using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Molinos.DataAgro.Entities.Dto.ControlDeBoletos
{
    public class ControlDeBoletosContratoDto
    {
        public string Id { get; set; }
        public string ContratoId { get; set; }
        public string Proveedor { get; set; }
        public string Corredor { get; set; }
        public DateTime? FechaDesde { get; set; }
        public DateTime? FechaHasta { get; set; }
        public DateTime? Fecha { get; set; }
        public string TipoNegocio { get; set; }
        public string Material { get; set; }
        public decimal? Cantidad { get; set; }
        public decimal? Precio { get; set; }
        public string Comercial { get; set; }
        public string MonedaId { get; set; }
        public string Campania { get; set; }
        public string Provincia { get; set; }
        public string Localidad { get; set; }
        public string ContratoSAP { get; set; }
        public string Negocio { get; set; }
        public bool? EPA { get; set; }
        public bool? EUDR { get; set; }
        public string SustentableTipoDBId { get; set; }
        public bool? Sustentable { get; set; }
        public decimal? Importe_Sustentable { get; set; }
        public string MonedaId_Sustentable { get; set; }
        public bool? TarifaAConvenir { get; set; }
        public DateTime? Fecha_Dolarizado { get; set; }
        public int? Dias_Pesificado { get; set; }
        public bool? NoInformaSIO { get; set; }
        public string CalidadDescripcion { get; set; }
        public int? Estado { get; set; }
        public string Observacion { get; set; }
        public string Moneda { get; set; }
        public string Moneda_Sustentable { get; set; }
        public string DestinoId { get; set; }
        public string DestinoDescripcion { get; set; }
        public int? CantidadCamiones { get; set; }
        public string Consignatario { get; set; }
        public string PlanCanje { get; set; }
        public string CondicionFijacion { get; set; }
        public string CD { get; set; }
        public bool? Warrant { get; set; }
        public bool? PagoDirectoVendedor { get; set; }
        public bool? EstablecimientoPropio { get; set; }
        public string BoletoId { get; set; }
        public string BolsaId { get; set; }
        public string BoletoDescripcion { get; set; }
        public string BolsaDescripcion { get; set; }
        public DateTime? DesdeFijacion { get; set; }
        public DateTime? HastaFijacion { get; set; }
        public string CondicionFijacionDescripcion { get; set; }
        public string ClasificacionId { get; set; }
        public string ClasificacionDescripcion { get; set; }
        public string StandardDeCalidadDescripcion { get; set; }
        public string CalidadEspecialDescripcion { get; set; }
        public string MercsDeposito { get; set; }
        public string ContratoCorredor { get; set; }
        public string ContratoVendedor { get; set; }
        public string SelCargoMOA { get; set; }
        public string SelCargoVendedor { get; set; }
        public string TipoFason { get; set; }
        public string Posicion { get; set; }
        public string Operador { get; set; }
        public decimal? PrecioNeto { get; set; }
        public string Pizarra { get; set; }
        public string ZonaDescripcion { get; set; }
        public string NivelTarifa { get; set; }
        public decimal? TarifaFlete { get; set; }
        public decimal? Compensacion { get; set; }
        public string Rechazo { get; set; }
        public DateTime? FechaCierta { get; set; }
        public decimal? PorcentajeDePago { get; set; }
        public string TipoAgenteCompraId { get; set; }
        public DateTime? FechaOperacion { get; set; }
        public string MotivoOperacionAnterior { get; set; }
        public string DescripcionOperacionAnterior { get; set; }
        public bool? PagoCBU { get; set; }
        public decimal? ChequeElectronicoValor { get; set; }
        public bool? CalidadTercero { get; set; }
        public bool? DolarizadoTercero { get; set; }
        public bool? PagoDiferidoTercero { get; set; }
        public bool? Canje { get; set; }
        public decimal? Monto { get; set; }
        public string MonedaCanjeId { get; set; }
        public string Insumo { get; set; }
        public bool? PrestamoDevolucion { get; set; }
        public string PlantaDestinoDescripcion { get; set; }
        public string ObservacionTercero { get; set; }
        public bool? SustentableTercero { get; set; }
        public bool? Venta { get; set; }
        public string FechaDesde_SustentableFormateado { get; set; }
        public string FechaHasta_SustentableFormateado { get; set; }
        public bool? ObligatoriedadCostoFinanciero { get; set; }
        public string PosicionCBOT { get; set; }
        public string TipoPosicionCBOT { get; set; }
        public string ProveedorCreador { get; set; }
        public bool? Cesion { get; set; }
        public string MotivoReemplazo { get; set; }
        public string AnulaYReemplazaContratoSAP { get; set; }
        public string ObligatoriedadBonificacionDesc { get; set; }
        public bool? Condicional { get; set; }
        public decimal? CondicionalCantidad { get; set; }
        public string CondicionalFechaFormateado { get; set; }
        public string CondicionalMonedaId { get; set; }
        public string CondicionalPosicion { get; set; }
        public decimal? CondicionalPrecio { get; set; }
        public string CondicionalContratoSAP { get; set; }
        public string MailVentaBoleto { get; set; }
        public string RazonSocialProveedorComisionista { get; set; }
        public decimal? KgMinimo { get; set; }
        public decimal? KgMaximo { get; set; }
        public bool? ConDescarga { get; set; }
        public int? ComercialZonaId { get; set; }
        public string FijacionDePrecioContratoId { get; set; }
        public int? TipoNegocioId { get; set; }
        public string AcuerdoId { get; set; }
        public string AgenteId { get; set; }
        public string FasonId { get; set; }
        public int? MaterialId { get; set; }
        public bool? Virtual { get; set; }
        public decimal? CantidadDeposito { get; set; }
        public string FechaDolarizadoOriginalFormateado { get; set; }
        public string FechaHastaOriginalFormateado { get; set; }
        public bool? ServicioModificado { get; set; }
        public bool? DolarExportador { get; set; }

        // Propiedades adicionales encontradas en otros métodos
        public string TipoAgenteCompra { get; set; }
        public string Hora { get; set; }
        public string GrupoCompraDescripcion { get; set; }
        public string ComercialCreador { get; set; }
        public string Estado_Contrato { get; set; }
        public int? ComercialCreadorId { get; set; }
        public int? ComercialId { get; set; }
        public int? StandardCalidadId { get; set; }
        public decimal? ImporteFinanciero { get; set; }
        public decimal? ImporteRedespacho { get; set; }
        public decimal? ImporteComision { get; set; }
        public decimal? ImporteBonificacion { get; set; }
        public bool? OcultarEnTablero { get; set; }
        public int? Ampliacion { get; set; }
        public int? Ampliaciones { get; set; }
        public string PrecioPlazo { get; set; }
        public string AnulaYReemplazaContratoId { get; set; }
    }
}
