using System;
using System.Collections.Generic;

namespace Molinos.DataAgro.Entities.Dto
{
    public class BasicoContrato
    {
        public string ChequeElectronicoValor;
        public int Id { get; set; }
        public string Cuit { get; set; }
        public int ContratoId { get; set; }
        public int MaterialId { get; set; }
        public int? NivelTarifaId { get; set; }
        public int TipoNegocioId { get; set; }
        public double Cantidad { get; set; }
        public decimal Precio { get; set; }
        public string PrecioPlazo { get; set; }
        public DateTime? FechaEntrega { get; set; }
        public int? CampanaId { get; set; }
        public DateTime? FechaDesde { get; set; }
        public string FechaDesdeFormateado { get; set; }
        public DateTime? FechaHasta { get; set; }
        public string FechaHastaFormateado { get; set; }
        public int ProveedorId { get; set; }
        public string MonedaId { get; set; }
        public string Moneda { get; set; }
        public DateTime? Fecha { get; set; }
        public string FechaFormateado { get; set; }
        public string Hora { get; set; }
        public string NivelTarifa { get; set; }
        public decimal? TarifaFlete { get; set; }
        public int GrupoCompra { get; set; }
        public string GrupoCompraDescripcion { get; set; }
        public int? ComercialId { get; set; }
        public int? ComercialCreadorId { get; set; }
        public int? ProvinciaId { get; set; }
        public int? LocalidadId { get; set; }
        public bool? Base { get; set; }
        public DateTime? Fecha_Dolarizado { get; set; }
        public string Fecha_DolarizadoFormateado { get; set; }
        public int? Dias_Pesificado { get; set; }
        public bool? NoInformaSIO { get; set; }
        public bool? TrigoEspecial { get; set; }
        public int? Estado { get; set; }
        public string UsuarioId { get; set; }
        public string ContratoSAP { get; set; }
        public double? Ampliaciones { get; set; }
        public string TipoNegocio { get; set; }
        public string Proveedor { get; set; }
        public string ProveedorDireccion { get; set; }
        public string ProveedorLocalidad { get; set; }
        public string ProveedorProvincia { get; set; }
        public string ProveedorCP { get; set; }
        public string RazonSocialCorredor { get; set; }
        public string CUITCorredor { get; set; }
        public string Comercial { get; set; }
        public string ComercialCreador { get; set; }
        public string Material { get; set; }
        public string Campania { get; set; }
        public string Provincia { get; set; }
        public string Localidad { get; set; }
        public string Estado_Contrato { get; set; }
        //public int? Cantidad_F { get; set; }
        //public decimal? Precio_F { get; set; }
        //public string Proveedor_F { get; set; }
        //public string Fecha_F { get; set; }
        //public string Material_F { get; set; }
        //public string MonedaId_F { get; set; }
        //public string Moneda_F { get; set; }
        //public int? Ampliaciones_F { get; set; }
        public DateTime Fecha_Order { get; set; }
        public int Estado_Order { get; set; }
        public string Observacion { get; set; }
        //public string Observacion_F { get; set; }
        public int? FijacionDePrecioContratoId { get; set; }
        public bool? Dolarizado { get; set; }
        public bool? Pesificado { get; set; }
        public string Negocio { get; set; }
        public int? ClasificacionId { get; set; }
        public string ClasificacionDescripcion { get; set; }
        public int? DestinoId { get; set; }
        public string DestinoDescripcion { get; set; }
        public int? CantidadCamiones { get; set; }
        public bool? Consignatario { get; set; }
        public bool? PlanCanje { get; set; }
        public int? CondicionFijacion { get; set; }
        public bool? CD { get; set; }
        public bool? Warrant { get; set; }
        public bool? PagoDirectoVendedor { get; set; }
        public string CalidadDescripcion { get; set; }
        public bool? EstablecimientoPropio { get; set; }
        public int? BoletoId { get; set; }
        public int? BolsaId { get; set; }
        public string BoletoDescripcion { get; set; }
        public string BolsaDescripcion { get; set; }
        public DateTime? DesdeFijacion { get; set; }
        public string DesdeFijacionFormateado { get; set; }
        public DateTime? HastaFijacion { get; set; }
        public string HastaFijacionFormateado { get; set; }
        public string CondicionFijacionDescripcion { get; set; }
        public List<DescuentoBonificacionDto> Descuentos { get; set; }
        public List<CalidadDto> Calidades { get; set; }
        public bool? MercsDeposito { get; set; }
        public int CorredorId { get; set; }
        public DatosFijacionDeContratoDto DatosFijacion { get; set; }
        public decimal? PorcentajeComision { get; set; }
        public string ContratoCorredor { get; set; }
        public string ContratoVendedor { get; set; }
        public bool? SelCargoMOA { get; set; }
        public bool? SelCargoVendedor { get; set; }
        public bool? Madre { get; set; }
        public bool? EsFason { get; set; }
        public string ContratoMadre { get; set; }
        public string Posicion { get; set; }
        public string TipoFason { get; set; }
        public int TipoFasonId { get; set; }
        public int FasonId { get; set; }
        public string Operador { get; set; }
        public int OperadorId { get; set; }
        public int AgenteId { get; set; }
        public List<AperturaPrecioDto> AperturaPrecios { get; set; }
        public List<PrecioPactadosDto> PreciosPactados { get; set; }
        public decimal? PrecioNeto { get; set; }
        public bool? Pizarra { get; set; }
        public int? StandardCalidadId { get; set; }
        public string StandardDeCalidadDescripcion { get; set; }
        public bool? PagoDiferido { get; set; }
        public int? PagoDiferidoTerceroId { get; set; }
        public int? ZonaId { get; set; }
        public string ZonaDescripcion { get; set; }
        public int? AcuerdoId { get; set; }
        public decimal? ImporteFinanciero { get; set; }
        public decimal? ImporteRedespacho { get; set; }
        public decimal? ImporteComision { get; set; }
        public decimal? ImporteBonificacion { get; set; }
        public decimal? PorcentajeBonificacion { get; set; }
        public bool? Compensacion { get; set; }
        public int? Acuerdo { get; set; }
        public string Rechazo { get; set; }
        public int? ComercialZonaId { get; set; }
        public string ComercialZonaDescripcion { get; set; }
        public bool OcultarEnTablero { get; set; }
        public string FechaCiertaFormateado { get; set; }
        public DateTime? FechaCierta { get; set; }
        public string MonedaBonificacion { get; set; }
        public string MesPosicion { get; set; }
        public int? CampanaMaterialId { get; set; }
        public int? ContratoAcuerdoId { get; set; }
        public decimal? PorcentajeDePago { get; set; }
        public int? TipoAgenteCompraId { get; set; }
        public string CaratulaExtension { get; set; }
        public string CaratulaMAT { get; set; }
        public decimal? PrecioAjusteComision { get; set; }
        public string MonedaAjusteComisionId { get; set; }
        public DateTime? FechaOperacion { get; set; }
        public string FechaOperacionFormateado { get; set; }
        public string MotivoOperacionAnterior { get; set; }
        public string UsuarioConfirmador { get; set; }
        public DateTime? FechaConfirmacion { get; set; }
        public int CantidadMaximaCupo { get; set; }
        public bool? ChequeElectronico { get; set; }
        public bool? DolarizadoExpress { get; set; }
        public string DolarizadoExpressValor { get; set; }
        public string PagoCBU { get; set; }
        public string DolarizadoValor { get; set; }
        public bool? CalidadTercero { get; set; }
        public bool? DolarizadoTercero { get; set; }
        public bool? PagoDiferidoTercero { get; set; }
        public string ObservacionTercero { get; set; }
        public bool? Canje { get; set; }
        public string MonedaCanjeId { get; set; }
        public decimal? Monto { get; set; }
        public string Insumo { get; set; }
        public bool PrestamoDevolucion { get; set; }
        public int PlantaDestinoId { get; set; }
        public string PlantaDestinoDescripcion { get; set; }
        public bool? DolarizadoCorredor { get; set; }
        public bool? SustentableTercero { get; set; }
        public bool? Venta { get; set; }
        public bool? Anticipo { get; set; }
        public bool? Cesion { get; set; }
        public string ClasificacionContrato { get; set; }
        public string TipoAgenteCompra { get; set; }
        public decimal? ImporteAPrecioContrato { get; set; }
        public decimal? PorcentajeAPrecioContrato { get; set; }
        public string MonedaAPrecioContrato { get; set; }
        public decimal? ImporteSobrePrecioContrato { get; set; }
        public decimal? PorcentajeSobrePrecioContrato { get; set; }
        public string MonedaSobrePrecioContrato { get; set; }
        public double CantidadAmpliado { get; set; }
        public bool? ObligatoriedadCostoFinanciero { get; set; }
        public bool? ObligatoriedadBonificacion { get; set; }
        public string ObligatoriedadCostoFinancieroDesc { get; set; }
        public string PosicionCBOT { get; set; }
        public int? ProveedorCreador { get; set; }
        public decimal? ImporteBasis { get; set; }
        public string MonedaFinanciero { get; set; }
        public string MonedaRedespacho { get; set; }
        public string MonedaComision { get; set; }
        public string MonedaBasis { get; set; }
        public bool? Virtual { get; set; }
        public string VirtualDescripcion { get; set; }
        public string UsuarioTercero { get; set; }
        public int? TipoPosicionCBOTId { get; set; }
        public string TipoPosicionCBOT { get; set; }
        public DateTime? FechaCiertaHasta { get; set; }
        public bool FechaCiertaTilde { get; set; }
        public int? AnulaYReemplazaContratoId { get; set; }
        public string AnulaYReemplazaContratoSAP { get; set; }
        public string MotivoReemplazo { get; set; }
        public int? ProcedenciaVentaId { get; set; }
        public int? CamaraId { get; set; }
        public int? ComisionAFavorId { get; set; }
        public decimal? PorcentajeComisionVenta { get; set; }
        public string FleteACargo { get; set; }
        public string KgBalanza { get; set; }
        public int? CondicionDePagoDiaPesificado { get; set; }
        public string CondicionDePagoTipoPesificado { get; set; }
        public int? CondicionDePagoPesificadoVentaId { get; set; }
        public string Pago { get; set; }
        public int? CondicionDePagoDiaFijacion { get; set; }
        public string CondicionDePagoTipoFijacion { get; set; }
        public int? CondicionDePagoFijacionVentaId { get; set; }
        public int? ProvinciaVentaId { get; set; }
        public string ProvinciaVenta { get; set; }
        public string LocalidadVenta { get; set; }
        public int? CreditoDisponible { get; set; }
        public string DescripcionOperacionAnterior { get; set; }
        public string ObligatoriedadBonificacionDesc { get; set; }
        public decimal? PrecioPonderado { get; set; }
        public decimal? PrecioNetoPonderado { get; set; }
        public bool? EsUsuarioExterno { get; set; }
        public bool? Condicional { get; set; }
        public double? CondicionalCantidad { get; set; }
        public DateTime? CondicionalFecha { get; set; }
        public string CondicionalMonedaId { get; set; }
        public string CondicionalPosicion { get; set; }
        public decimal? CondicionalPrecio { get; set; }
        public string CondicionalFechaFormateado { get; set; }
        public int? CondicionalContratoId { get; set; }
        public string CondicionalContratoSAP { get; set; }
        public int? BoletoVentaId { get; set; }
        public string MailVentaBoleto { get; set; }
        public int KgMinimo { get; set; }
        public int KgMaximo { get; set; }
        public int? ProveedorComisionistaId { get; set; }
        public string RazonSocialProveedorComisionista { get; set; }
        public int StandardDeCalidadId { get; set; }
        public string DestinoLocalidad { get; set; }
        public string DestinoProvincia { get; set; }
        public string MonedaCanjeDescripcion { get; set; }
        public string CondicionalMonedaDescripcion { get; set; }
        public int? BoletoContratoId { get; set; }
        public string RazonSocialProveedor { get; set; }
        public string Corredor { get; set; }
        public int? BolsaContratoId { get; set; }
        public bool? TarifaAConvenir { get; set; }
        public double? CantidadDeposito { get; set; }
        public string MercaderiaDescripcion { get; set; }
        public string FijacionSAP { get; set; }
        public DateTime? DolarizadoOriginal { get; set; }
        public string FechaDolarizadoOriginalFormateado { get; set; }
        public DateTime? HastaOriginal { get; set; }
        public string FechaHastaOriginalFormateado { get; set; }
        public List<ServicioValorDto> Servicios { get; set; }
        public bool ServicioModificado { get; set; }
        public bool? Sustentable { get; set; }
        public decimal? Importe_Sustentable { get; set; }
        public string MonedaId_Sustentable { get; set; }
        public string Moneda_Sustentable { get; set; }
        public DateTime? FechaDesde_Sustentable { get; set; }
        public string FechaDesde_SustentableFormateado { get; set; }
        public DateTime? FechaHasta_Sustentable { get; set; }
        public string FechaHasta_SustentableFormateado { get; set; }
        public bool? EPA { get; set; }
        public int? SustentableTipoDBId { get; set; }
        public string SustentableTipoDB { get; set; }
        public bool? ConDescarga { get; set; }
        public bool? DolarExportador { get; set; }
        public int? TipoDeCambioId { get; set; }
    }

    public class StoredPorContratoResult
    {
        public List<BasicoContrato> BasicoContratoTraerPorFiltro { get; set; }
        public List<BasicoContrato> ReporteContratoContratoTraerPorFiltro { get; set; }
    }
}