//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Molinos.DataAgro.Agent.CriterioCDWarrant {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="namespace:dataagro", ConfigurationName="CriterioCDWarrant.SI_ZMPWS_DATAAGRO_CD_WARRANTS")]
    public interface SI_ZMPWS_DATAAGRO_CD_WARRANTS {
        
        // CODEGEN: Generating message contract since the operation SI_ZMPWS_DATAAGRO_CD_WARRANTS is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Molinos.DataAgro.Agent.CriterioCDWarrant.SI_ZMPWS_DATAAGRO_CD_WARRANTSResponse SI_ZMPWS_DATAAGRO_CD_WARRANTS(Molinos.DataAgro.Agent.CriterioCDWarrant.SI_ZMPWS_DATAAGRO_CD_WARRANTSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<Molinos.DataAgro.Agent.CriterioCDWarrant.SI_ZMPWS_DATAAGRO_CD_WARRANTSResponse> SI_ZMPWS_DATAAGRO_CD_WARRANTSAsync(Molinos.DataAgro.Agent.CriterioCDWarrant.SI_ZMPWS_DATAAGRO_CD_WARRANTSRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_MPRFC_CD_WARRANTS : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iM_FECHA_DESDEField;
        
        private string iM_FECHA_HASTAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string IM_FECHA_DESDE {
            get {
                return this.iM_FECHA_DESDEField;
            }
            set {
                this.iM_FECHA_DESDEField = value;
                this.RaisePropertyChanged("IM_FECHA_DESDE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string IM_FECHA_HASTA {
            get {
                return this.iM_FECHA_HASTAField;
            }
            set {
                this.iM_FECHA_HASTAField = value;
                this.RaisePropertyChanged("IM_FECHA_HASTA");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMPES5610 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cONTRATOField;
        
        private string cD_WARRANTSField;
        
        private decimal kILOSField;
        
        private string fECHAField;
        
        private decimal pRECIOField;
        
        private string mONEDAField;
        
        private string mATERIALField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CONTRATO {
            get {
                return this.cONTRATOField;
            }
            set {
                this.cONTRATOField = value;
                this.RaisePropertyChanged("CONTRATO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string CD_WARRANTS {
            get {
                return this.cD_WARRANTSField;
            }
            set {
                this.cD_WARRANTSField = value;
                this.RaisePropertyChanged("CD_WARRANTS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal KILOS {
            get {
                return this.kILOSField;
            }
            set {
                this.kILOSField = value;
                this.RaisePropertyChanged("KILOS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string FECHA {
            get {
                return this.fECHAField;
            }
            set {
                this.fECHAField = value;
                this.RaisePropertyChanged("FECHA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal PRECIO {
            get {
                return this.pRECIOField;
            }
            set {
                this.pRECIOField = value;
                this.RaisePropertyChanged("PRECIO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string MONEDA {
            get {
                return this.mONEDAField;
            }
            set {
                this.mONEDAField = value;
                this.RaisePropertyChanged("MONEDA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string MATERIAL {
            get {
                return this.mATERIALField;
            }
            set {
                this.mATERIALField = value;
                this.RaisePropertyChanged("MATERIAL");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_MPRFC_CD_WARRANTSResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZMPES5610[] eX_SALIDAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZMPES5610[] EX_SALIDA {
            get {
                return this.eX_SALIDAField;
            }
            set {
                this.eX_SALIDAField = value;
                this.RaisePropertyChanged("EX_SALIDA");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_ZMPWS_DATAAGRO_CD_WARRANTSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public Molinos.DataAgro.Agent.CriterioCDWarrant.Z_MPRFC_CD_WARRANTS Z_MPRFC_CD_WARRANTS;
        
        public SI_ZMPWS_DATAAGRO_CD_WARRANTSRequest() {
        }
        
        public SI_ZMPWS_DATAAGRO_CD_WARRANTSRequest(Molinos.DataAgro.Agent.CriterioCDWarrant.Z_MPRFC_CD_WARRANTS Z_MPRFC_CD_WARRANTS) {
            this.Z_MPRFC_CD_WARRANTS = Z_MPRFC_CD_WARRANTS;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_ZMPWS_DATAAGRO_CD_WARRANTSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public Molinos.DataAgro.Agent.CriterioCDWarrant.Z_MPRFC_CD_WARRANTSResponse Z_MPRFC_CD_WARRANTSResponse;
        
        public SI_ZMPWS_DATAAGRO_CD_WARRANTSResponse() {
        }
        
        public SI_ZMPWS_DATAAGRO_CD_WARRANTSResponse(Molinos.DataAgro.Agent.CriterioCDWarrant.Z_MPRFC_CD_WARRANTSResponse Z_MPRFC_CD_WARRANTSResponse) {
            this.Z_MPRFC_CD_WARRANTSResponse = Z_MPRFC_CD_WARRANTSResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_ZMPWS_DATAAGRO_CD_WARRANTSChannel : Molinos.DataAgro.Agent.CriterioCDWarrant.SI_ZMPWS_DATAAGRO_CD_WARRANTS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_ZMPWS_DATAAGRO_CD_WARRANTSClient : System.ServiceModel.ClientBase<Molinos.DataAgro.Agent.CriterioCDWarrant.SI_ZMPWS_DATAAGRO_CD_WARRANTS>, Molinos.DataAgro.Agent.CriterioCDWarrant.SI_ZMPWS_DATAAGRO_CD_WARRANTS {
        
        public SI_ZMPWS_DATAAGRO_CD_WARRANTSClient() {
        }
        
        public SI_ZMPWS_DATAAGRO_CD_WARRANTSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SI_ZMPWS_DATAAGRO_CD_WARRANTSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_ZMPWS_DATAAGRO_CD_WARRANTSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_ZMPWS_DATAAGRO_CD_WARRANTSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Molinos.DataAgro.Agent.CriterioCDWarrant.SI_ZMPWS_DATAAGRO_CD_WARRANTSResponse Molinos.DataAgro.Agent.CriterioCDWarrant.SI_ZMPWS_DATAAGRO_CD_WARRANTS.SI_ZMPWS_DATAAGRO_CD_WARRANTS(Molinos.DataAgro.Agent.CriterioCDWarrant.SI_ZMPWS_DATAAGRO_CD_WARRANTSRequest request) {
            return base.Channel.SI_ZMPWS_DATAAGRO_CD_WARRANTS(request);
        }
        
        public Molinos.DataAgro.Agent.CriterioCDWarrant.Z_MPRFC_CD_WARRANTSResponse SI_ZMPWS_DATAAGRO_CD_WARRANTS(Molinos.DataAgro.Agent.CriterioCDWarrant.Z_MPRFC_CD_WARRANTS Z_MPRFC_CD_WARRANTS) {
            Molinos.DataAgro.Agent.CriterioCDWarrant.SI_ZMPWS_DATAAGRO_CD_WARRANTSRequest inValue = new Molinos.DataAgro.Agent.CriterioCDWarrant.SI_ZMPWS_DATAAGRO_CD_WARRANTSRequest();
            inValue.Z_MPRFC_CD_WARRANTS = Z_MPRFC_CD_WARRANTS;
            Molinos.DataAgro.Agent.CriterioCDWarrant.SI_ZMPWS_DATAAGRO_CD_WARRANTSResponse retVal = ((Molinos.DataAgro.Agent.CriterioCDWarrant.SI_ZMPWS_DATAAGRO_CD_WARRANTS)(this)).SI_ZMPWS_DATAAGRO_CD_WARRANTS(inValue);
            return retVal.Z_MPRFC_CD_WARRANTSResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Molinos.DataAgro.Agent.CriterioCDWarrant.SI_ZMPWS_DATAAGRO_CD_WARRANTSResponse> Molinos.DataAgro.Agent.CriterioCDWarrant.SI_ZMPWS_DATAAGRO_CD_WARRANTS.SI_ZMPWS_DATAAGRO_CD_WARRANTSAsync(Molinos.DataAgro.Agent.CriterioCDWarrant.SI_ZMPWS_DATAAGRO_CD_WARRANTSRequest request) {
            return base.Channel.SI_ZMPWS_DATAAGRO_CD_WARRANTSAsync(request);
        }
        
        public System.Threading.Tasks.Task<Molinos.DataAgro.Agent.CriterioCDWarrant.SI_ZMPWS_DATAAGRO_CD_WARRANTSResponse> SI_ZMPWS_DATAAGRO_CD_WARRANTSAsync(Molinos.DataAgro.Agent.CriterioCDWarrant.Z_MPRFC_CD_WARRANTS Z_MPRFC_CD_WARRANTS) {
            Molinos.DataAgro.Agent.CriterioCDWarrant.SI_ZMPWS_DATAAGRO_CD_WARRANTSRequest inValue = new Molinos.DataAgro.Agent.CriterioCDWarrant.SI_ZMPWS_DATAAGRO_CD_WARRANTSRequest();
            inValue.Z_MPRFC_CD_WARRANTS = Z_MPRFC_CD_WARRANTS;
            return ((Molinos.DataAgro.Agent.CriterioCDWarrant.SI_ZMPWS_DATAAGRO_CD_WARRANTS)(this)).SI_ZMPWS_DATAAGRO_CD_WARRANTSAsync(inValue);
        }
    }
}
