//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Molinos.DataAgro.Agent.ConsultarEstadoBoleto {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="namespace:dataagro", ConfigurationName="ConsultarEstadoBoleto.SI_ZMPWS_DATAAGRO_CONSULTAR_ESTADO_BOLET")]
    public interface SI_ZMPWS_DATAAGRO_CONSULTAR_ESTADO_BOLET {
        
        // CODEGEN: Generating message contract since the operation SI_ZMPWS_DATAAGRO_CONSULTAR_ESTADO_BOLET is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Molinos.DataAgro.Agent.ConsultarEstadoBoleto.SI_ZMPWS_DATAAGRO_CONSULTAR_ESTADO_BOLETResponse SI_ZMPWS_DATAAGRO_CONSULTAR_ESTADO_BOLET(Molinos.DataAgro.Agent.ConsultarEstadoBoleto.SI_ZMPWS_DATAAGRO_CONSULTAR_ESTADO_BOLETRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<Molinos.DataAgro.Agent.ConsultarEstadoBoleto.SI_ZMPWS_DATAAGRO_CONSULTAR_ESTADO_BOLETResponse> SI_ZMPWS_DATAAGRO_CONSULTAR_ESTADO_BOLETAsync(Molinos.DataAgro.Agent.ConsultarEstadoBoleto.SI_ZMPWS_DATAAGRO_CONSULTAR_ESTADO_BOLETRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_MPRFC_CONSULTAR_ESTADO_BOLET : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iM_CONTRATOField;
        
        private string iM_FIJACIONField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string IM_CONTRATO {
            get {
                return this.iM_CONTRATOField;
            }
            set {
                this.iM_CONTRATOField = value;
                this.RaisePropertyChanged("IM_CONTRATO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string IM_FIJACION {
            get {
                return this.iM_FIJACIONField;
            }
            set {
                this.iM_FIJACIONField = value;
                this.RaisePropertyChanged("IM_FIJACION");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMPES6680 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cONTRNUMField;
        
        private string fE_DESDEField;
        
        private string fE_HASTAField;
        
        private decimal cANT_MAXField;
        
        private decimal cANT_MINField;
        
        private string mEINSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CONTRNUM {
            get {
                return this.cONTRNUMField;
            }
            set {
                this.cONTRNUMField = value;
                this.RaisePropertyChanged("CONTRNUM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string FE_DESDE {
            get {
                return this.fE_DESDEField;
            }
            set {
                this.fE_DESDEField = value;
                this.RaisePropertyChanged("FE_DESDE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string FE_HASTA {
            get {
                return this.fE_HASTAField;
            }
            set {
                this.fE_HASTAField = value;
                this.RaisePropertyChanged("FE_HASTA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal CANT_MAX {
            get {
                return this.cANT_MAXField;
            }
            set {
                this.cANT_MAXField = value;
                this.RaisePropertyChanged("CANT_MAX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal CANT_MIN {
            get {
                return this.cANT_MINField;
            }
            set {
                this.cANT_MINField = value;
                this.RaisePropertyChanged("CANT_MIN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string MEINS {
            get {
                return this.mEINSField;
            }
            set {
                this.mEINSField = value;
                this.RaisePropertyChanged("MEINS");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_MPRFC_CONSULTAR_ESTADO_BOLETResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string eX_ANULADOField;
        
        private ZMPES6680[] eX_COND_FIJACIONField;
        
        private string eX_CONTRATOField;
        
        private string eX_FECHA_CONFIRField;
        
        private string eX_FE_RECEP_BOLETOField;
        
        private string eX_GENERADOField;
        
        private string eX_VERSIONField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string EX_ANULADO {
            get {
                return this.eX_ANULADOField;
            }
            set {
                this.eX_ANULADOField = value;
                this.RaisePropertyChanged("EX_ANULADO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZMPES6680[] EX_COND_FIJACION {
            get {
                return this.eX_COND_FIJACIONField;
            }
            set {
                this.eX_COND_FIJACIONField = value;
                this.RaisePropertyChanged("EX_COND_FIJACION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string EX_CONTRATO {
            get {
                return this.eX_CONTRATOField;
            }
            set {
                this.eX_CONTRATOField = value;
                this.RaisePropertyChanged("EX_CONTRATO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string EX_FECHA_CONFIR {
            get {
                return this.eX_FECHA_CONFIRField;
            }
            set {
                this.eX_FECHA_CONFIRField = value;
                this.RaisePropertyChanged("EX_FECHA_CONFIR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string EX_FE_RECEP_BOLETO {
            get {
                return this.eX_FE_RECEP_BOLETOField;
            }
            set {
                this.eX_FE_RECEP_BOLETOField = value;
                this.RaisePropertyChanged("EX_FE_RECEP_BOLETO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string EX_GENERADO {
            get {
                return this.eX_GENERADOField;
            }
            set {
                this.eX_GENERADOField = value;
                this.RaisePropertyChanged("EX_GENERADO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string EX_VERSION {
            get {
                return this.eX_VERSIONField;
            }
            set {
                this.eX_VERSIONField = value;
                this.RaisePropertyChanged("EX_VERSION");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_ZMPWS_DATAAGRO_CONSULTAR_ESTADO_BOLETRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public Molinos.DataAgro.Agent.ConsultarEstadoBoleto.Z_MPRFC_CONSULTAR_ESTADO_BOLET Z_MPRFC_CONSULTAR_ESTADO_BOLET;
        
        public SI_ZMPWS_DATAAGRO_CONSULTAR_ESTADO_BOLETRequest() {
        }
        
        public SI_ZMPWS_DATAAGRO_CONSULTAR_ESTADO_BOLETRequest(Molinos.DataAgro.Agent.ConsultarEstadoBoleto.Z_MPRFC_CONSULTAR_ESTADO_BOLET Z_MPRFC_CONSULTAR_ESTADO_BOLET) {
            this.Z_MPRFC_CONSULTAR_ESTADO_BOLET = Z_MPRFC_CONSULTAR_ESTADO_BOLET;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_ZMPWS_DATAAGRO_CONSULTAR_ESTADO_BOLETResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public Molinos.DataAgro.Agent.ConsultarEstadoBoleto.Z_MPRFC_CONSULTAR_ESTADO_BOLETResponse Z_MPRFC_CONSULTAR_ESTADO_BOLETResponse;
        
        public SI_ZMPWS_DATAAGRO_CONSULTAR_ESTADO_BOLETResponse() {
        }
        
        public SI_ZMPWS_DATAAGRO_CONSULTAR_ESTADO_BOLETResponse(Molinos.DataAgro.Agent.ConsultarEstadoBoleto.Z_MPRFC_CONSULTAR_ESTADO_BOLETResponse Z_MPRFC_CONSULTAR_ESTADO_BOLETResponse) {
            this.Z_MPRFC_CONSULTAR_ESTADO_BOLETResponse = Z_MPRFC_CONSULTAR_ESTADO_BOLETResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_ZMPWS_DATAAGRO_CONSULTAR_ESTADO_BOLETChannel : Molinos.DataAgro.Agent.ConsultarEstadoBoleto.SI_ZMPWS_DATAAGRO_CONSULTAR_ESTADO_BOLET, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_ZMPWS_DATAAGRO_CONSULTAR_ESTADO_BOLETClient : System.ServiceModel.ClientBase<Molinos.DataAgro.Agent.ConsultarEstadoBoleto.SI_ZMPWS_DATAAGRO_CONSULTAR_ESTADO_BOLET>, Molinos.DataAgro.Agent.ConsultarEstadoBoleto.SI_ZMPWS_DATAAGRO_CONSULTAR_ESTADO_BOLET {
        
        public SI_ZMPWS_DATAAGRO_CONSULTAR_ESTADO_BOLETClient() {
        }
        
        public SI_ZMPWS_DATAAGRO_CONSULTAR_ESTADO_BOLETClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SI_ZMPWS_DATAAGRO_CONSULTAR_ESTADO_BOLETClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_ZMPWS_DATAAGRO_CONSULTAR_ESTADO_BOLETClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_ZMPWS_DATAAGRO_CONSULTAR_ESTADO_BOLETClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Molinos.DataAgro.Agent.ConsultarEstadoBoleto.SI_ZMPWS_DATAAGRO_CONSULTAR_ESTADO_BOLETResponse Molinos.DataAgro.Agent.ConsultarEstadoBoleto.SI_ZMPWS_DATAAGRO_CONSULTAR_ESTADO_BOLET.SI_ZMPWS_DATAAGRO_CONSULTAR_ESTADO_BOLET(Molinos.DataAgro.Agent.ConsultarEstadoBoleto.SI_ZMPWS_DATAAGRO_CONSULTAR_ESTADO_BOLETRequest request) {
            return base.Channel.SI_ZMPWS_DATAAGRO_CONSULTAR_ESTADO_BOLET(request);
        }
        
        public Molinos.DataAgro.Agent.ConsultarEstadoBoleto.Z_MPRFC_CONSULTAR_ESTADO_BOLETResponse SI_ZMPWS_DATAAGRO_CONSULTAR_ESTADO_BOLET(Molinos.DataAgro.Agent.ConsultarEstadoBoleto.Z_MPRFC_CONSULTAR_ESTADO_BOLET Z_MPRFC_CONSULTAR_ESTADO_BOLET) {
            Molinos.DataAgro.Agent.ConsultarEstadoBoleto.SI_ZMPWS_DATAAGRO_CONSULTAR_ESTADO_BOLETRequest inValue = new Molinos.DataAgro.Agent.ConsultarEstadoBoleto.SI_ZMPWS_DATAAGRO_CONSULTAR_ESTADO_BOLETRequest();
            inValue.Z_MPRFC_CONSULTAR_ESTADO_BOLET = Z_MPRFC_CONSULTAR_ESTADO_BOLET;
            Molinos.DataAgro.Agent.ConsultarEstadoBoleto.SI_ZMPWS_DATAAGRO_CONSULTAR_ESTADO_BOLETResponse retVal = ((Molinos.DataAgro.Agent.ConsultarEstadoBoleto.SI_ZMPWS_DATAAGRO_CONSULTAR_ESTADO_BOLET)(this)).SI_ZMPWS_DATAAGRO_CONSULTAR_ESTADO_BOLET(inValue);
            return retVal.Z_MPRFC_CONSULTAR_ESTADO_BOLETResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Molinos.DataAgro.Agent.ConsultarEstadoBoleto.SI_ZMPWS_DATAAGRO_CONSULTAR_ESTADO_BOLETResponse> Molinos.DataAgro.Agent.ConsultarEstadoBoleto.SI_ZMPWS_DATAAGRO_CONSULTAR_ESTADO_BOLET.SI_ZMPWS_DATAAGRO_CONSULTAR_ESTADO_BOLETAsync(Molinos.DataAgro.Agent.ConsultarEstadoBoleto.SI_ZMPWS_DATAAGRO_CONSULTAR_ESTADO_BOLETRequest request) {
            return base.Channel.SI_ZMPWS_DATAAGRO_CONSULTAR_ESTADO_BOLETAsync(request);
        }
        
        public System.Threading.Tasks.Task<Molinos.DataAgro.Agent.ConsultarEstadoBoleto.SI_ZMPWS_DATAAGRO_CONSULTAR_ESTADO_BOLETResponse> SI_ZMPWS_DATAAGRO_CONSULTAR_ESTADO_BOLETAsync(Molinos.DataAgro.Agent.ConsultarEstadoBoleto.Z_MPRFC_CONSULTAR_ESTADO_BOLET Z_MPRFC_CONSULTAR_ESTADO_BOLET) {
            Molinos.DataAgro.Agent.ConsultarEstadoBoleto.SI_ZMPWS_DATAAGRO_CONSULTAR_ESTADO_BOLETRequest inValue = new Molinos.DataAgro.Agent.ConsultarEstadoBoleto.SI_ZMPWS_DATAAGRO_CONSULTAR_ESTADO_BOLETRequest();
            inValue.Z_MPRFC_CONSULTAR_ESTADO_BOLET = Z_MPRFC_CONSULTAR_ESTADO_BOLET;
            return ((Molinos.DataAgro.Agent.ConsultarEstadoBoleto.SI_ZMPWS_DATAAGRO_CONSULTAR_ESTADO_BOLET)(this)).SI_ZMPWS_DATAAGRO_CONSULTAR_ESTADO_BOLETAsync(inValue);
        }
    }
}
