//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Molinos.DataAgro.Agent.ConfirmaQAConsultaTrackingInteraccionesFecha {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://confirma.com.ar/gd/2012/05/consultadocumentotrackinginteraccionesfechas", ConfigurationName="ConfirmaQAConsultaTrackingInteraccionesFecha.IConsultaDocumentoTrackingInteraccio" +
        "nesFechasService")]
    public interface IConsultaDocumentoTrackingInteraccionesFechasService {
        
        // CODEGEN: Generating message contract since the operation ConsultaDocumentoTrackingInteracciones is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://confirma.com.ar/gd/2012/05/consultadocumentotrackinginteraccionesfechas", ReplyAction="http://confirma.com.ar/gd/2012/05/consultadocumentotrackinginteraccionesfechas/IC" +
            "onsultaDocumentoTrackingInteraccionesFechasService/ConsultaDocumentoTrackingInte" +
            "raccionesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Molinos.DataAgro.Agent.ConfirmaQAConsultaTrackingInteraccionesFecha.ConsultaDocumentoTrackingInteraccionesMasivoResponse ConsultaDocumentoTrackingInteracciones(Molinos.DataAgro.Agent.ConfirmaQAConsultaTrackingInteraccionesFecha.ConsultaDocumentoTrackingInteraccionesMasivo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://confirma.com.ar/gd/2012/05/consultadocumentotrackinginteraccionesfechas", ReplyAction="http://confirma.com.ar/gd/2012/05/consultadocumentotrackinginteraccionesfechas/IC" +
            "onsultaDocumentoTrackingInteraccionesFechasService/ConsultaDocumentoTrackingInte" +
            "raccionesResponse")]
        System.Threading.Tasks.Task<Molinos.DataAgro.Agent.ConfirmaQAConsultaTrackingInteraccionesFecha.ConsultaDocumentoTrackingInteraccionesMasivoResponse> ConsultaDocumentoTrackingInteraccionesAsync(Molinos.DataAgro.Agent.ConfirmaQAConsultaTrackingInteraccionesFecha.ConsultaDocumentoTrackingInteraccionesMasivo request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://confirma.com.ar/gd/2012/05/WSConsultaDocumentoTrackingInteraccionesFechasS" +
        "chema")]
    public partial class ConsultaDocumentoTrackingInteraccionesFechas : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string empresaPresentanteField;
        
        private string fechaDesdeField;
        
        private string fechaHastaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string EmpresaPresentante {
            get {
                return this.empresaPresentanteField;
            }
            set {
                this.empresaPresentanteField = value;
                this.RaisePropertyChanged("EmpresaPresentante");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FechaDesde {
            get {
                return this.fechaDesdeField;
            }
            set {
                this.fechaDesdeField = value;
                this.RaisePropertyChanged("FechaDesde");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string FechaHasta {
            get {
                return this.fechaHastaField;
            }
            set {
                this.fechaHastaField = value;
                this.RaisePropertyChanged("FechaHasta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://confirma.com.ar/gd/2012/05/WSCommonSchema")]
    public partial class TCodCaption : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string captionField;
        
        private string codListaField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Caption {
            get {
                return this.captionField;
            }
            set {
                this.captionField = value;
                this.RaisePropertyChanged("Caption");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodLista {
            get {
                return this.codListaField;
            }
            set {
                this.codListaField = value;
                this.RaisePropertyChanged("CodLista");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://confirma.com.ar/gd/2012/05/WSConsultaDocumentoResponseSchema")]
    public partial class Empresa : object, System.ComponentModel.INotifyPropertyChanged {
        
        private TCodCaption cUITField;
        
        private string razonSocialField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public TCodCaption CUIT {
            get {
                return this.cUITField;
            }
            set {
                this.cUITField = value;
                this.RaisePropertyChanged("CUIT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string RazonSocial {
            get {
                return this.razonSocialField;
            }
            set {
                this.razonSocialField = value;
                this.RaisePropertyChanged("RazonSocial");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://confirma.com.ar/gd/2012/05/WSConsultaDocumentoResponseSchema")]
    public partial class consultaDocumentosResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private consultaEstadoWS consultaEstadoField;
        
        private string consultaEstadoErrorField;
        
        private consultaDocumentosResponseConsultaDocumentoResponse[] consultaDocumentoResponseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public consultaEstadoWS consultaEstado {
            get {
                return this.consultaEstadoField;
            }
            set {
                this.consultaEstadoField = value;
                this.RaisePropertyChanged("consultaEstado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string consultaEstadoError {
            get {
                return this.consultaEstadoErrorField;
            }
            set {
                this.consultaEstadoErrorField = value;
                this.RaisePropertyChanged("consultaEstadoError");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("consultaDocumentoResponse", Order=2)]
        public consultaDocumentosResponseConsultaDocumentoResponse[] consultaDocumentoResponse {
            get {
                return this.consultaDocumentoResponseField;
            }
            set {
                this.consultaDocumentoResponseField = value;
                this.RaisePropertyChanged("consultaDocumentoResponse");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://confirma.com.ar/gd/2012/05/WSConsultaDocumentoResponseSchema")]
    public enum consultaEstadoWS {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://confirma.com.ar/gd/2012/05/WSConsultaDocumentoResponseSchema")]
    public partial class consultaDocumentosResponseConsultaDocumentoResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idDocumentoField;
        
        private string idBolsaField;
        
        private consultaEstadoDocumento consultaEstadoDocumentoField;
        
        private int estadoDocumentoField;
        
        private Empresa enPoderDeField;
        
        private consultaDocumentosResponseConsultaDocumentoResponseTracking[] accionesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string IdDocumento {
            get {
                return this.idDocumentoField;
            }
            set {
                this.idDocumentoField = value;
                this.RaisePropertyChanged("IdDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string IdBolsa {
            get {
                return this.idBolsaField;
            }
            set {
                this.idBolsaField = value;
                this.RaisePropertyChanged("IdBolsa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public consultaEstadoDocumento consultaEstadoDocumento {
            get {
                return this.consultaEstadoDocumentoField;
            }
            set {
                this.consultaEstadoDocumentoField = value;
                this.RaisePropertyChanged("consultaEstadoDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int EstadoDocumento {
            get {
                return this.estadoDocumentoField;
            }
            set {
                this.estadoDocumentoField = value;
                this.RaisePropertyChanged("EstadoDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public Empresa EnPoderDe {
            get {
                return this.enPoderDeField;
            }
            set {
                this.enPoderDeField = value;
                this.RaisePropertyChanged("EnPoderDe");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Tracking", IsNullable=false)]
        public consultaDocumentosResponseConsultaDocumentoResponseTracking[] Acciones {
            get {
                return this.accionesField;
            }
            set {
                this.accionesField = value;
                this.RaisePropertyChanged("Acciones");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://confirma.com.ar/gd/2012/05/WSConsultaDocumentoResponseSchema")]
    public enum consultaEstadoDocumento {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://confirma.com.ar/gd/2012/05/WSConsultaDocumentoResponseSchema")]
    public partial class consultaDocumentosResponseConsultaDocumentoResponseTracking : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fechaHoraField;
        
        private consultaDocumentosResponseConsultaDocumentoResponseTrackingAccion accionField;
        
        private consultaDocumentosResponseConsultaDocumentoResponseTrackingResultado resultadoField;
        
        private Empresa empresaField;
        
        private consultaDocumentosResponseConsultaDocumentoResponseTrackingUsuario usuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FechaHora {
            get {
                return this.fechaHoraField;
            }
            set {
                this.fechaHoraField = value;
                this.RaisePropertyChanged("FechaHora");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public consultaDocumentosResponseConsultaDocumentoResponseTrackingAccion Accion {
            get {
                return this.accionField;
            }
            set {
                this.accionField = value;
                this.RaisePropertyChanged("Accion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public consultaDocumentosResponseConsultaDocumentoResponseTrackingResultado Resultado {
            get {
                return this.resultadoField;
            }
            set {
                this.resultadoField = value;
                this.RaisePropertyChanged("Resultado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public Empresa Empresa {
            get {
                return this.empresaField;
            }
            set {
                this.empresaField = value;
                this.RaisePropertyChanged("Empresa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public consultaDocumentosResponseConsultaDocumentoResponseTrackingUsuario Usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("Usuario");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://confirma.com.ar/gd/2012/05/WSConsultaDocumentoResponseSchema")]
    public partial class consultaDocumentosResponseConsultaDocumentoResponseTrackingAccion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private codigoAccion codigoField;
        
        private bool codigoFieldSpecified;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public codigoAccion codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoSpecified {
            get {
                return this.codigoFieldSpecified;
            }
            set {
                this.codigoFieldSpecified = value;
                this.RaisePropertyChanged("codigoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://confirma.com.ar/gd/2012/05/WSConsultaDocumentoResponseSchema")]
    public enum codigoAccion {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("9")]
        Item9,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("11")]
        Item11,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://confirma.com.ar/gd/2012/05/WSConsultaDocumentoResponseSchema")]
    public partial class consultaDocumentosResponseConsultaDocumentoResponseTrackingResultado : object, System.ComponentModel.INotifyPropertyChanged {
        
        private codigoResultado codigoField;
        
        private bool codigoFieldSpecified;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public codigoResultado codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoSpecified {
            get {
                return this.codigoFieldSpecified;
            }
            set {
                this.codigoFieldSpecified = value;
                this.RaisePropertyChanged("codigoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://confirma.com.ar/gd/2012/05/WSConsultaDocumentoResponseSchema")]
    public enum codigoResultado {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("18")]
        Item18,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("8")]
        Item8,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("11")]
        Item11,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("27")]
        Item27,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("23")]
        Item23,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("33")]
        Item33,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://confirma.com.ar/gd/2012/05/WSConsultaDocumentoResponseSchema")]
    public partial class consultaDocumentosResponseConsultaDocumentoResponseTrackingUsuario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tipoDocumentoField;
        
        private string nroDocumentoField;
        
        private string apellidoField;
        
        private string nombreField;
        
        private string cargoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TipoDocumento {
            get {
                return this.tipoDocumentoField;
            }
            set {
                this.tipoDocumentoField = value;
                this.RaisePropertyChanged("TipoDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string NroDocumento {
            get {
                return this.nroDocumentoField;
            }
            set {
                this.nroDocumentoField = value;
                this.RaisePropertyChanged("NroDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Apellido {
            get {
                return this.apellidoField;
            }
            set {
                this.apellidoField = value;
                this.RaisePropertyChanged("Apellido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Cargo {
            get {
                return this.cargoField;
            }
            set {
                this.cargoField = value;
                this.RaisePropertyChanged("Cargo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaDocumentoTrackingInteraccionesMasivo {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://confirma.com.ar/gd/2012/05/consultadocumentotrackinginteraccionesfechas", Order=0)]
        public Molinos.DataAgro.Agent.ConfirmaQAConsultaTrackingInteraccionesFecha.ConsultaDocumentoTrackingInteraccionesFechas ConsultaDocumentoTrackingInteraccionesFechas;
        
        public ConsultaDocumentoTrackingInteraccionesMasivo() {
        }
        
        public ConsultaDocumentoTrackingInteraccionesMasivo(Molinos.DataAgro.Agent.ConfirmaQAConsultaTrackingInteraccionesFecha.ConsultaDocumentoTrackingInteraccionesFechas ConsultaDocumentoTrackingInteraccionesFechas) {
            this.ConsultaDocumentoTrackingInteraccionesFechas = ConsultaDocumentoTrackingInteraccionesFechas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaDocumentoTrackingInteraccionesMasivoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://confirma.com.ar/gd/2012/05/consultadocumentotrackinginteraccionesfechas", Order=0)]
        public Molinos.DataAgro.Agent.ConfirmaQAConsultaTrackingInteraccionesFecha.consultaDocumentosResponse ConsultaDocumentosResponse;
        
        public ConsultaDocumentoTrackingInteraccionesMasivoResponse() {
        }
        
        public ConsultaDocumentoTrackingInteraccionesMasivoResponse(Molinos.DataAgro.Agent.ConfirmaQAConsultaTrackingInteraccionesFecha.consultaDocumentosResponse ConsultaDocumentosResponse) {
            this.ConsultaDocumentosResponse = ConsultaDocumentosResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConsultaDocumentoTrackingInteraccionesFechasServiceChannel : Molinos.DataAgro.Agent.ConfirmaQAConsultaTrackingInteraccionesFecha.IConsultaDocumentoTrackingInteraccionesFechasService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsultaDocumentoTrackingInteraccionesFechasServiceClient : System.ServiceModel.ClientBase<Molinos.DataAgro.Agent.ConfirmaQAConsultaTrackingInteraccionesFecha.IConsultaDocumentoTrackingInteraccionesFechasService>, Molinos.DataAgro.Agent.ConfirmaQAConsultaTrackingInteraccionesFecha.IConsultaDocumentoTrackingInteraccionesFechasService {
        
        public ConsultaDocumentoTrackingInteraccionesFechasServiceClient() {
        }
        
        public ConsultaDocumentoTrackingInteraccionesFechasServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConsultaDocumentoTrackingInteraccionesFechasServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultaDocumentoTrackingInteraccionesFechasServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultaDocumentoTrackingInteraccionesFechasServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Molinos.DataAgro.Agent.ConfirmaQAConsultaTrackingInteraccionesFecha.ConsultaDocumentoTrackingInteraccionesMasivoResponse Molinos.DataAgro.Agent.ConfirmaQAConsultaTrackingInteraccionesFecha.IConsultaDocumentoTrackingInteraccionesFechasService.ConsultaDocumentoTrackingInteracciones(Molinos.DataAgro.Agent.ConfirmaQAConsultaTrackingInteraccionesFecha.ConsultaDocumentoTrackingInteraccionesMasivo request) {
            return base.Channel.ConsultaDocumentoTrackingInteracciones(request);
        }
        
        public Molinos.DataAgro.Agent.ConfirmaQAConsultaTrackingInteraccionesFecha.consultaDocumentosResponse ConsultaDocumentoTrackingInteracciones(Molinos.DataAgro.Agent.ConfirmaQAConsultaTrackingInteraccionesFecha.ConsultaDocumentoTrackingInteraccionesFechas ConsultaDocumentoTrackingInteraccionesFechas) {
            Molinos.DataAgro.Agent.ConfirmaQAConsultaTrackingInteraccionesFecha.ConsultaDocumentoTrackingInteraccionesMasivo inValue = new Molinos.DataAgro.Agent.ConfirmaQAConsultaTrackingInteraccionesFecha.ConsultaDocumentoTrackingInteraccionesMasivo();
            inValue.ConsultaDocumentoTrackingInteraccionesFechas = ConsultaDocumentoTrackingInteraccionesFechas;
            Molinos.DataAgro.Agent.ConfirmaQAConsultaTrackingInteraccionesFecha.ConsultaDocumentoTrackingInteraccionesMasivoResponse retVal = ((Molinos.DataAgro.Agent.ConfirmaQAConsultaTrackingInteraccionesFecha.IConsultaDocumentoTrackingInteraccionesFechasService)(this)).ConsultaDocumentoTrackingInteracciones(inValue);
            return retVal.ConsultaDocumentosResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Molinos.DataAgro.Agent.ConfirmaQAConsultaTrackingInteraccionesFecha.ConsultaDocumentoTrackingInteraccionesMasivoResponse> Molinos.DataAgro.Agent.ConfirmaQAConsultaTrackingInteraccionesFecha.IConsultaDocumentoTrackingInteraccionesFechasService.ConsultaDocumentoTrackingInteraccionesAsync(Molinos.DataAgro.Agent.ConfirmaQAConsultaTrackingInteraccionesFecha.ConsultaDocumentoTrackingInteraccionesMasivo request) {
            return base.Channel.ConsultaDocumentoTrackingInteraccionesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Molinos.DataAgro.Agent.ConfirmaQAConsultaTrackingInteraccionesFecha.ConsultaDocumentoTrackingInteraccionesMasivoResponse> ConsultaDocumentoTrackingInteraccionesAsync(Molinos.DataAgro.Agent.ConfirmaQAConsultaTrackingInteraccionesFecha.ConsultaDocumentoTrackingInteraccionesFechas ConsultaDocumentoTrackingInteraccionesFechas) {
            Molinos.DataAgro.Agent.ConfirmaQAConsultaTrackingInteraccionesFecha.ConsultaDocumentoTrackingInteraccionesMasivo inValue = new Molinos.DataAgro.Agent.ConfirmaQAConsultaTrackingInteraccionesFecha.ConsultaDocumentoTrackingInteraccionesMasivo();
            inValue.ConsultaDocumentoTrackingInteraccionesFechas = ConsultaDocumentoTrackingInteraccionesFechas;
            return ((Molinos.DataAgro.Agent.ConfirmaQAConsultaTrackingInteraccionesFecha.IConsultaDocumentoTrackingInteraccionesFechasService)(this)).ConsultaDocumentoTrackingInteraccionesAsync(inValue);
        }
    }
}
