//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Molinos.DataAgro.Agent.PrecioPizarra {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="namespace:dataagro", ConfigurationName="PrecioPizarra.SI_ZMPWS_DATAAGRO_PRECIO_PIZARRA")]
    public interface SI_ZMPWS_DATAAGRO_PRECIO_PIZARRA {
        
        // CODEGEN: Generating message contract since the operation SI_ZMPWS_DATAAGRO_PRECIO_PIZARRA is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Molinos.DataAgro.Agent.PrecioPizarra.SI_ZMPWS_DATAAGRO_PRECIO_PIZARRAResponse SI_ZMPWS_DATAAGRO_PRECIO_PIZARRA(Molinos.DataAgro.Agent.PrecioPizarra.SI_ZMPWS_DATAAGRO_PRECIO_PIZARRARequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<Molinos.DataAgro.Agent.PrecioPizarra.SI_ZMPWS_DATAAGRO_PRECIO_PIZARRAResponse> SI_ZMPWS_DATAAGRO_PRECIO_PIZARRAAsync(Molinos.DataAgro.Agent.PrecioPizarra.SI_ZMPWS_DATAAGRO_PRECIO_PIZARRARequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_MPRFC_PRECIO_PIZARRA : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iM_ANULACIONField;
        
        private string iM_FECHA_DESDEField;
        
        private string iM_FECHA_HASTAField;
        
        private string iM_MATNRField;
        
        private string iM_PIZARRAField;
        
        private decimal iM_PRECIOField;
        
        private string iM_UDATEField;
        
        private string iM_UNIMEDField;
        
        private string iM_USUARIOField;
        
        private string iM_UTIMEField;
        
        private string iM_WAERSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string IM_ANULACION {
            get {
                return this.iM_ANULACIONField;
            }
            set {
                this.iM_ANULACIONField = value;
                this.RaisePropertyChanged("IM_ANULACION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string IM_FECHA_DESDE {
            get {
                return this.iM_FECHA_DESDEField;
            }
            set {
                this.iM_FECHA_DESDEField = value;
                this.RaisePropertyChanged("IM_FECHA_DESDE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string IM_FECHA_HASTA {
            get {
                return this.iM_FECHA_HASTAField;
            }
            set {
                this.iM_FECHA_HASTAField = value;
                this.RaisePropertyChanged("IM_FECHA_HASTA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string IM_MATNR {
            get {
                return this.iM_MATNRField;
            }
            set {
                this.iM_MATNRField = value;
                this.RaisePropertyChanged("IM_MATNR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string IM_PIZARRA {
            get {
                return this.iM_PIZARRAField;
            }
            set {
                this.iM_PIZARRAField = value;
                this.RaisePropertyChanged("IM_PIZARRA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal IM_PRECIO {
            get {
                return this.iM_PRECIOField;
            }
            set {
                this.iM_PRECIOField = value;
                this.RaisePropertyChanged("IM_PRECIO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string IM_UDATE {
            get {
                return this.iM_UDATEField;
            }
            set {
                this.iM_UDATEField = value;
                this.RaisePropertyChanged("IM_UDATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string IM_UNIMED {
            get {
                return this.iM_UNIMEDField;
            }
            set {
                this.iM_UNIMEDField = value;
                this.RaisePropertyChanged("IM_UNIMED");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string IM_USUARIO {
            get {
                return this.iM_USUARIOField;
            }
            set {
                this.iM_USUARIOField = value;
                this.RaisePropertyChanged("IM_USUARIO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string IM_UTIME {
            get {
                return this.iM_UTIMEField;
            }
            set {
                this.iM_UTIMEField = value;
                this.RaisePropertyChanged("IM_UTIME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string IM_WAERS {
            get {
                return this.iM_WAERSField;
            }
            set {
                this.iM_WAERSField = value;
                this.RaisePropertyChanged("IM_WAERS");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_MPRFC_PRECIO_PIZARRAResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string eX_MENSAJEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string EX_MENSAJE {
            get {
                return this.eX_MENSAJEField;
            }
            set {
                this.eX_MENSAJEField = value;
                this.RaisePropertyChanged("EX_MENSAJE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_ZMPWS_DATAAGRO_PRECIO_PIZARRARequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public Molinos.DataAgro.Agent.PrecioPizarra.Z_MPRFC_PRECIO_PIZARRA Z_MPRFC_PRECIO_PIZARRA;
        
        public SI_ZMPWS_DATAAGRO_PRECIO_PIZARRARequest() {
        }
        
        public SI_ZMPWS_DATAAGRO_PRECIO_PIZARRARequest(Molinos.DataAgro.Agent.PrecioPizarra.Z_MPRFC_PRECIO_PIZARRA Z_MPRFC_PRECIO_PIZARRA) {
            this.Z_MPRFC_PRECIO_PIZARRA = Z_MPRFC_PRECIO_PIZARRA;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_ZMPWS_DATAAGRO_PRECIO_PIZARRAResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public Molinos.DataAgro.Agent.PrecioPizarra.Z_MPRFC_PRECIO_PIZARRAResponse Z_MPRFC_PRECIO_PIZARRAResponse;
        
        public SI_ZMPWS_DATAAGRO_PRECIO_PIZARRAResponse() {
        }
        
        public SI_ZMPWS_DATAAGRO_PRECIO_PIZARRAResponse(Molinos.DataAgro.Agent.PrecioPizarra.Z_MPRFC_PRECIO_PIZARRAResponse Z_MPRFC_PRECIO_PIZARRAResponse) {
            this.Z_MPRFC_PRECIO_PIZARRAResponse = Z_MPRFC_PRECIO_PIZARRAResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_ZMPWS_DATAAGRO_PRECIO_PIZARRAChannel : Molinos.DataAgro.Agent.PrecioPizarra.SI_ZMPWS_DATAAGRO_PRECIO_PIZARRA, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_ZMPWS_DATAAGRO_PRECIO_PIZARRAClient : System.ServiceModel.ClientBase<Molinos.DataAgro.Agent.PrecioPizarra.SI_ZMPWS_DATAAGRO_PRECIO_PIZARRA>, Molinos.DataAgro.Agent.PrecioPizarra.SI_ZMPWS_DATAAGRO_PRECIO_PIZARRA {
        
        public SI_ZMPWS_DATAAGRO_PRECIO_PIZARRAClient() {
        }
        
        public SI_ZMPWS_DATAAGRO_PRECIO_PIZARRAClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SI_ZMPWS_DATAAGRO_PRECIO_PIZARRAClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_ZMPWS_DATAAGRO_PRECIO_PIZARRAClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_ZMPWS_DATAAGRO_PRECIO_PIZARRAClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Molinos.DataAgro.Agent.PrecioPizarra.SI_ZMPWS_DATAAGRO_PRECIO_PIZARRAResponse Molinos.DataAgro.Agent.PrecioPizarra.SI_ZMPWS_DATAAGRO_PRECIO_PIZARRA.SI_ZMPWS_DATAAGRO_PRECIO_PIZARRA(Molinos.DataAgro.Agent.PrecioPizarra.SI_ZMPWS_DATAAGRO_PRECIO_PIZARRARequest request) {
            return base.Channel.SI_ZMPWS_DATAAGRO_PRECIO_PIZARRA(request);
        }
        
        public Molinos.DataAgro.Agent.PrecioPizarra.Z_MPRFC_PRECIO_PIZARRAResponse SI_ZMPWS_DATAAGRO_PRECIO_PIZARRA(Molinos.DataAgro.Agent.PrecioPizarra.Z_MPRFC_PRECIO_PIZARRA Z_MPRFC_PRECIO_PIZARRA) {
            Molinos.DataAgro.Agent.PrecioPizarra.SI_ZMPWS_DATAAGRO_PRECIO_PIZARRARequest inValue = new Molinos.DataAgro.Agent.PrecioPizarra.SI_ZMPWS_DATAAGRO_PRECIO_PIZARRARequest();
            inValue.Z_MPRFC_PRECIO_PIZARRA = Z_MPRFC_PRECIO_PIZARRA;
            Molinos.DataAgro.Agent.PrecioPizarra.SI_ZMPWS_DATAAGRO_PRECIO_PIZARRAResponse retVal = ((Molinos.DataAgro.Agent.PrecioPizarra.SI_ZMPWS_DATAAGRO_PRECIO_PIZARRA)(this)).SI_ZMPWS_DATAAGRO_PRECIO_PIZARRA(inValue);
            return retVal.Z_MPRFC_PRECIO_PIZARRAResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Molinos.DataAgro.Agent.PrecioPizarra.SI_ZMPWS_DATAAGRO_PRECIO_PIZARRAResponse> Molinos.DataAgro.Agent.PrecioPizarra.SI_ZMPWS_DATAAGRO_PRECIO_PIZARRA.SI_ZMPWS_DATAAGRO_PRECIO_PIZARRAAsync(Molinos.DataAgro.Agent.PrecioPizarra.SI_ZMPWS_DATAAGRO_PRECIO_PIZARRARequest request) {
            return base.Channel.SI_ZMPWS_DATAAGRO_PRECIO_PIZARRAAsync(request);
        }
        
        public System.Threading.Tasks.Task<Molinos.DataAgro.Agent.PrecioPizarra.SI_ZMPWS_DATAAGRO_PRECIO_PIZARRAResponse> SI_ZMPWS_DATAAGRO_PRECIO_PIZARRAAsync(Molinos.DataAgro.Agent.PrecioPizarra.Z_MPRFC_PRECIO_PIZARRA Z_MPRFC_PRECIO_PIZARRA) {
            Molinos.DataAgro.Agent.PrecioPizarra.SI_ZMPWS_DATAAGRO_PRECIO_PIZARRARequest inValue = new Molinos.DataAgro.Agent.PrecioPizarra.SI_ZMPWS_DATAAGRO_PRECIO_PIZARRARequest();
            inValue.Z_MPRFC_PRECIO_PIZARRA = Z_MPRFC_PRECIO_PIZARRA;
            return ((Molinos.DataAgro.Agent.PrecioPizarra.SI_ZMPWS_DATAAGRO_PRECIO_PIZARRA)(this)).SI_ZMPWS_DATAAGRO_PRECIO_PIZARRAAsync(inValue);
        }
    }
}
