//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Molinos.DataAgro.Agent.CapacidadProductiva {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="namespace:dataagro", ConfigurationName="CapacidadProductiva.SI_ZMPWS_DATAAGRO_CAPACIDAD_PRODUCTIVA")]
    public interface SI_ZMPWS_DATAAGRO_CAPACIDAD_PRODUCTIVA {
        
        // CODEGEN: Generating message contract since the operation SI_ZMPWS_DATAAGRO_CAPACIDAD_PRODUCTIVA is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Molinos.DataAgro.Agent.CapacidadProductiva.SI_ZMPWS_DATAAGRO_CAPACIDAD_PRODUCTIVAResponse SI_ZMPWS_DATAAGRO_CAPACIDAD_PRODUCTIVA(Molinos.DataAgro.Agent.CapacidadProductiva.SI_ZMPWS_DATAAGRO_CAPACIDAD_PRODUCTIVARequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<Molinos.DataAgro.Agent.CapacidadProductiva.SI_ZMPWS_DATAAGRO_CAPACIDAD_PRODUCTIVAResponse> SI_ZMPWS_DATAAGRO_CAPACIDAD_PRODUCTIVAAsync(Molinos.DataAgro.Agent.CapacidadProductiva.SI_ZMPWS_DATAAGRO_CAPACIDAD_PRODUCTIVARequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_MPRFC_CAPACIDAD_PRODUCTIVA : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal iM_CANTIDADField;
        
        private string iM_CENTROField;
        
        private string iM_COSECHAField;
        
        private string iM_CUITField;
        
        private string iM_MATERIALField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal IM_CANTIDAD {
            get {
                return this.iM_CANTIDADField;
            }
            set {
                this.iM_CANTIDADField = value;
                this.RaisePropertyChanged("IM_CANTIDAD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string IM_CENTRO {
            get {
                return this.iM_CENTROField;
            }
            set {
                this.iM_CENTROField = value;
                this.RaisePropertyChanged("IM_CENTRO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string IM_COSECHA {
            get {
                return this.iM_COSECHAField;
            }
            set {
                this.iM_COSECHAField = value;
                this.RaisePropertyChanged("IM_COSECHA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string IM_CUIT {
            get {
                return this.iM_CUITField;
            }
            set {
                this.iM_CUITField = value;
                this.RaisePropertyChanged("IM_CUIT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string IM_MATERIAL {
            get {
                return this.iM_MATERIALField;
            }
            set {
                this.iM_MATERIALField = value;
                this.RaisePropertyChanged("IM_MATERIAL");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_MPRFC_CAPACIDAD_PRODUCTIVAResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string eX_MENSAJEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string EX_MENSAJE {
            get {
                return this.eX_MENSAJEField;
            }
            set {
                this.eX_MENSAJEField = value;
                this.RaisePropertyChanged("EX_MENSAJE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_ZMPWS_DATAAGRO_CAPACIDAD_PRODUCTIVARequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public Molinos.DataAgro.Agent.CapacidadProductiva.Z_MPRFC_CAPACIDAD_PRODUCTIVA Z_MPRFC_CAPACIDAD_PRODUCTIVA;
        
        public SI_ZMPWS_DATAAGRO_CAPACIDAD_PRODUCTIVARequest() {
        }
        
        public SI_ZMPWS_DATAAGRO_CAPACIDAD_PRODUCTIVARequest(Molinos.DataAgro.Agent.CapacidadProductiva.Z_MPRFC_CAPACIDAD_PRODUCTIVA Z_MPRFC_CAPACIDAD_PRODUCTIVA) {
            this.Z_MPRFC_CAPACIDAD_PRODUCTIVA = Z_MPRFC_CAPACIDAD_PRODUCTIVA;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_ZMPWS_DATAAGRO_CAPACIDAD_PRODUCTIVAResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public Molinos.DataAgro.Agent.CapacidadProductiva.Z_MPRFC_CAPACIDAD_PRODUCTIVAResponse Z_MPRFC_CAPACIDAD_PRODUCTIVAResponse;
        
        public SI_ZMPWS_DATAAGRO_CAPACIDAD_PRODUCTIVAResponse() {
        }
        
        public SI_ZMPWS_DATAAGRO_CAPACIDAD_PRODUCTIVAResponse(Molinos.DataAgro.Agent.CapacidadProductiva.Z_MPRFC_CAPACIDAD_PRODUCTIVAResponse Z_MPRFC_CAPACIDAD_PRODUCTIVAResponse) {
            this.Z_MPRFC_CAPACIDAD_PRODUCTIVAResponse = Z_MPRFC_CAPACIDAD_PRODUCTIVAResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_ZMPWS_DATAAGRO_CAPACIDAD_PRODUCTIVAChannel : Molinos.DataAgro.Agent.CapacidadProductiva.SI_ZMPWS_DATAAGRO_CAPACIDAD_PRODUCTIVA, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_ZMPWS_DATAAGRO_CAPACIDAD_PRODUCTIVAClient : System.ServiceModel.ClientBase<Molinos.DataAgro.Agent.CapacidadProductiva.SI_ZMPWS_DATAAGRO_CAPACIDAD_PRODUCTIVA>, Molinos.DataAgro.Agent.CapacidadProductiva.SI_ZMPWS_DATAAGRO_CAPACIDAD_PRODUCTIVA {
        
        public SI_ZMPWS_DATAAGRO_CAPACIDAD_PRODUCTIVAClient() {
        }
        
        public SI_ZMPWS_DATAAGRO_CAPACIDAD_PRODUCTIVAClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SI_ZMPWS_DATAAGRO_CAPACIDAD_PRODUCTIVAClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_ZMPWS_DATAAGRO_CAPACIDAD_PRODUCTIVAClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_ZMPWS_DATAAGRO_CAPACIDAD_PRODUCTIVAClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Molinos.DataAgro.Agent.CapacidadProductiva.SI_ZMPWS_DATAAGRO_CAPACIDAD_PRODUCTIVAResponse Molinos.DataAgro.Agent.CapacidadProductiva.SI_ZMPWS_DATAAGRO_CAPACIDAD_PRODUCTIVA.SI_ZMPWS_DATAAGRO_CAPACIDAD_PRODUCTIVA(Molinos.DataAgro.Agent.CapacidadProductiva.SI_ZMPWS_DATAAGRO_CAPACIDAD_PRODUCTIVARequest request) {
            return base.Channel.SI_ZMPWS_DATAAGRO_CAPACIDAD_PRODUCTIVA(request);
        }
        
        public Molinos.DataAgro.Agent.CapacidadProductiva.Z_MPRFC_CAPACIDAD_PRODUCTIVAResponse SI_ZMPWS_DATAAGRO_CAPACIDAD_PRODUCTIVA(Molinos.DataAgro.Agent.CapacidadProductiva.Z_MPRFC_CAPACIDAD_PRODUCTIVA Z_MPRFC_CAPACIDAD_PRODUCTIVA) {
            Molinos.DataAgro.Agent.CapacidadProductiva.SI_ZMPWS_DATAAGRO_CAPACIDAD_PRODUCTIVARequest inValue = new Molinos.DataAgro.Agent.CapacidadProductiva.SI_ZMPWS_DATAAGRO_CAPACIDAD_PRODUCTIVARequest();
            inValue.Z_MPRFC_CAPACIDAD_PRODUCTIVA = Z_MPRFC_CAPACIDAD_PRODUCTIVA;
            Molinos.DataAgro.Agent.CapacidadProductiva.SI_ZMPWS_DATAAGRO_CAPACIDAD_PRODUCTIVAResponse retVal = ((Molinos.DataAgro.Agent.CapacidadProductiva.SI_ZMPWS_DATAAGRO_CAPACIDAD_PRODUCTIVA)(this)).SI_ZMPWS_DATAAGRO_CAPACIDAD_PRODUCTIVA(inValue);
            return retVal.Z_MPRFC_CAPACIDAD_PRODUCTIVAResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Molinos.DataAgro.Agent.CapacidadProductiva.SI_ZMPWS_DATAAGRO_CAPACIDAD_PRODUCTIVAResponse> Molinos.DataAgro.Agent.CapacidadProductiva.SI_ZMPWS_DATAAGRO_CAPACIDAD_PRODUCTIVA.SI_ZMPWS_DATAAGRO_CAPACIDAD_PRODUCTIVAAsync(Molinos.DataAgro.Agent.CapacidadProductiva.SI_ZMPWS_DATAAGRO_CAPACIDAD_PRODUCTIVARequest request) {
            return base.Channel.SI_ZMPWS_DATAAGRO_CAPACIDAD_PRODUCTIVAAsync(request);
        }
        
        public System.Threading.Tasks.Task<Molinos.DataAgro.Agent.CapacidadProductiva.SI_ZMPWS_DATAAGRO_CAPACIDAD_PRODUCTIVAResponse> SI_ZMPWS_DATAAGRO_CAPACIDAD_PRODUCTIVAAsync(Molinos.DataAgro.Agent.CapacidadProductiva.Z_MPRFC_CAPACIDAD_PRODUCTIVA Z_MPRFC_CAPACIDAD_PRODUCTIVA) {
            Molinos.DataAgro.Agent.CapacidadProductiva.SI_ZMPWS_DATAAGRO_CAPACIDAD_PRODUCTIVARequest inValue = new Molinos.DataAgro.Agent.CapacidadProductiva.SI_ZMPWS_DATAAGRO_CAPACIDAD_PRODUCTIVARequest();
            inValue.Z_MPRFC_CAPACIDAD_PRODUCTIVA = Z_MPRFC_CAPACIDAD_PRODUCTIVA;
            return ((Molinos.DataAgro.Agent.CapacidadProductiva.SI_ZMPWS_DATAAGRO_CAPACIDAD_PRODUCTIVA)(this)).SI_ZMPWS_DATAAGRO_CAPACIDAD_PRODUCTIVAAsync(inValue);
        }
    }
}
