//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Molinos.DataAgro.Agent.ValidarLiquidacionParcial {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="namespace:dataagro", ConfigurationName="ValidarLiquidacionParcial.SI_ZMPWS_DATAAGRO_VALIDAR_LIQ_PARCIAL")]
    public interface SI_ZMPWS_DATAAGRO_VALIDAR_LIQ_PARCIAL {
        
        // CODEGEN: Generating message contract since the operation SI_ZMPWS_DATAAGRO_VALIDAR_LIQ_PARCIAL is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Molinos.DataAgro.Agent.ValidarLiquidacionParcial.SI_ZMPWS_DATAAGRO_VALIDAR_LIQ_PARCIALResponse SI_ZMPWS_DATAAGRO_VALIDAR_LIQ_PARCIAL(Molinos.DataAgro.Agent.ValidarLiquidacionParcial.SI_ZMPWS_DATAAGRO_VALIDAR_LIQ_PARCIALRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<Molinos.DataAgro.Agent.ValidarLiquidacionParcial.SI_ZMPWS_DATAAGRO_VALIDAR_LIQ_PARCIALResponse> SI_ZMPWS_DATAAGRO_VALIDAR_LIQ_PARCIALAsync(Molinos.DataAgro.Agent.ValidarLiquidacionParcial.SI_ZMPWS_DATAAGRO_VALIDAR_LIQ_PARCIALRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_MPRFC_VALIDAR_LIQ_PARCIAL : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iM_CONTRATOField;
        
        private string iM_PEDIDOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string IM_CONTRATO {
            get {
                return this.iM_CONTRATOField;
            }
            set {
                this.iM_CONTRATOField = value;
                this.RaisePropertyChanged("IM_CONTRATO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string IM_PEDIDO {
            get {
                return this.iM_PEDIDOField;
            }
            set {
                this.iM_PEDIDOField = value;
                this.RaisePropertyChanged("IM_PEDIDO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_MPRFC_VALIDAR_LIQ_PARCIALResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string eX_MENSAJEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string EX_MENSAJE {
            get {
                return this.eX_MENSAJEField;
            }
            set {
                this.eX_MENSAJEField = value;
                this.RaisePropertyChanged("EX_MENSAJE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_ZMPWS_DATAAGRO_VALIDAR_LIQ_PARCIALRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public Molinos.DataAgro.Agent.ValidarLiquidacionParcial.Z_MPRFC_VALIDAR_LIQ_PARCIAL Z_MPRFC_VALIDAR_LIQ_PARCIAL;
        
        public SI_ZMPWS_DATAAGRO_VALIDAR_LIQ_PARCIALRequest() {
        }
        
        public SI_ZMPWS_DATAAGRO_VALIDAR_LIQ_PARCIALRequest(Molinos.DataAgro.Agent.ValidarLiquidacionParcial.Z_MPRFC_VALIDAR_LIQ_PARCIAL Z_MPRFC_VALIDAR_LIQ_PARCIAL) {
            this.Z_MPRFC_VALIDAR_LIQ_PARCIAL = Z_MPRFC_VALIDAR_LIQ_PARCIAL;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_ZMPWS_DATAAGRO_VALIDAR_LIQ_PARCIALResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public Molinos.DataAgro.Agent.ValidarLiquidacionParcial.Z_MPRFC_VALIDAR_LIQ_PARCIALResponse Z_MPRFC_VALIDAR_LIQ_PARCIALResponse;
        
        public SI_ZMPWS_DATAAGRO_VALIDAR_LIQ_PARCIALResponse() {
        }
        
        public SI_ZMPWS_DATAAGRO_VALIDAR_LIQ_PARCIALResponse(Molinos.DataAgro.Agent.ValidarLiquidacionParcial.Z_MPRFC_VALIDAR_LIQ_PARCIALResponse Z_MPRFC_VALIDAR_LIQ_PARCIALResponse) {
            this.Z_MPRFC_VALIDAR_LIQ_PARCIALResponse = Z_MPRFC_VALIDAR_LIQ_PARCIALResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_ZMPWS_DATAAGRO_VALIDAR_LIQ_PARCIALChannel : Molinos.DataAgro.Agent.ValidarLiquidacionParcial.SI_ZMPWS_DATAAGRO_VALIDAR_LIQ_PARCIAL, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_ZMPWS_DATAAGRO_VALIDAR_LIQ_PARCIALClient : System.ServiceModel.ClientBase<Molinos.DataAgro.Agent.ValidarLiquidacionParcial.SI_ZMPWS_DATAAGRO_VALIDAR_LIQ_PARCIAL>, Molinos.DataAgro.Agent.ValidarLiquidacionParcial.SI_ZMPWS_DATAAGRO_VALIDAR_LIQ_PARCIAL {
        
        public SI_ZMPWS_DATAAGRO_VALIDAR_LIQ_PARCIALClient() {
        }
        
        public SI_ZMPWS_DATAAGRO_VALIDAR_LIQ_PARCIALClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SI_ZMPWS_DATAAGRO_VALIDAR_LIQ_PARCIALClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_ZMPWS_DATAAGRO_VALIDAR_LIQ_PARCIALClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_ZMPWS_DATAAGRO_VALIDAR_LIQ_PARCIALClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Molinos.DataAgro.Agent.ValidarLiquidacionParcial.SI_ZMPWS_DATAAGRO_VALIDAR_LIQ_PARCIALResponse Molinos.DataAgro.Agent.ValidarLiquidacionParcial.SI_ZMPWS_DATAAGRO_VALIDAR_LIQ_PARCIAL.SI_ZMPWS_DATAAGRO_VALIDAR_LIQ_PARCIAL(Molinos.DataAgro.Agent.ValidarLiquidacionParcial.SI_ZMPWS_DATAAGRO_VALIDAR_LIQ_PARCIALRequest request) {
            return base.Channel.SI_ZMPWS_DATAAGRO_VALIDAR_LIQ_PARCIAL(request);
        }
        
        public Molinos.DataAgro.Agent.ValidarLiquidacionParcial.Z_MPRFC_VALIDAR_LIQ_PARCIALResponse SI_ZMPWS_DATAAGRO_VALIDAR_LIQ_PARCIAL(Molinos.DataAgro.Agent.ValidarLiquidacionParcial.Z_MPRFC_VALIDAR_LIQ_PARCIAL Z_MPRFC_VALIDAR_LIQ_PARCIAL) {
            Molinos.DataAgro.Agent.ValidarLiquidacionParcial.SI_ZMPWS_DATAAGRO_VALIDAR_LIQ_PARCIALRequest inValue = new Molinos.DataAgro.Agent.ValidarLiquidacionParcial.SI_ZMPWS_DATAAGRO_VALIDAR_LIQ_PARCIALRequest();
            inValue.Z_MPRFC_VALIDAR_LIQ_PARCIAL = Z_MPRFC_VALIDAR_LIQ_PARCIAL;
            Molinos.DataAgro.Agent.ValidarLiquidacionParcial.SI_ZMPWS_DATAAGRO_VALIDAR_LIQ_PARCIALResponse retVal = ((Molinos.DataAgro.Agent.ValidarLiquidacionParcial.SI_ZMPWS_DATAAGRO_VALIDAR_LIQ_PARCIAL)(this)).SI_ZMPWS_DATAAGRO_VALIDAR_LIQ_PARCIAL(inValue);
            return retVal.Z_MPRFC_VALIDAR_LIQ_PARCIALResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Molinos.DataAgro.Agent.ValidarLiquidacionParcial.SI_ZMPWS_DATAAGRO_VALIDAR_LIQ_PARCIALResponse> Molinos.DataAgro.Agent.ValidarLiquidacionParcial.SI_ZMPWS_DATAAGRO_VALIDAR_LIQ_PARCIAL.SI_ZMPWS_DATAAGRO_VALIDAR_LIQ_PARCIALAsync(Molinos.DataAgro.Agent.ValidarLiquidacionParcial.SI_ZMPWS_DATAAGRO_VALIDAR_LIQ_PARCIALRequest request) {
            return base.Channel.SI_ZMPWS_DATAAGRO_VALIDAR_LIQ_PARCIALAsync(request);
        }
        
        public System.Threading.Tasks.Task<Molinos.DataAgro.Agent.ValidarLiquidacionParcial.SI_ZMPWS_DATAAGRO_VALIDAR_LIQ_PARCIALResponse> SI_ZMPWS_DATAAGRO_VALIDAR_LIQ_PARCIALAsync(Molinos.DataAgro.Agent.ValidarLiquidacionParcial.Z_MPRFC_VALIDAR_LIQ_PARCIAL Z_MPRFC_VALIDAR_LIQ_PARCIAL) {
            Molinos.DataAgro.Agent.ValidarLiquidacionParcial.SI_ZMPWS_DATAAGRO_VALIDAR_LIQ_PARCIALRequest inValue = new Molinos.DataAgro.Agent.ValidarLiquidacionParcial.SI_ZMPWS_DATAAGRO_VALIDAR_LIQ_PARCIALRequest();
            inValue.Z_MPRFC_VALIDAR_LIQ_PARCIAL = Z_MPRFC_VALIDAR_LIQ_PARCIAL;
            return ((Molinos.DataAgro.Agent.ValidarLiquidacionParcial.SI_ZMPWS_DATAAGRO_VALIDAR_LIQ_PARCIAL)(this)).SI_ZMPWS_DATAAGRO_VALIDAR_LIQ_PARCIALAsync(inValue);
        }
    }
}
