//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Molinos.DataAgro.Agent.ListadoCCPPendiente {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="namespace:dataagro", ConfigurationName="ListadoCCPPendiente.SI_ZMPWS_DATAAGRO_CCPP_PEND_APLICAR")]
    public interface SI_ZMPWS_DATAAGRO_CCPP_PEND_APLICAR {
        
        // CODEGEN: Generating message contract since the operation SI_ZMPWS_DATAAGRO_CCPP_PEND_APLICAR is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Molinos.DataAgro.Agent.ListadoCCPPendiente.SI_ZMPWS_DATAAGRO_CCPP_PEND_APLICARResponse SI_ZMPWS_DATAAGRO_CCPP_PEND_APLICAR(Molinos.DataAgro.Agent.ListadoCCPPendiente.SI_ZMPWS_DATAAGRO_CCPP_PEND_APLICARRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<Molinos.DataAgro.Agent.ListadoCCPPendiente.SI_ZMPWS_DATAAGRO_CCPP_PEND_APLICARResponse> SI_ZMPWS_DATAAGRO_CCPP_PEND_APLICARAsync(Molinos.DataAgro.Agent.ListadoCCPPendiente.SI_ZMPWS_DATAAGRO_CCPP_PEND_APLICARRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_MPRFC_CCPP_PENDIENTE_APLICAR : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iM_AGENTE_COMPRAField;
        
        private string iM_CENTROField;
        
        private string iM_CORREDORField;
        
        private string iM_MATERIALField;
        
        private string iM_PROVEEDORField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string IM_AGENTE_COMPRA {
            get {
                return this.iM_AGENTE_COMPRAField;
            }
            set {
                this.iM_AGENTE_COMPRAField = value;
                this.RaisePropertyChanged("IM_AGENTE_COMPRA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string IM_CENTRO {
            get {
                return this.iM_CENTROField;
            }
            set {
                this.iM_CENTROField = value;
                this.RaisePropertyChanged("IM_CENTRO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string IM_CORREDOR {
            get {
                return this.iM_CORREDORField;
            }
            set {
                this.iM_CORREDORField = value;
                this.RaisePropertyChanged("IM_CORREDOR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string IM_MATERIAL {
            get {
                return this.iM_MATERIALField;
            }
            set {
                this.iM_MATERIALField = value;
                this.RaisePropertyChanged("IM_MATERIAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string IM_PROVEEDOR {
            get {
                return this.iM_PROVEEDORField;
            }
            set {
                this.iM_PROVEEDORField = value;
                this.RaisePropertyChanged("IM_PROVEEDOR");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMPES6410 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string pROVEEDORField;
        
        private string cORREDORField;
        
        private string aGENTE_COMPRAField;
        
        private string cCPPField;
        
        private string mATERIALField;
        
        private string cENTROField;
        
        private decimal cANTIDADField;
        
        private string fECHA_NETOField;
        
        private string fECHA_INGRESOField;
        
        private string cTGField;
        
        private string cUIT_SOLICITANTEField;
        
        private string aLMACENField;
        
        private string cONTRATOField;
        
        private decimal kILOS_CONTField;
        
        private string sUSTENTABLEField;
        
        private string cD_CGField;
        
        private string wARRANTField;
        
        private string cANJEField;
        
        private string rEGIONField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string PROVEEDOR {
            get {
                return this.pROVEEDORField;
            }
            set {
                this.pROVEEDORField = value;
                this.RaisePropertyChanged("PROVEEDOR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string CORREDOR {
            get {
                return this.cORREDORField;
            }
            set {
                this.cORREDORField = value;
                this.RaisePropertyChanged("CORREDOR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string AGENTE_COMPRA {
            get {
                return this.aGENTE_COMPRAField;
            }
            set {
                this.aGENTE_COMPRAField = value;
                this.RaisePropertyChanged("AGENTE_COMPRA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string CCPP {
            get {
                return this.cCPPField;
            }
            set {
                this.cCPPField = value;
                this.RaisePropertyChanged("CCPP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string MATERIAL {
            get {
                return this.mATERIALField;
            }
            set {
                this.mATERIALField = value;
                this.RaisePropertyChanged("MATERIAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string CENTRO {
            get {
                return this.cENTROField;
            }
            set {
                this.cENTROField = value;
                this.RaisePropertyChanged("CENTRO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public decimal CANTIDAD {
            get {
                return this.cANTIDADField;
            }
            set {
                this.cANTIDADField = value;
                this.RaisePropertyChanged("CANTIDAD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string FECHA_NETO {
            get {
                return this.fECHA_NETOField;
            }
            set {
                this.fECHA_NETOField = value;
                this.RaisePropertyChanged("FECHA_NETO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string FECHA_INGRESO {
            get {
                return this.fECHA_INGRESOField;
            }
            set {
                this.fECHA_INGRESOField = value;
                this.RaisePropertyChanged("FECHA_INGRESO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string CTG {
            get {
                return this.cTGField;
            }
            set {
                this.cTGField = value;
                this.RaisePropertyChanged("CTG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string CUIT_SOLICITANTE {
            get {
                return this.cUIT_SOLICITANTEField;
            }
            set {
                this.cUIT_SOLICITANTEField = value;
                this.RaisePropertyChanged("CUIT_SOLICITANTE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string ALMACEN {
            get {
                return this.aLMACENField;
            }
            set {
                this.aLMACENField = value;
                this.RaisePropertyChanged("ALMACEN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string CONTRATO {
            get {
                return this.cONTRATOField;
            }
            set {
                this.cONTRATOField = value;
                this.RaisePropertyChanged("CONTRATO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public decimal KILOS_CONT {
            get {
                return this.kILOS_CONTField;
            }
            set {
                this.kILOS_CONTField = value;
                this.RaisePropertyChanged("KILOS_CONT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string SUSTENTABLE {
            get {
                return this.sUSTENTABLEField;
            }
            set {
                this.sUSTENTABLEField = value;
                this.RaisePropertyChanged("SUSTENTABLE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string CD_CG {
            get {
                return this.cD_CGField;
            }
            set {
                this.cD_CGField = value;
                this.RaisePropertyChanged("CD_CG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string WARRANT {
            get {
                return this.wARRANTField;
            }
            set {
                this.wARRANTField = value;
                this.RaisePropertyChanged("WARRANT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string CANJE {
            get {
                return this.cANJEField;
            }
            set {
                this.cANJEField = value;
                this.RaisePropertyChanged("CANJE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string REGION {
            get {
                return this.rEGIONField;
            }
            set {
                this.rEGIONField = value;
                this.RaisePropertyChanged("REGION");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_MPRFC_CCPP_PENDIENTE_APLICARResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string eX_MENSAJEField;
        
        private ZMPES6410[] eX_SALIDAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string EX_MENSAJE {
            get {
                return this.eX_MENSAJEField;
            }
            set {
                this.eX_MENSAJEField = value;
                this.RaisePropertyChanged("EX_MENSAJE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZMPES6410[] EX_SALIDA {
            get {
                return this.eX_SALIDAField;
            }
            set {
                this.eX_SALIDAField = value;
                this.RaisePropertyChanged("EX_SALIDA");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_ZMPWS_DATAAGRO_CCPP_PEND_APLICARRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public Molinos.DataAgro.Agent.ListadoCCPPendiente.Z_MPRFC_CCPP_PENDIENTE_APLICAR Z_MPRFC_CCPP_PENDIENTE_APLICAR;
        
        public SI_ZMPWS_DATAAGRO_CCPP_PEND_APLICARRequest() {
        }
        
        public SI_ZMPWS_DATAAGRO_CCPP_PEND_APLICARRequest(Molinos.DataAgro.Agent.ListadoCCPPendiente.Z_MPRFC_CCPP_PENDIENTE_APLICAR Z_MPRFC_CCPP_PENDIENTE_APLICAR) {
            this.Z_MPRFC_CCPP_PENDIENTE_APLICAR = Z_MPRFC_CCPP_PENDIENTE_APLICAR;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_ZMPWS_DATAAGRO_CCPP_PEND_APLICARResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public Molinos.DataAgro.Agent.ListadoCCPPendiente.Z_MPRFC_CCPP_PENDIENTE_APLICARResponse Z_MPRFC_CCPP_PENDIENTE_APLICARResponse;
        
        public SI_ZMPWS_DATAAGRO_CCPP_PEND_APLICARResponse() {
        }
        
        public SI_ZMPWS_DATAAGRO_CCPP_PEND_APLICARResponse(Molinos.DataAgro.Agent.ListadoCCPPendiente.Z_MPRFC_CCPP_PENDIENTE_APLICARResponse Z_MPRFC_CCPP_PENDIENTE_APLICARResponse) {
            this.Z_MPRFC_CCPP_PENDIENTE_APLICARResponse = Z_MPRFC_CCPP_PENDIENTE_APLICARResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_ZMPWS_DATAAGRO_CCPP_PEND_APLICARChannel : Molinos.DataAgro.Agent.ListadoCCPPendiente.SI_ZMPWS_DATAAGRO_CCPP_PEND_APLICAR, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_ZMPWS_DATAAGRO_CCPP_PEND_APLICARClient : System.ServiceModel.ClientBase<Molinos.DataAgro.Agent.ListadoCCPPendiente.SI_ZMPWS_DATAAGRO_CCPP_PEND_APLICAR>, Molinos.DataAgro.Agent.ListadoCCPPendiente.SI_ZMPWS_DATAAGRO_CCPP_PEND_APLICAR {
        
        public SI_ZMPWS_DATAAGRO_CCPP_PEND_APLICARClient() {
        }
        
        public SI_ZMPWS_DATAAGRO_CCPP_PEND_APLICARClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SI_ZMPWS_DATAAGRO_CCPP_PEND_APLICARClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_ZMPWS_DATAAGRO_CCPP_PEND_APLICARClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_ZMPWS_DATAAGRO_CCPP_PEND_APLICARClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Molinos.DataAgro.Agent.ListadoCCPPendiente.SI_ZMPWS_DATAAGRO_CCPP_PEND_APLICARResponse Molinos.DataAgro.Agent.ListadoCCPPendiente.SI_ZMPWS_DATAAGRO_CCPP_PEND_APLICAR.SI_ZMPWS_DATAAGRO_CCPP_PEND_APLICAR(Molinos.DataAgro.Agent.ListadoCCPPendiente.SI_ZMPWS_DATAAGRO_CCPP_PEND_APLICARRequest request) {
            return base.Channel.SI_ZMPWS_DATAAGRO_CCPP_PEND_APLICAR(request);
        }
        
        public Molinos.DataAgro.Agent.ListadoCCPPendiente.Z_MPRFC_CCPP_PENDIENTE_APLICARResponse SI_ZMPWS_DATAAGRO_CCPP_PEND_APLICAR(Molinos.DataAgro.Agent.ListadoCCPPendiente.Z_MPRFC_CCPP_PENDIENTE_APLICAR Z_MPRFC_CCPP_PENDIENTE_APLICAR) {
            Molinos.DataAgro.Agent.ListadoCCPPendiente.SI_ZMPWS_DATAAGRO_CCPP_PEND_APLICARRequest inValue = new Molinos.DataAgro.Agent.ListadoCCPPendiente.SI_ZMPWS_DATAAGRO_CCPP_PEND_APLICARRequest();
            inValue.Z_MPRFC_CCPP_PENDIENTE_APLICAR = Z_MPRFC_CCPP_PENDIENTE_APLICAR;
            Molinos.DataAgro.Agent.ListadoCCPPendiente.SI_ZMPWS_DATAAGRO_CCPP_PEND_APLICARResponse retVal = ((Molinos.DataAgro.Agent.ListadoCCPPendiente.SI_ZMPWS_DATAAGRO_CCPP_PEND_APLICAR)(this)).SI_ZMPWS_DATAAGRO_CCPP_PEND_APLICAR(inValue);
            return retVal.Z_MPRFC_CCPP_PENDIENTE_APLICARResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Molinos.DataAgro.Agent.ListadoCCPPendiente.SI_ZMPWS_DATAAGRO_CCPP_PEND_APLICARResponse> Molinos.DataAgro.Agent.ListadoCCPPendiente.SI_ZMPWS_DATAAGRO_CCPP_PEND_APLICAR.SI_ZMPWS_DATAAGRO_CCPP_PEND_APLICARAsync(Molinos.DataAgro.Agent.ListadoCCPPendiente.SI_ZMPWS_DATAAGRO_CCPP_PEND_APLICARRequest request) {
            return base.Channel.SI_ZMPWS_DATAAGRO_CCPP_PEND_APLICARAsync(request);
        }
        
        public System.Threading.Tasks.Task<Molinos.DataAgro.Agent.ListadoCCPPendiente.SI_ZMPWS_DATAAGRO_CCPP_PEND_APLICARResponse> SI_ZMPWS_DATAAGRO_CCPP_PEND_APLICARAsync(Molinos.DataAgro.Agent.ListadoCCPPendiente.Z_MPRFC_CCPP_PENDIENTE_APLICAR Z_MPRFC_CCPP_PENDIENTE_APLICAR) {
            Molinos.DataAgro.Agent.ListadoCCPPendiente.SI_ZMPWS_DATAAGRO_CCPP_PEND_APLICARRequest inValue = new Molinos.DataAgro.Agent.ListadoCCPPendiente.SI_ZMPWS_DATAAGRO_CCPP_PEND_APLICARRequest();
            inValue.Z_MPRFC_CCPP_PENDIENTE_APLICAR = Z_MPRFC_CCPP_PENDIENTE_APLICAR;
            return ((Molinos.DataAgro.Agent.ListadoCCPPendiente.SI_ZMPWS_DATAAGRO_CCPP_PEND_APLICAR)(this)).SI_ZMPWS_DATAAGRO_CCPP_PEND_APLICARAsync(inValue);
        }
    }
}
