//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Molinos.DataAgro.Agent.ListaCBUProveedor {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="namespace:dataagro", ConfigurationName="ListaCBUProveedor.SI_ZMPWS_DATAAGRO_LISTA_CBU_PROVEEDOR")]
    public interface SI_ZMPWS_DATAAGRO_LISTA_CBU_PROVEEDOR {
        
        // CODEGEN: Generating message contract since the operation SI_ZMPWS_DATAAGRO_LISTA_CBU_PROVEEDOR is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Molinos.DataAgro.Agent.ListaCBUProveedor.SI_ZMPWS_DATAAGRO_LISTA_CBU_PROVEEDORResponse SI_ZMPWS_DATAAGRO_LISTA_CBU_PROVEEDOR(Molinos.DataAgro.Agent.ListaCBUProveedor.SI_ZMPWS_DATAAGRO_LISTA_CBU_PROVEEDORRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<Molinos.DataAgro.Agent.ListaCBUProveedor.SI_ZMPWS_DATAAGRO_LISTA_CBU_PROVEEDORResponse> SI_ZMPWS_DATAAGRO_LISTA_CBU_PROVEEDORAsync(Molinos.DataAgro.Agent.ListaCBUProveedor.SI_ZMPWS_DATAAGRO_LISTA_CBU_PROVEEDORRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_MPRFC_LISTA_CBU_PROVEEDOR : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZMPES6280[] iM_CUITField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZMPES6280[] IM_CUIT {
            get {
                return this.iM_CUITField;
            }
            set {
                this.iM_CUITField = value;
                this.RaisePropertyChanged("IM_CUIT");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMPES6280 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cUITField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CUIT {
            get {
                return this.cUITField;
            }
            set {
                this.cUITField = value;
                this.RaisePropertyChanged("CUIT");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMPES6270 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cUITField;
        
        private string kOINHField;
        
        private string bANKNField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CUIT {
            get {
                return this.cUITField;
            }
            set {
                this.cUITField = value;
                this.RaisePropertyChanged("CUIT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string KOINH {
            get {
                return this.kOINHField;
            }
            set {
                this.kOINHField = value;
                this.RaisePropertyChanged("KOINH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string BANKN {
            get {
                return this.bANKNField;
            }
            set {
                this.bANKNField = value;
                this.RaisePropertyChanged("BANKN");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_MPRFC_LISTA_CBU_PROVEEDORResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZMPES6270[] eX_CBUField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZMPES6270[] EX_CBU {
            get {
                return this.eX_CBUField;
            }
            set {
                this.eX_CBUField = value;
                this.RaisePropertyChanged("EX_CBU");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_ZMPWS_DATAAGRO_LISTA_CBU_PROVEEDORRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public Molinos.DataAgro.Agent.ListaCBUProveedor.Z_MPRFC_LISTA_CBU_PROVEEDOR Z_MPRFC_LISTA_CBU_PROVEEDOR;
        
        public SI_ZMPWS_DATAAGRO_LISTA_CBU_PROVEEDORRequest() {
        }
        
        public SI_ZMPWS_DATAAGRO_LISTA_CBU_PROVEEDORRequest(Molinos.DataAgro.Agent.ListaCBUProveedor.Z_MPRFC_LISTA_CBU_PROVEEDOR Z_MPRFC_LISTA_CBU_PROVEEDOR) {
            this.Z_MPRFC_LISTA_CBU_PROVEEDOR = Z_MPRFC_LISTA_CBU_PROVEEDOR;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_ZMPWS_DATAAGRO_LISTA_CBU_PROVEEDORResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public Molinos.DataAgro.Agent.ListaCBUProveedor.Z_MPRFC_LISTA_CBU_PROVEEDORResponse Z_MPRFC_LISTA_CBU_PROVEEDORResponse;
        
        public SI_ZMPWS_DATAAGRO_LISTA_CBU_PROVEEDORResponse() {
        }
        
        public SI_ZMPWS_DATAAGRO_LISTA_CBU_PROVEEDORResponse(Molinos.DataAgro.Agent.ListaCBUProveedor.Z_MPRFC_LISTA_CBU_PROVEEDORResponse Z_MPRFC_LISTA_CBU_PROVEEDORResponse) {
            this.Z_MPRFC_LISTA_CBU_PROVEEDORResponse = Z_MPRFC_LISTA_CBU_PROVEEDORResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_ZMPWS_DATAAGRO_LISTA_CBU_PROVEEDORChannel : Molinos.DataAgro.Agent.ListaCBUProveedor.SI_ZMPWS_DATAAGRO_LISTA_CBU_PROVEEDOR, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_ZMPWS_DATAAGRO_LISTA_CBU_PROVEEDORClient : System.ServiceModel.ClientBase<Molinos.DataAgro.Agent.ListaCBUProveedor.SI_ZMPWS_DATAAGRO_LISTA_CBU_PROVEEDOR>, Molinos.DataAgro.Agent.ListaCBUProveedor.SI_ZMPWS_DATAAGRO_LISTA_CBU_PROVEEDOR {
        
        public SI_ZMPWS_DATAAGRO_LISTA_CBU_PROVEEDORClient() {
        }
        
        public SI_ZMPWS_DATAAGRO_LISTA_CBU_PROVEEDORClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SI_ZMPWS_DATAAGRO_LISTA_CBU_PROVEEDORClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_ZMPWS_DATAAGRO_LISTA_CBU_PROVEEDORClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_ZMPWS_DATAAGRO_LISTA_CBU_PROVEEDORClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Molinos.DataAgro.Agent.ListaCBUProveedor.SI_ZMPWS_DATAAGRO_LISTA_CBU_PROVEEDORResponse Molinos.DataAgro.Agent.ListaCBUProveedor.SI_ZMPWS_DATAAGRO_LISTA_CBU_PROVEEDOR.SI_ZMPWS_DATAAGRO_LISTA_CBU_PROVEEDOR(Molinos.DataAgro.Agent.ListaCBUProveedor.SI_ZMPWS_DATAAGRO_LISTA_CBU_PROVEEDORRequest request) {
            return base.Channel.SI_ZMPWS_DATAAGRO_LISTA_CBU_PROVEEDOR(request);
        }
        
        public Molinos.DataAgro.Agent.ListaCBUProveedor.Z_MPRFC_LISTA_CBU_PROVEEDORResponse SI_ZMPWS_DATAAGRO_LISTA_CBU_PROVEEDOR(Molinos.DataAgro.Agent.ListaCBUProveedor.Z_MPRFC_LISTA_CBU_PROVEEDOR Z_MPRFC_LISTA_CBU_PROVEEDOR) {
            Molinos.DataAgro.Agent.ListaCBUProveedor.SI_ZMPWS_DATAAGRO_LISTA_CBU_PROVEEDORRequest inValue = new Molinos.DataAgro.Agent.ListaCBUProveedor.SI_ZMPWS_DATAAGRO_LISTA_CBU_PROVEEDORRequest();
            inValue.Z_MPRFC_LISTA_CBU_PROVEEDOR = Z_MPRFC_LISTA_CBU_PROVEEDOR;
            Molinos.DataAgro.Agent.ListaCBUProveedor.SI_ZMPWS_DATAAGRO_LISTA_CBU_PROVEEDORResponse retVal = ((Molinos.DataAgro.Agent.ListaCBUProveedor.SI_ZMPWS_DATAAGRO_LISTA_CBU_PROVEEDOR)(this)).SI_ZMPWS_DATAAGRO_LISTA_CBU_PROVEEDOR(inValue);
            return retVal.Z_MPRFC_LISTA_CBU_PROVEEDORResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Molinos.DataAgro.Agent.ListaCBUProveedor.SI_ZMPWS_DATAAGRO_LISTA_CBU_PROVEEDORResponse> Molinos.DataAgro.Agent.ListaCBUProveedor.SI_ZMPWS_DATAAGRO_LISTA_CBU_PROVEEDOR.SI_ZMPWS_DATAAGRO_LISTA_CBU_PROVEEDORAsync(Molinos.DataAgro.Agent.ListaCBUProveedor.SI_ZMPWS_DATAAGRO_LISTA_CBU_PROVEEDORRequest request) {
            return base.Channel.SI_ZMPWS_DATAAGRO_LISTA_CBU_PROVEEDORAsync(request);
        }
        
        public System.Threading.Tasks.Task<Molinos.DataAgro.Agent.ListaCBUProveedor.SI_ZMPWS_DATAAGRO_LISTA_CBU_PROVEEDORResponse> SI_ZMPWS_DATAAGRO_LISTA_CBU_PROVEEDORAsync(Molinos.DataAgro.Agent.ListaCBUProveedor.Z_MPRFC_LISTA_CBU_PROVEEDOR Z_MPRFC_LISTA_CBU_PROVEEDOR) {
            Molinos.DataAgro.Agent.ListaCBUProveedor.SI_ZMPWS_DATAAGRO_LISTA_CBU_PROVEEDORRequest inValue = new Molinos.DataAgro.Agent.ListaCBUProveedor.SI_ZMPWS_DATAAGRO_LISTA_CBU_PROVEEDORRequest();
            inValue.Z_MPRFC_LISTA_CBU_PROVEEDOR = Z_MPRFC_LISTA_CBU_PROVEEDOR;
            return ((Molinos.DataAgro.Agent.ListaCBUProveedor.SI_ZMPWS_DATAAGRO_LISTA_CBU_PROVEEDOR)(this)).SI_ZMPWS_DATAAGRO_LISTA_CBU_PROVEEDORAsync(inValue);
        }
    }
}
