//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Molinos.DataAgro.Agent.VisualizarCapacidadProductiva {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="namespace:dataagro", ConfigurationName="VisualizarCapacidadProductiva.SI_ZMPWS_DATAAGRO_VISU_CAP_PRODUCTIVA")]
    public interface SI_ZMPWS_DATAAGRO_VISU_CAP_PRODUCTIVA {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación SI_ZMPWS_DATAAGRO_VISU_CAP_PRODUCTIVA no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Molinos.DataAgro.Agent.VisualizarCapacidadProductiva.SI_ZMPWS_DATAAGRO_VISU_CAP_PRODUCTIVAResponse SI_ZMPWS_DATAAGRO_VISU_CAP_PRODUCTIVA(Molinos.DataAgro.Agent.VisualizarCapacidadProductiva.SI_ZMPWS_DATAAGRO_VISU_CAP_PRODUCTIVARequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<Molinos.DataAgro.Agent.VisualizarCapacidadProductiva.SI_ZMPWS_DATAAGRO_VISU_CAP_PRODUCTIVAResponse> SI_ZMPWS_DATAAGRO_VISU_CAP_PRODUCTIVAAsync(Molinos.DataAgro.Agent.VisualizarCapacidadProductiva.SI_ZMPWS_DATAAGRO_VISU_CAP_PRODUCTIVARequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_MPRFC_VISU_CAP_PRODUCTIVA : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iM_CUITField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string IM_CUIT {
            get {
                return this.iM_CUITField;
            }
            set {
                this.iM_CUITField = value;
                this.RaisePropertyChanged("IM_CUIT");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMPES6950 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string lIFNRField;
        
        private string mATNRField;
        
        private string cOSECHAField;
        
        private decimal cANTIDADField;
        
        private string uNIMEField;
        
        private decimal pORCField;
        
        private string fECHA_ACTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string LIFNR {
            get {
                return this.lIFNRField;
            }
            set {
                this.lIFNRField = value;
                this.RaisePropertyChanged("LIFNR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string MATNR {
            get {
                return this.mATNRField;
            }
            set {
                this.mATNRField = value;
                this.RaisePropertyChanged("MATNR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string COSECHA {
            get {
                return this.cOSECHAField;
            }
            set {
                this.cOSECHAField = value;
                this.RaisePropertyChanged("COSECHA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal CANTIDAD {
            get {
                return this.cANTIDADField;
            }
            set {
                this.cANTIDADField = value;
                this.RaisePropertyChanged("CANTIDAD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string UNIME {
            get {
                return this.uNIMEField;
            }
            set {
                this.uNIMEField = value;
                this.RaisePropertyChanged("UNIME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal PORC {
            get {
                return this.pORCField;
            }
            set {
                this.pORCField = value;
                this.RaisePropertyChanged("PORC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string FECHA_ACT {
            get {
                return this.fECHA_ACTField;
            }
            set {
                this.fECHA_ACTField = value;
                this.RaisePropertyChanged("FECHA_ACT");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_MPRFC_VISU_CAP_PRODUCTIVAResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZMPES6950[] eX_SALIDAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZMPES6950[] EX_SALIDA {
            get {
                return this.eX_SALIDAField;
            }
            set {
                this.eX_SALIDAField = value;
                this.RaisePropertyChanged("EX_SALIDA");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_ZMPWS_DATAAGRO_VISU_CAP_PRODUCTIVARequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public Molinos.DataAgro.Agent.VisualizarCapacidadProductiva.Z_MPRFC_VISU_CAP_PRODUCTIVA Z_MPRFC_VISU_CAP_PRODUCTIVA;
        
        public SI_ZMPWS_DATAAGRO_VISU_CAP_PRODUCTIVARequest() {
        }
        
        public SI_ZMPWS_DATAAGRO_VISU_CAP_PRODUCTIVARequest(Molinos.DataAgro.Agent.VisualizarCapacidadProductiva.Z_MPRFC_VISU_CAP_PRODUCTIVA Z_MPRFC_VISU_CAP_PRODUCTIVA) {
            this.Z_MPRFC_VISU_CAP_PRODUCTIVA = Z_MPRFC_VISU_CAP_PRODUCTIVA;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_ZMPWS_DATAAGRO_VISU_CAP_PRODUCTIVAResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public Molinos.DataAgro.Agent.VisualizarCapacidadProductiva.Z_MPRFC_VISU_CAP_PRODUCTIVAResponse Z_MPRFC_VISU_CAP_PRODUCTIVAResponse;
        
        public SI_ZMPWS_DATAAGRO_VISU_CAP_PRODUCTIVAResponse() {
        }
        
        public SI_ZMPWS_DATAAGRO_VISU_CAP_PRODUCTIVAResponse(Molinos.DataAgro.Agent.VisualizarCapacidadProductiva.Z_MPRFC_VISU_CAP_PRODUCTIVAResponse Z_MPRFC_VISU_CAP_PRODUCTIVAResponse) {
            this.Z_MPRFC_VISU_CAP_PRODUCTIVAResponse = Z_MPRFC_VISU_CAP_PRODUCTIVAResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_ZMPWS_DATAAGRO_VISU_CAP_PRODUCTIVAChannel : Molinos.DataAgro.Agent.VisualizarCapacidadProductiva.SI_ZMPWS_DATAAGRO_VISU_CAP_PRODUCTIVA, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_ZMPWS_DATAAGRO_VISU_CAP_PRODUCTIVAClient : System.ServiceModel.ClientBase<Molinos.DataAgro.Agent.VisualizarCapacidadProductiva.SI_ZMPWS_DATAAGRO_VISU_CAP_PRODUCTIVA>, Molinos.DataAgro.Agent.VisualizarCapacidadProductiva.SI_ZMPWS_DATAAGRO_VISU_CAP_PRODUCTIVA {
        
        public SI_ZMPWS_DATAAGRO_VISU_CAP_PRODUCTIVAClient() {
        }
        
        public SI_ZMPWS_DATAAGRO_VISU_CAP_PRODUCTIVAClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SI_ZMPWS_DATAAGRO_VISU_CAP_PRODUCTIVAClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_ZMPWS_DATAAGRO_VISU_CAP_PRODUCTIVAClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_ZMPWS_DATAAGRO_VISU_CAP_PRODUCTIVAClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Molinos.DataAgro.Agent.VisualizarCapacidadProductiva.SI_ZMPWS_DATAAGRO_VISU_CAP_PRODUCTIVAResponse Molinos.DataAgro.Agent.VisualizarCapacidadProductiva.SI_ZMPWS_DATAAGRO_VISU_CAP_PRODUCTIVA.SI_ZMPWS_DATAAGRO_VISU_CAP_PRODUCTIVA(Molinos.DataAgro.Agent.VisualizarCapacidadProductiva.SI_ZMPWS_DATAAGRO_VISU_CAP_PRODUCTIVARequest request) {
            return base.Channel.SI_ZMPWS_DATAAGRO_VISU_CAP_PRODUCTIVA(request);
        }
        
        public Molinos.DataAgro.Agent.VisualizarCapacidadProductiva.Z_MPRFC_VISU_CAP_PRODUCTIVAResponse SI_ZMPWS_DATAAGRO_VISU_CAP_PRODUCTIVA(Molinos.DataAgro.Agent.VisualizarCapacidadProductiva.Z_MPRFC_VISU_CAP_PRODUCTIVA Z_MPRFC_VISU_CAP_PRODUCTIVA) {
            Molinos.DataAgro.Agent.VisualizarCapacidadProductiva.SI_ZMPWS_DATAAGRO_VISU_CAP_PRODUCTIVARequest inValue = new Molinos.DataAgro.Agent.VisualizarCapacidadProductiva.SI_ZMPWS_DATAAGRO_VISU_CAP_PRODUCTIVARequest();
            inValue.Z_MPRFC_VISU_CAP_PRODUCTIVA = Z_MPRFC_VISU_CAP_PRODUCTIVA;
            Molinos.DataAgro.Agent.VisualizarCapacidadProductiva.SI_ZMPWS_DATAAGRO_VISU_CAP_PRODUCTIVAResponse retVal = ((Molinos.DataAgro.Agent.VisualizarCapacidadProductiva.SI_ZMPWS_DATAAGRO_VISU_CAP_PRODUCTIVA)(this)).SI_ZMPWS_DATAAGRO_VISU_CAP_PRODUCTIVA(inValue);
            return retVal.Z_MPRFC_VISU_CAP_PRODUCTIVAResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Molinos.DataAgro.Agent.VisualizarCapacidadProductiva.SI_ZMPWS_DATAAGRO_VISU_CAP_PRODUCTIVAResponse> Molinos.DataAgro.Agent.VisualizarCapacidadProductiva.SI_ZMPWS_DATAAGRO_VISU_CAP_PRODUCTIVA.SI_ZMPWS_DATAAGRO_VISU_CAP_PRODUCTIVAAsync(Molinos.DataAgro.Agent.VisualizarCapacidadProductiva.SI_ZMPWS_DATAAGRO_VISU_CAP_PRODUCTIVARequest request) {
            return base.Channel.SI_ZMPWS_DATAAGRO_VISU_CAP_PRODUCTIVAAsync(request);
        }
        
        public System.Threading.Tasks.Task<Molinos.DataAgro.Agent.VisualizarCapacidadProductiva.SI_ZMPWS_DATAAGRO_VISU_CAP_PRODUCTIVAResponse> SI_ZMPWS_DATAAGRO_VISU_CAP_PRODUCTIVAAsync(Molinos.DataAgro.Agent.VisualizarCapacidadProductiva.Z_MPRFC_VISU_CAP_PRODUCTIVA Z_MPRFC_VISU_CAP_PRODUCTIVA) {
            Molinos.DataAgro.Agent.VisualizarCapacidadProductiva.SI_ZMPWS_DATAAGRO_VISU_CAP_PRODUCTIVARequest inValue = new Molinos.DataAgro.Agent.VisualizarCapacidadProductiva.SI_ZMPWS_DATAAGRO_VISU_CAP_PRODUCTIVARequest();
            inValue.Z_MPRFC_VISU_CAP_PRODUCTIVA = Z_MPRFC_VISU_CAP_PRODUCTIVA;
            return ((Molinos.DataAgro.Agent.VisualizarCapacidadProductiva.SI_ZMPWS_DATAAGRO_VISU_CAP_PRODUCTIVA)(this)).SI_ZMPWS_DATAAGRO_VISU_CAP_PRODUCTIVAAsync(inValue);
        }
    }
}
