//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Molinos.DataAgro.Agent.InsertarFijacionesVirtuales {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="namespace:dataagro", ConfigurationName="InsertarFijacionesVirtuales.SI_ZMPWS_DATAAGRO_INSERTAR_FIJ_VIR_CANJE")]
    public interface SI_ZMPWS_DATAAGRO_INSERTAR_FIJ_VIR_CANJE {
        
        // CODEGEN: Generating message contract since the operation SI_ZMPWS_DATAAGRO_INSERTAR_FIJ_VIR_CANJE is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Molinos.DataAgro.Agent.InsertarFijacionesVirtuales.SI_ZMPWS_DATAAGRO_INSERTAR_FIJ_VIR_CANJEResponse SI_ZMPWS_DATAAGRO_INSERTAR_FIJ_VIR_CANJE(Molinos.DataAgro.Agent.InsertarFijacionesVirtuales.SI_ZMPWS_DATAAGRO_INSERTAR_FIJ_VIR_CANJERequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<Molinos.DataAgro.Agent.InsertarFijacionesVirtuales.SI_ZMPWS_DATAAGRO_INSERTAR_FIJ_VIR_CANJEResponse> SI_ZMPWS_DATAAGRO_INSERTAR_FIJ_VIR_CANJEAsync(Molinos.DataAgro.Agent.InsertarFijacionesVirtuales.SI_ZMPWS_DATAAGRO_INSERTAR_FIJ_VIR_CANJERequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_MPRFC_INSERTAR_FIJ_VIR_CANJE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iM_A_FIJARField;
        
        private string iM_COMERCIALField;
        
        private string iM_CONTRATOField;
        
        private string iM_FECHAField;
        
        private string iM_FECHA_OPERACIONField;
        
        private string iM_HORAField;
        
        private string iM_MONEDAField;
        
        private decimal iM_PRECIOField;
        
        private string iM_UNIMEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string IM_A_FIJAR {
            get {
                return this.iM_A_FIJARField;
            }
            set {
                this.iM_A_FIJARField = value;
                this.RaisePropertyChanged("IM_A_FIJAR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string IM_COMERCIAL {
            get {
                return this.iM_COMERCIALField;
            }
            set {
                this.iM_COMERCIALField = value;
                this.RaisePropertyChanged("IM_COMERCIAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string IM_CONTRATO {
            get {
                return this.iM_CONTRATOField;
            }
            set {
                this.iM_CONTRATOField = value;
                this.RaisePropertyChanged("IM_CONTRATO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string IM_FECHA {
            get {
                return this.iM_FECHAField;
            }
            set {
                this.iM_FECHAField = value;
                this.RaisePropertyChanged("IM_FECHA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string IM_FECHA_OPERACION {
            get {
                return this.iM_FECHA_OPERACIONField;
            }
            set {
                this.iM_FECHA_OPERACIONField = value;
                this.RaisePropertyChanged("IM_FECHA_OPERACION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string IM_HORA {
            get {
                return this.iM_HORAField;
            }
            set {
                this.iM_HORAField = value;
                this.RaisePropertyChanged("IM_HORA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string IM_MONEDA {
            get {
                return this.iM_MONEDAField;
            }
            set {
                this.iM_MONEDAField = value;
                this.RaisePropertyChanged("IM_MONEDA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public decimal IM_PRECIO {
            get {
                return this.iM_PRECIOField;
            }
            set {
                this.iM_PRECIOField = value;
                this.RaisePropertyChanged("IM_PRECIO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string IM_UNIME {
            get {
                return this.iM_UNIMEField;
            }
            set {
                this.iM_UNIMEField = value;
                this.RaisePropertyChanged("IM_UNIME");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_MPRFC_INSERTAR_FIJ_VIR_CANJEResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string eX_NROFIJOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string EX_NROFIJO {
            get {
                return this.eX_NROFIJOField;
            }
            set {
                this.eX_NROFIJOField = value;
                this.RaisePropertyChanged("EX_NROFIJO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_ZMPWS_DATAAGRO_INSERTAR_FIJ_VIR_CANJERequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public Molinos.DataAgro.Agent.InsertarFijacionesVirtuales.Z_MPRFC_INSERTAR_FIJ_VIR_CANJE Z_MPRFC_INSERTAR_FIJ_VIR_CANJE;
        
        public SI_ZMPWS_DATAAGRO_INSERTAR_FIJ_VIR_CANJERequest() {
        }
        
        public SI_ZMPWS_DATAAGRO_INSERTAR_FIJ_VIR_CANJERequest(Molinos.DataAgro.Agent.InsertarFijacionesVirtuales.Z_MPRFC_INSERTAR_FIJ_VIR_CANJE Z_MPRFC_INSERTAR_FIJ_VIR_CANJE) {
            this.Z_MPRFC_INSERTAR_FIJ_VIR_CANJE = Z_MPRFC_INSERTAR_FIJ_VIR_CANJE;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_ZMPWS_DATAAGRO_INSERTAR_FIJ_VIR_CANJEResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public Molinos.DataAgro.Agent.InsertarFijacionesVirtuales.Z_MPRFC_INSERTAR_FIJ_VIR_CANJEResponse Z_MPRFC_INSERTAR_FIJ_VIR_CANJEResponse;
        
        public SI_ZMPWS_DATAAGRO_INSERTAR_FIJ_VIR_CANJEResponse() {
        }
        
        public SI_ZMPWS_DATAAGRO_INSERTAR_FIJ_VIR_CANJEResponse(Molinos.DataAgro.Agent.InsertarFijacionesVirtuales.Z_MPRFC_INSERTAR_FIJ_VIR_CANJEResponse Z_MPRFC_INSERTAR_FIJ_VIR_CANJEResponse) {
            this.Z_MPRFC_INSERTAR_FIJ_VIR_CANJEResponse = Z_MPRFC_INSERTAR_FIJ_VIR_CANJEResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_ZMPWS_DATAAGRO_INSERTAR_FIJ_VIR_CANJEChannel : Molinos.DataAgro.Agent.InsertarFijacionesVirtuales.SI_ZMPWS_DATAAGRO_INSERTAR_FIJ_VIR_CANJE, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_ZMPWS_DATAAGRO_INSERTAR_FIJ_VIR_CANJEClient : System.ServiceModel.ClientBase<Molinos.DataAgro.Agent.InsertarFijacionesVirtuales.SI_ZMPWS_DATAAGRO_INSERTAR_FIJ_VIR_CANJE>, Molinos.DataAgro.Agent.InsertarFijacionesVirtuales.SI_ZMPWS_DATAAGRO_INSERTAR_FIJ_VIR_CANJE {
        
        public SI_ZMPWS_DATAAGRO_INSERTAR_FIJ_VIR_CANJEClient() {
        }
        
        public SI_ZMPWS_DATAAGRO_INSERTAR_FIJ_VIR_CANJEClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SI_ZMPWS_DATAAGRO_INSERTAR_FIJ_VIR_CANJEClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_ZMPWS_DATAAGRO_INSERTAR_FIJ_VIR_CANJEClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_ZMPWS_DATAAGRO_INSERTAR_FIJ_VIR_CANJEClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Molinos.DataAgro.Agent.InsertarFijacionesVirtuales.SI_ZMPWS_DATAAGRO_INSERTAR_FIJ_VIR_CANJEResponse Molinos.DataAgro.Agent.InsertarFijacionesVirtuales.SI_ZMPWS_DATAAGRO_INSERTAR_FIJ_VIR_CANJE.SI_ZMPWS_DATAAGRO_INSERTAR_FIJ_VIR_CANJE(Molinos.DataAgro.Agent.InsertarFijacionesVirtuales.SI_ZMPWS_DATAAGRO_INSERTAR_FIJ_VIR_CANJERequest request) {
            return base.Channel.SI_ZMPWS_DATAAGRO_INSERTAR_FIJ_VIR_CANJE(request);
        }
        
        public Molinos.DataAgro.Agent.InsertarFijacionesVirtuales.Z_MPRFC_INSERTAR_FIJ_VIR_CANJEResponse SI_ZMPWS_DATAAGRO_INSERTAR_FIJ_VIR_CANJE(Molinos.DataAgro.Agent.InsertarFijacionesVirtuales.Z_MPRFC_INSERTAR_FIJ_VIR_CANJE Z_MPRFC_INSERTAR_FIJ_VIR_CANJE) {
            Molinos.DataAgro.Agent.InsertarFijacionesVirtuales.SI_ZMPWS_DATAAGRO_INSERTAR_FIJ_VIR_CANJERequest inValue = new Molinos.DataAgro.Agent.InsertarFijacionesVirtuales.SI_ZMPWS_DATAAGRO_INSERTAR_FIJ_VIR_CANJERequest();
            inValue.Z_MPRFC_INSERTAR_FIJ_VIR_CANJE = Z_MPRFC_INSERTAR_FIJ_VIR_CANJE;
            Molinos.DataAgro.Agent.InsertarFijacionesVirtuales.SI_ZMPWS_DATAAGRO_INSERTAR_FIJ_VIR_CANJEResponse retVal = ((Molinos.DataAgro.Agent.InsertarFijacionesVirtuales.SI_ZMPWS_DATAAGRO_INSERTAR_FIJ_VIR_CANJE)(this)).SI_ZMPWS_DATAAGRO_INSERTAR_FIJ_VIR_CANJE(inValue);
            return retVal.Z_MPRFC_INSERTAR_FIJ_VIR_CANJEResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Molinos.DataAgro.Agent.InsertarFijacionesVirtuales.SI_ZMPWS_DATAAGRO_INSERTAR_FIJ_VIR_CANJEResponse> Molinos.DataAgro.Agent.InsertarFijacionesVirtuales.SI_ZMPWS_DATAAGRO_INSERTAR_FIJ_VIR_CANJE.SI_ZMPWS_DATAAGRO_INSERTAR_FIJ_VIR_CANJEAsync(Molinos.DataAgro.Agent.InsertarFijacionesVirtuales.SI_ZMPWS_DATAAGRO_INSERTAR_FIJ_VIR_CANJERequest request) {
            return base.Channel.SI_ZMPWS_DATAAGRO_INSERTAR_FIJ_VIR_CANJEAsync(request);
        }
        
        public System.Threading.Tasks.Task<Molinos.DataAgro.Agent.InsertarFijacionesVirtuales.SI_ZMPWS_DATAAGRO_INSERTAR_FIJ_VIR_CANJEResponse> SI_ZMPWS_DATAAGRO_INSERTAR_FIJ_VIR_CANJEAsync(Molinos.DataAgro.Agent.InsertarFijacionesVirtuales.Z_MPRFC_INSERTAR_FIJ_VIR_CANJE Z_MPRFC_INSERTAR_FIJ_VIR_CANJE) {
            Molinos.DataAgro.Agent.InsertarFijacionesVirtuales.SI_ZMPWS_DATAAGRO_INSERTAR_FIJ_VIR_CANJERequest inValue = new Molinos.DataAgro.Agent.InsertarFijacionesVirtuales.SI_ZMPWS_DATAAGRO_INSERTAR_FIJ_VIR_CANJERequest();
            inValue.Z_MPRFC_INSERTAR_FIJ_VIR_CANJE = Z_MPRFC_INSERTAR_FIJ_VIR_CANJE;
            return ((Molinos.DataAgro.Agent.InsertarFijacionesVirtuales.SI_ZMPWS_DATAAGRO_INSERTAR_FIJ_VIR_CANJE)(this)).SI_ZMPWS_DATAAGRO_INSERTAR_FIJ_VIR_CANJEAsync(inValue);
        }
    }
}
