//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Molinos.DataAgro.Agent.ModificarCupos {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="namespace:dataagro", ConfigurationName="ModificarCupos.SI_ZMPWS_DATAAGRO_MODIFICAR_CUPO")]
    public interface SI_ZMPWS_DATAAGRO_MODIFICAR_CUPO {
        
        // CODEGEN: Generating message contract since the operation SI_ZMPWS_DATAAGRO_MODIFICAR_CUPO is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Molinos.DataAgro.Agent.ModificarCupos.SI_ZMPWS_DATAAGRO_MODIFICAR_CUPOResponse SI_ZMPWS_DATAAGRO_MODIFICAR_CUPO(Molinos.DataAgro.Agent.ModificarCupos.SI_ZMPWS_DATAAGRO_MODIFICAR_CUPORequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<Molinos.DataAgro.Agent.ModificarCupos.SI_ZMPWS_DATAAGRO_MODIFICAR_CUPOResponse> SI_ZMPWS_DATAAGRO_MODIFICAR_CUPOAsync(Molinos.DataAgro.Agent.ModificarCupos.SI_ZMPWS_DATAAGRO_MODIFICAR_CUPORequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_MPRFC_MODIFICAR_CUPO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iM_CALIDADField;
        
        private string iM_CODIGOField;
        
        private string iM_COMERCIALField;
        
        private string iM_DESCPROVField;
        
        private string iM_DESTINATARIOField;
        
        private string iM_FLETE_PROCField;
        
        private string iM_OBSERVACIONESField;
        
        private string iM_PROVEEDORField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string IM_CALIDAD {
            get {
                return this.iM_CALIDADField;
            }
            set {
                this.iM_CALIDADField = value;
                this.RaisePropertyChanged("IM_CALIDAD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string IM_CODIGO {
            get {
                return this.iM_CODIGOField;
            }
            set {
                this.iM_CODIGOField = value;
                this.RaisePropertyChanged("IM_CODIGO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string IM_COMERCIAL {
            get {
                return this.iM_COMERCIALField;
            }
            set {
                this.iM_COMERCIALField = value;
                this.RaisePropertyChanged("IM_COMERCIAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string IM_DESCPROV {
            get {
                return this.iM_DESCPROVField;
            }
            set {
                this.iM_DESCPROVField = value;
                this.RaisePropertyChanged("IM_DESCPROV");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string IM_DESTINATARIO {
            get {
                return this.iM_DESTINATARIOField;
            }
            set {
                this.iM_DESTINATARIOField = value;
                this.RaisePropertyChanged("IM_DESTINATARIO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string IM_FLETE_PROC {
            get {
                return this.iM_FLETE_PROCField;
            }
            set {
                this.iM_FLETE_PROCField = value;
                this.RaisePropertyChanged("IM_FLETE_PROC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string IM_OBSERVACIONES {
            get {
                return this.iM_OBSERVACIONESField;
            }
            set {
                this.iM_OBSERVACIONESField = value;
                this.RaisePropertyChanged("IM_OBSERVACIONES");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string IM_PROVEEDOR {
            get {
                return this.iM_PROVEEDORField;
            }
            set {
                this.iM_PROVEEDORField = value;
                this.RaisePropertyChanged("IM_PROVEEDOR");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_MPRFC_MODIFICAR_CUPOResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string eX_MENSAJEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string EX_MENSAJE {
            get {
                return this.eX_MENSAJEField;
            }
            set {
                this.eX_MENSAJEField = value;
                this.RaisePropertyChanged("EX_MENSAJE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_ZMPWS_DATAAGRO_MODIFICAR_CUPORequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public Molinos.DataAgro.Agent.ModificarCupos.Z_MPRFC_MODIFICAR_CUPO Z_MPRFC_MODIFICAR_CUPO;
        
        public SI_ZMPWS_DATAAGRO_MODIFICAR_CUPORequest() {
        }
        
        public SI_ZMPWS_DATAAGRO_MODIFICAR_CUPORequest(Molinos.DataAgro.Agent.ModificarCupos.Z_MPRFC_MODIFICAR_CUPO Z_MPRFC_MODIFICAR_CUPO) {
            this.Z_MPRFC_MODIFICAR_CUPO = Z_MPRFC_MODIFICAR_CUPO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_ZMPWS_DATAAGRO_MODIFICAR_CUPOResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public Molinos.DataAgro.Agent.ModificarCupos.Z_MPRFC_MODIFICAR_CUPOResponse Z_MPRFC_MODIFICAR_CUPOResponse;
        
        public SI_ZMPWS_DATAAGRO_MODIFICAR_CUPOResponse() {
        }
        
        public SI_ZMPWS_DATAAGRO_MODIFICAR_CUPOResponse(Molinos.DataAgro.Agent.ModificarCupos.Z_MPRFC_MODIFICAR_CUPOResponse Z_MPRFC_MODIFICAR_CUPOResponse) {
            this.Z_MPRFC_MODIFICAR_CUPOResponse = Z_MPRFC_MODIFICAR_CUPOResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_ZMPWS_DATAAGRO_MODIFICAR_CUPOChannel : Molinos.DataAgro.Agent.ModificarCupos.SI_ZMPWS_DATAAGRO_MODIFICAR_CUPO, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_ZMPWS_DATAAGRO_MODIFICAR_CUPOClient : System.ServiceModel.ClientBase<Molinos.DataAgro.Agent.ModificarCupos.SI_ZMPWS_DATAAGRO_MODIFICAR_CUPO>, Molinos.DataAgro.Agent.ModificarCupos.SI_ZMPWS_DATAAGRO_MODIFICAR_CUPO {
        
        public SI_ZMPWS_DATAAGRO_MODIFICAR_CUPOClient() {
        }
        
        public SI_ZMPWS_DATAAGRO_MODIFICAR_CUPOClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SI_ZMPWS_DATAAGRO_MODIFICAR_CUPOClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_ZMPWS_DATAAGRO_MODIFICAR_CUPOClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_ZMPWS_DATAAGRO_MODIFICAR_CUPOClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Molinos.DataAgro.Agent.ModificarCupos.SI_ZMPWS_DATAAGRO_MODIFICAR_CUPOResponse Molinos.DataAgro.Agent.ModificarCupos.SI_ZMPWS_DATAAGRO_MODIFICAR_CUPO.SI_ZMPWS_DATAAGRO_MODIFICAR_CUPO(Molinos.DataAgro.Agent.ModificarCupos.SI_ZMPWS_DATAAGRO_MODIFICAR_CUPORequest request) {
            return base.Channel.SI_ZMPWS_DATAAGRO_MODIFICAR_CUPO(request);
        }
        
        public Molinos.DataAgro.Agent.ModificarCupos.Z_MPRFC_MODIFICAR_CUPOResponse SI_ZMPWS_DATAAGRO_MODIFICAR_CUPO(Molinos.DataAgro.Agent.ModificarCupos.Z_MPRFC_MODIFICAR_CUPO Z_MPRFC_MODIFICAR_CUPO) {
            Molinos.DataAgro.Agent.ModificarCupos.SI_ZMPWS_DATAAGRO_MODIFICAR_CUPORequest inValue = new Molinos.DataAgro.Agent.ModificarCupos.SI_ZMPWS_DATAAGRO_MODIFICAR_CUPORequest();
            inValue.Z_MPRFC_MODIFICAR_CUPO = Z_MPRFC_MODIFICAR_CUPO;
            Molinos.DataAgro.Agent.ModificarCupos.SI_ZMPWS_DATAAGRO_MODIFICAR_CUPOResponse retVal = ((Molinos.DataAgro.Agent.ModificarCupos.SI_ZMPWS_DATAAGRO_MODIFICAR_CUPO)(this)).SI_ZMPWS_DATAAGRO_MODIFICAR_CUPO(inValue);
            return retVal.Z_MPRFC_MODIFICAR_CUPOResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Molinos.DataAgro.Agent.ModificarCupos.SI_ZMPWS_DATAAGRO_MODIFICAR_CUPOResponse> Molinos.DataAgro.Agent.ModificarCupos.SI_ZMPWS_DATAAGRO_MODIFICAR_CUPO.SI_ZMPWS_DATAAGRO_MODIFICAR_CUPOAsync(Molinos.DataAgro.Agent.ModificarCupos.SI_ZMPWS_DATAAGRO_MODIFICAR_CUPORequest request) {
            return base.Channel.SI_ZMPWS_DATAAGRO_MODIFICAR_CUPOAsync(request);
        }
        
        public System.Threading.Tasks.Task<Molinos.DataAgro.Agent.ModificarCupos.SI_ZMPWS_DATAAGRO_MODIFICAR_CUPOResponse> SI_ZMPWS_DATAAGRO_MODIFICAR_CUPOAsync(Molinos.DataAgro.Agent.ModificarCupos.Z_MPRFC_MODIFICAR_CUPO Z_MPRFC_MODIFICAR_CUPO) {
            Molinos.DataAgro.Agent.ModificarCupos.SI_ZMPWS_DATAAGRO_MODIFICAR_CUPORequest inValue = new Molinos.DataAgro.Agent.ModificarCupos.SI_ZMPWS_DATAAGRO_MODIFICAR_CUPORequest();
            inValue.Z_MPRFC_MODIFICAR_CUPO = Z_MPRFC_MODIFICAR_CUPO;
            return ((Molinos.DataAgro.Agent.ModificarCupos.SI_ZMPWS_DATAAGRO_MODIFICAR_CUPO)(this)).SI_ZMPWS_DATAAGRO_MODIFICAR_CUPOAsync(inValue);
        }
    }
}
