//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Molinos.DataAgro.Agent.AcuerdosGenerados {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="namespace:dataagro", ConfigurationName="AcuerdosGenerados.SI_ZMPWS_DATAAGRO_ACUERDOS_GENERADOS")]
    public interface SI_ZMPWS_DATAAGRO_ACUERDOS_GENERADOS {
        
        // CODEGEN: Generating message contract since the operation SI_ZMPWS_DATAAGRO_ACUERDOS_GENERADOS is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Molinos.DataAgro.Agent.AcuerdosGenerados.SI_ZMPWS_DATAAGRO_ACUERDOS_GENERADOSResponse SI_ZMPWS_DATAAGRO_ACUERDOS_GENERADOS(Molinos.DataAgro.Agent.AcuerdosGenerados.SI_ZMPWS_DATAAGRO_ACUERDOS_GENERADOSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<Molinos.DataAgro.Agent.AcuerdosGenerados.SI_ZMPWS_DATAAGRO_ACUERDOS_GENERADOSResponse> SI_ZMPWS_DATAAGRO_ACUERDOS_GENERADOSAsync(Molinos.DataAgro.Agent.AcuerdosGenerados.SI_ZMPWS_DATAAGRO_ACUERDOS_GENERADOSRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_MPRFC_ACUERDOS_GENERADOS : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iM_CUITField;
        
        private string iM_MATERIALField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string IM_CUIT {
            get {
                return this.iM_CUITField;
            }
            set {
                this.iM_CUITField = value;
                this.RaisePropertyChanged("IM_CUIT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string IM_MATERIAL {
            get {
                return this.iM_MATERIALField;
            }
            set {
                this.iM_MATERIALField = value;
                this.RaisePropertyChanged("IM_MATERIAL");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMPES6340 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nROACUERDOField;
        
        private string cLASEDOCField;
        
        private string cLIENTEField;
        
        private string mATERIALField;
        
        private string fECHAREGField;
        
        private string iNPERVALField;
        
        private string fINPERVALField;
        
        private string cOSECHAField;
        
        private decimal cANTIDADField;
        
        private string eSTADOField;
        
        private string uNIDADField;
        
        private decimal pRECIOSERVField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string NROACUERDO {
            get {
                return this.nROACUERDOField;
            }
            set {
                this.nROACUERDOField = value;
                this.RaisePropertyChanged("NROACUERDO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string CLASEDOC {
            get {
                return this.cLASEDOCField;
            }
            set {
                this.cLASEDOCField = value;
                this.RaisePropertyChanged("CLASEDOC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string CLIENTE {
            get {
                return this.cLIENTEField;
            }
            set {
                this.cLIENTEField = value;
                this.RaisePropertyChanged("CLIENTE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string MATERIAL {
            get {
                return this.mATERIALField;
            }
            set {
                this.mATERIALField = value;
                this.RaisePropertyChanged("MATERIAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string FECHAREG {
            get {
                return this.fECHAREGField;
            }
            set {
                this.fECHAREGField = value;
                this.RaisePropertyChanged("FECHAREG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string INPERVAL {
            get {
                return this.iNPERVALField;
            }
            set {
                this.iNPERVALField = value;
                this.RaisePropertyChanged("INPERVAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string FINPERVAL {
            get {
                return this.fINPERVALField;
            }
            set {
                this.fINPERVALField = value;
                this.RaisePropertyChanged("FINPERVAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string COSECHA {
            get {
                return this.cOSECHAField;
            }
            set {
                this.cOSECHAField = value;
                this.RaisePropertyChanged("COSECHA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public decimal CANTIDAD {
            get {
                return this.cANTIDADField;
            }
            set {
                this.cANTIDADField = value;
                this.RaisePropertyChanged("CANTIDAD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string ESTADO {
            get {
                return this.eSTADOField;
            }
            set {
                this.eSTADOField = value;
                this.RaisePropertyChanged("ESTADO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string UNIDAD {
            get {
                return this.uNIDADField;
            }
            set {
                this.uNIDADField = value;
                this.RaisePropertyChanged("UNIDAD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public decimal PRECIOSERV {
            get {
                return this.pRECIOSERVField;
            }
            set {
                this.pRECIOSERVField = value;
                this.RaisePropertyChanged("PRECIOSERV");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_MPRFC_ACUERDOS_GENERADOSResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZMPES6340[] eX_ACUER_GENERADOSField;
        
        private string eX_MENSAJEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZMPES6340[] EX_ACUER_GENERADOS {
            get {
                return this.eX_ACUER_GENERADOSField;
            }
            set {
                this.eX_ACUER_GENERADOSField = value;
                this.RaisePropertyChanged("EX_ACUER_GENERADOS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string EX_MENSAJE {
            get {
                return this.eX_MENSAJEField;
            }
            set {
                this.eX_MENSAJEField = value;
                this.RaisePropertyChanged("EX_MENSAJE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_ZMPWS_DATAAGRO_ACUERDOS_GENERADOSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public Molinos.DataAgro.Agent.AcuerdosGenerados.Z_MPRFC_ACUERDOS_GENERADOS Z_MPRFC_ACUERDOS_GENERADOS;
        
        public SI_ZMPWS_DATAAGRO_ACUERDOS_GENERADOSRequest() {
        }
        
        public SI_ZMPWS_DATAAGRO_ACUERDOS_GENERADOSRequest(Molinos.DataAgro.Agent.AcuerdosGenerados.Z_MPRFC_ACUERDOS_GENERADOS Z_MPRFC_ACUERDOS_GENERADOS) {
            this.Z_MPRFC_ACUERDOS_GENERADOS = Z_MPRFC_ACUERDOS_GENERADOS;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_ZMPWS_DATAAGRO_ACUERDOS_GENERADOSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public Molinos.DataAgro.Agent.AcuerdosGenerados.Z_MPRFC_ACUERDOS_GENERADOSResponse Z_MPRFC_ACUERDOS_GENERADOSResponse;
        
        public SI_ZMPWS_DATAAGRO_ACUERDOS_GENERADOSResponse() {
        }
        
        public SI_ZMPWS_DATAAGRO_ACUERDOS_GENERADOSResponse(Molinos.DataAgro.Agent.AcuerdosGenerados.Z_MPRFC_ACUERDOS_GENERADOSResponse Z_MPRFC_ACUERDOS_GENERADOSResponse) {
            this.Z_MPRFC_ACUERDOS_GENERADOSResponse = Z_MPRFC_ACUERDOS_GENERADOSResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_ZMPWS_DATAAGRO_ACUERDOS_GENERADOSChannel : Molinos.DataAgro.Agent.AcuerdosGenerados.SI_ZMPWS_DATAAGRO_ACUERDOS_GENERADOS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_ZMPWS_DATAAGRO_ACUERDOS_GENERADOSClient : System.ServiceModel.ClientBase<Molinos.DataAgro.Agent.AcuerdosGenerados.SI_ZMPWS_DATAAGRO_ACUERDOS_GENERADOS>, Molinos.DataAgro.Agent.AcuerdosGenerados.SI_ZMPWS_DATAAGRO_ACUERDOS_GENERADOS {
        
        public SI_ZMPWS_DATAAGRO_ACUERDOS_GENERADOSClient() {
        }
        
        public SI_ZMPWS_DATAAGRO_ACUERDOS_GENERADOSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SI_ZMPWS_DATAAGRO_ACUERDOS_GENERADOSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_ZMPWS_DATAAGRO_ACUERDOS_GENERADOSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_ZMPWS_DATAAGRO_ACUERDOS_GENERADOSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Molinos.DataAgro.Agent.AcuerdosGenerados.SI_ZMPWS_DATAAGRO_ACUERDOS_GENERADOSResponse Molinos.DataAgro.Agent.AcuerdosGenerados.SI_ZMPWS_DATAAGRO_ACUERDOS_GENERADOS.SI_ZMPWS_DATAAGRO_ACUERDOS_GENERADOS(Molinos.DataAgro.Agent.AcuerdosGenerados.SI_ZMPWS_DATAAGRO_ACUERDOS_GENERADOSRequest request) {
            return base.Channel.SI_ZMPWS_DATAAGRO_ACUERDOS_GENERADOS(request);
        }
        
        public Molinos.DataAgro.Agent.AcuerdosGenerados.Z_MPRFC_ACUERDOS_GENERADOSResponse SI_ZMPWS_DATAAGRO_ACUERDOS_GENERADOS(Molinos.DataAgro.Agent.AcuerdosGenerados.Z_MPRFC_ACUERDOS_GENERADOS Z_MPRFC_ACUERDOS_GENERADOS) {
            Molinos.DataAgro.Agent.AcuerdosGenerados.SI_ZMPWS_DATAAGRO_ACUERDOS_GENERADOSRequest inValue = new Molinos.DataAgro.Agent.AcuerdosGenerados.SI_ZMPWS_DATAAGRO_ACUERDOS_GENERADOSRequest();
            inValue.Z_MPRFC_ACUERDOS_GENERADOS = Z_MPRFC_ACUERDOS_GENERADOS;
            Molinos.DataAgro.Agent.AcuerdosGenerados.SI_ZMPWS_DATAAGRO_ACUERDOS_GENERADOSResponse retVal = ((Molinos.DataAgro.Agent.AcuerdosGenerados.SI_ZMPWS_DATAAGRO_ACUERDOS_GENERADOS)(this)).SI_ZMPWS_DATAAGRO_ACUERDOS_GENERADOS(inValue);
            return retVal.Z_MPRFC_ACUERDOS_GENERADOSResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Molinos.DataAgro.Agent.AcuerdosGenerados.SI_ZMPWS_DATAAGRO_ACUERDOS_GENERADOSResponse> Molinos.DataAgro.Agent.AcuerdosGenerados.SI_ZMPWS_DATAAGRO_ACUERDOS_GENERADOS.SI_ZMPWS_DATAAGRO_ACUERDOS_GENERADOSAsync(Molinos.DataAgro.Agent.AcuerdosGenerados.SI_ZMPWS_DATAAGRO_ACUERDOS_GENERADOSRequest request) {
            return base.Channel.SI_ZMPWS_DATAAGRO_ACUERDOS_GENERADOSAsync(request);
        }
        
        public System.Threading.Tasks.Task<Molinos.DataAgro.Agent.AcuerdosGenerados.SI_ZMPWS_DATAAGRO_ACUERDOS_GENERADOSResponse> SI_ZMPWS_DATAAGRO_ACUERDOS_GENERADOSAsync(Molinos.DataAgro.Agent.AcuerdosGenerados.Z_MPRFC_ACUERDOS_GENERADOS Z_MPRFC_ACUERDOS_GENERADOS) {
            Molinos.DataAgro.Agent.AcuerdosGenerados.SI_ZMPWS_DATAAGRO_ACUERDOS_GENERADOSRequest inValue = new Molinos.DataAgro.Agent.AcuerdosGenerados.SI_ZMPWS_DATAAGRO_ACUERDOS_GENERADOSRequest();
            inValue.Z_MPRFC_ACUERDOS_GENERADOS = Z_MPRFC_ACUERDOS_GENERADOS;
            return ((Molinos.DataAgro.Agent.AcuerdosGenerados.SI_ZMPWS_DATAAGRO_ACUERDOS_GENERADOS)(this)).SI_ZMPWS_DATAAGRO_ACUERDOS_GENERADOSAsync(inValue);
        }
    }
}
