//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Molinos.DataAgro.Agent.AltaTempranaNosisBolsaRuca {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="namespace:dataagro", ConfigurationName="AltaTempranaNosisBolsaRuca.SI_ZMPWS_DATAAGRO_ALTA_TEMPRANA_N_R_CO")]
    public interface SI_ZMPWS_DATAAGRO_ALTA_TEMPRANA_N_R_CO {
        
        // CODEGEN: Generating message contract since the operation SI_ZMPWS_DATAAGRO_ALTA_TEMPRANA_N_R_CO is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Molinos.DataAgro.Agent.AltaTempranaNosisBolsaRuca.SI_ZMPWS_DATAAGRO_ALTA_TEMPRANA_N_R_COResponse SI_ZMPWS_DATAAGRO_ALTA_TEMPRANA_N_R_CO(Molinos.DataAgro.Agent.AltaTempranaNosisBolsaRuca.SI_ZMPWS_DATAAGRO_ALTA_TEMPRANA_N_R_CORequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<Molinos.DataAgro.Agent.AltaTempranaNosisBolsaRuca.SI_ZMPWS_DATAAGRO_ALTA_TEMPRANA_N_R_COResponse> SI_ZMPWS_DATAAGRO_ALTA_TEMPRANA_N_R_COAsync(Molinos.DataAgro.Agent.AltaTempranaNosisBolsaRuca.SI_ZMPWS_DATAAGRO_ALTA_TEMPRANA_N_R_CORequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_MPRFC_ALTA_TEMPRANA_N_R_CO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iM_CUITField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string IM_CUIT {
            get {
                return this.iM_CUITField;
            }
            set {
                this.iM_CUITField = value;
                this.RaisePropertyChanged("IM_CUIT");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMPES540 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dIRECTOField;
        
        private string pROV_PLAN_CANJEField;
        
        private string cONSIGNATARIOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string DIRECTO {
            get {
                return this.dIRECTOField;
            }
            set {
                this.dIRECTOField = value;
                this.RaisePropertyChanged("DIRECTO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string PROV_PLAN_CANJE {
            get {
                return this.pROV_PLAN_CANJEField;
            }
            set {
                this.pROV_PLAN_CANJEField = value;
                this.RaisePropertyChanged("PROV_PLAN_CANJE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string CONSIGNATARIO {
            get {
                return this.cONSIGNATARIOField;
            }
            set {
                this.cONSIGNATARIOField = value;
                this.RaisePropertyChanged("CONSIGNATARIO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMPES5510 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZMPES540 aCOPIADORField;
        
        private ZMPES540 oTROSField;
        
        private string cORREDORField;
        
        private string fASONField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ZMPES540 ACOPIADOR {
            get {
                return this.aCOPIADORField;
            }
            set {
                this.aCOPIADORField = value;
                this.RaisePropertyChanged("ACOPIADOR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ZMPES540 OTROS {
            get {
                return this.oTROSField;
            }
            set {
                this.oTROSField = value;
                this.RaisePropertyChanged("OTROS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string CORREDOR {
            get {
                return this.cORREDORField;
            }
            set {
                this.cORREDORField = value;
                this.RaisePropertyChanged("CORREDOR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string FASON {
            get {
                return this.fASONField;
            }
            set {
                this.fASONField = value;
                this.RaisePropertyChanged("FASON");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_MPRFC_ALTA_TEMPRANA_N_R_COResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string eX_ALTA_TEMPRANAField;
        
        private string eX_BOLSAField;
        
        private string eX_CARTAField;
        
        private string eX_CONSIGNATARIOField;
        
        private string eX_FECHA_ACTUALIZACIONField;
        
        private string eX_MENSAJEField;
        
        private string eX_NOSISField;
        
        private string eX_PLAN_CANJEField;
        
        private ZMPES5510 eX_RUCAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string EX_ALTA_TEMPRANA {
            get {
                return this.eX_ALTA_TEMPRANAField;
            }
            set {
                this.eX_ALTA_TEMPRANAField = value;
                this.RaisePropertyChanged("EX_ALTA_TEMPRANA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string EX_BOLSA {
            get {
                return this.eX_BOLSAField;
            }
            set {
                this.eX_BOLSAField = value;
                this.RaisePropertyChanged("EX_BOLSA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string EX_CARTA {
            get {
                return this.eX_CARTAField;
            }
            set {
                this.eX_CARTAField = value;
                this.RaisePropertyChanged("EX_CARTA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string EX_CONSIGNATARIO {
            get {
                return this.eX_CONSIGNATARIOField;
            }
            set {
                this.eX_CONSIGNATARIOField = value;
                this.RaisePropertyChanged("EX_CONSIGNATARIO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string EX_FECHA_ACTUALIZACION {
            get {
                return this.eX_FECHA_ACTUALIZACIONField;
            }
            set {
                this.eX_FECHA_ACTUALIZACIONField = value;
                this.RaisePropertyChanged("EX_FECHA_ACTUALIZACION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string EX_MENSAJE {
            get {
                return this.eX_MENSAJEField;
            }
            set {
                this.eX_MENSAJEField = value;
                this.RaisePropertyChanged("EX_MENSAJE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string EX_NOSIS {
            get {
                return this.eX_NOSISField;
            }
            set {
                this.eX_NOSISField = value;
                this.RaisePropertyChanged("EX_NOSIS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string EX_PLAN_CANJE {
            get {
                return this.eX_PLAN_CANJEField;
            }
            set {
                this.eX_PLAN_CANJEField = value;
                this.RaisePropertyChanged("EX_PLAN_CANJE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public ZMPES5510 EX_RUCA {
            get {
                return this.eX_RUCAField;
            }
            set {
                this.eX_RUCAField = value;
                this.RaisePropertyChanged("EX_RUCA");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_ZMPWS_DATAAGRO_ALTA_TEMPRANA_N_R_CORequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public Molinos.DataAgro.Agent.AltaTempranaNosisBolsaRuca.Z_MPRFC_ALTA_TEMPRANA_N_R_CO Z_MPRFC_ALTA_TEMPRANA_N_R_CO;
        
        public SI_ZMPWS_DATAAGRO_ALTA_TEMPRANA_N_R_CORequest() {
        }
        
        public SI_ZMPWS_DATAAGRO_ALTA_TEMPRANA_N_R_CORequest(Molinos.DataAgro.Agent.AltaTempranaNosisBolsaRuca.Z_MPRFC_ALTA_TEMPRANA_N_R_CO Z_MPRFC_ALTA_TEMPRANA_N_R_CO) {
            this.Z_MPRFC_ALTA_TEMPRANA_N_R_CO = Z_MPRFC_ALTA_TEMPRANA_N_R_CO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_ZMPWS_DATAAGRO_ALTA_TEMPRANA_N_R_COResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public Molinos.DataAgro.Agent.AltaTempranaNosisBolsaRuca.Z_MPRFC_ALTA_TEMPRANA_N_R_COResponse Z_MPRFC_ALTA_TEMPRANA_N_R_COResponse;
        
        public SI_ZMPWS_DATAAGRO_ALTA_TEMPRANA_N_R_COResponse() {
        }
        
        public SI_ZMPWS_DATAAGRO_ALTA_TEMPRANA_N_R_COResponse(Molinos.DataAgro.Agent.AltaTempranaNosisBolsaRuca.Z_MPRFC_ALTA_TEMPRANA_N_R_COResponse Z_MPRFC_ALTA_TEMPRANA_N_R_COResponse) {
            this.Z_MPRFC_ALTA_TEMPRANA_N_R_COResponse = Z_MPRFC_ALTA_TEMPRANA_N_R_COResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_ZMPWS_DATAAGRO_ALTA_TEMPRANA_N_R_COChannel : Molinos.DataAgro.Agent.AltaTempranaNosisBolsaRuca.SI_ZMPWS_DATAAGRO_ALTA_TEMPRANA_N_R_CO, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_ZMPWS_DATAAGRO_ALTA_TEMPRANA_N_R_COClient : System.ServiceModel.ClientBase<Molinos.DataAgro.Agent.AltaTempranaNosisBolsaRuca.SI_ZMPWS_DATAAGRO_ALTA_TEMPRANA_N_R_CO>, Molinos.DataAgro.Agent.AltaTempranaNosisBolsaRuca.SI_ZMPWS_DATAAGRO_ALTA_TEMPRANA_N_R_CO {
        
        public SI_ZMPWS_DATAAGRO_ALTA_TEMPRANA_N_R_COClient() {
        }
        
        public SI_ZMPWS_DATAAGRO_ALTA_TEMPRANA_N_R_COClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SI_ZMPWS_DATAAGRO_ALTA_TEMPRANA_N_R_COClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_ZMPWS_DATAAGRO_ALTA_TEMPRANA_N_R_COClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_ZMPWS_DATAAGRO_ALTA_TEMPRANA_N_R_COClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Molinos.DataAgro.Agent.AltaTempranaNosisBolsaRuca.SI_ZMPWS_DATAAGRO_ALTA_TEMPRANA_N_R_COResponse Molinos.DataAgro.Agent.AltaTempranaNosisBolsaRuca.SI_ZMPWS_DATAAGRO_ALTA_TEMPRANA_N_R_CO.SI_ZMPWS_DATAAGRO_ALTA_TEMPRANA_N_R_CO(Molinos.DataAgro.Agent.AltaTempranaNosisBolsaRuca.SI_ZMPWS_DATAAGRO_ALTA_TEMPRANA_N_R_CORequest request) {
            return base.Channel.SI_ZMPWS_DATAAGRO_ALTA_TEMPRANA_N_R_CO(request);
        }
        
        public Molinos.DataAgro.Agent.AltaTempranaNosisBolsaRuca.Z_MPRFC_ALTA_TEMPRANA_N_R_COResponse SI_ZMPWS_DATAAGRO_ALTA_TEMPRANA_N_R_CO(Molinos.DataAgro.Agent.AltaTempranaNosisBolsaRuca.Z_MPRFC_ALTA_TEMPRANA_N_R_CO Z_MPRFC_ALTA_TEMPRANA_N_R_CO) {
            Molinos.DataAgro.Agent.AltaTempranaNosisBolsaRuca.SI_ZMPWS_DATAAGRO_ALTA_TEMPRANA_N_R_CORequest inValue = new Molinos.DataAgro.Agent.AltaTempranaNosisBolsaRuca.SI_ZMPWS_DATAAGRO_ALTA_TEMPRANA_N_R_CORequest();
            inValue.Z_MPRFC_ALTA_TEMPRANA_N_R_CO = Z_MPRFC_ALTA_TEMPRANA_N_R_CO;
            Molinos.DataAgro.Agent.AltaTempranaNosisBolsaRuca.SI_ZMPWS_DATAAGRO_ALTA_TEMPRANA_N_R_COResponse retVal = ((Molinos.DataAgro.Agent.AltaTempranaNosisBolsaRuca.SI_ZMPWS_DATAAGRO_ALTA_TEMPRANA_N_R_CO)(this)).SI_ZMPWS_DATAAGRO_ALTA_TEMPRANA_N_R_CO(inValue);
            return retVal.Z_MPRFC_ALTA_TEMPRANA_N_R_COResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Molinos.DataAgro.Agent.AltaTempranaNosisBolsaRuca.SI_ZMPWS_DATAAGRO_ALTA_TEMPRANA_N_R_COResponse> Molinos.DataAgro.Agent.AltaTempranaNosisBolsaRuca.SI_ZMPWS_DATAAGRO_ALTA_TEMPRANA_N_R_CO.SI_ZMPWS_DATAAGRO_ALTA_TEMPRANA_N_R_COAsync(Molinos.DataAgro.Agent.AltaTempranaNosisBolsaRuca.SI_ZMPWS_DATAAGRO_ALTA_TEMPRANA_N_R_CORequest request) {
            return base.Channel.SI_ZMPWS_DATAAGRO_ALTA_TEMPRANA_N_R_COAsync(request);
        }
        
        public System.Threading.Tasks.Task<Molinos.DataAgro.Agent.AltaTempranaNosisBolsaRuca.SI_ZMPWS_DATAAGRO_ALTA_TEMPRANA_N_R_COResponse> SI_ZMPWS_DATAAGRO_ALTA_TEMPRANA_N_R_COAsync(Molinos.DataAgro.Agent.AltaTempranaNosisBolsaRuca.Z_MPRFC_ALTA_TEMPRANA_N_R_CO Z_MPRFC_ALTA_TEMPRANA_N_R_CO) {
            Molinos.DataAgro.Agent.AltaTempranaNosisBolsaRuca.SI_ZMPWS_DATAAGRO_ALTA_TEMPRANA_N_R_CORequest inValue = new Molinos.DataAgro.Agent.AltaTempranaNosisBolsaRuca.SI_ZMPWS_DATAAGRO_ALTA_TEMPRANA_N_R_CORequest();
            inValue.Z_MPRFC_ALTA_TEMPRANA_N_R_CO = Z_MPRFC_ALTA_TEMPRANA_N_R_CO;
            return ((Molinos.DataAgro.Agent.AltaTempranaNosisBolsaRuca.SI_ZMPWS_DATAAGRO_ALTA_TEMPRANA_N_R_CO)(this)).SI_ZMPWS_DATAAGRO_ALTA_TEMPRANA_N_R_COAsync(inValue);
        }
    }
}
