<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.5" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <!--General-->
    <ProjectSolution>..\DataAgro.sln</ProjectSolution>
    <NUnitToolPath>C:\Program Files (x86)\NUnit 2.6.3\bin</NUnitToolPath>
    <NUnitProject>..\Molinos.DataAgro.Test\bin\Jenkins\Molinos.DataAgro.Test.dll</NUnitProject>
    <OutputDir>..\Deploy\</OutputDir>
    <PackageWeb>..\WebDataAgro\obj\Jenkins\Package\**\*</PackageWeb>

    <OpenCoverTool>C:\Program Files (x86)\OpenCover\OpenCover.Console.exe</OpenCoverTool>
    <OpenCoverFilter>+[Molinos.DataAgro.Agent]* +[Molinos.DataAgro.Business]* +[Molinos.DataAgro.Entities]* +[Molinos.DataAgro.Interfaces]* +[Molinos.DataAgro.Mapping]* +[Molinos.DataAgro.Report]* +[WebDataAgro]*</OpenCoverFilter>

    <ReportGeneratorTool>C:\Program Files (x86)\ReportGenerator\bin\ReportGenerator.exe</ReportGeneratorTool>

    <GendarmeTool>C:\Program Files (x86)\Gendarme\gendarme.exe</GendarmeTool>
    <GendarmeAssemblies>..\Molinos.DataAgro.Agent\bin\Jenkins\Molinos.DataAgro.Agent.dll ..\Molinos.DataAgro.Business\bin\Jenkins\Molinos.DataAgro.Business.dll ..\Molinos.DataAgro.Entities\bin\Jenkins\Molinos.DataAgro.Entities.dll ..\Molinos.DataAgro.Interfaces\bin\Jenkins\Molinos.DataAgro.Interfaces.dll ..\Molinos.DataAgro.Mapping\bin\Jenkins\Molinos.DataAgro.Mapping.dll ..\Molinos.DataAgro.Report\bin\Jenkins\Molinos.DataAgro.Report.dll ..\WebDataAgro\bin\WebDataAgro.dll</GendarmeAssemblies>

    <OutputPackDir>..\Deploy\DeployPack</OutputPackDir>
    <OutputPackWebDir>..\Deploy\DeployPack\Web</OutputPackWebDir>
    
    <ZipDir>..\Deploy\**\*.zip</ZipDir>
    <CmdDir>..\Deploy\**\*.cmd</CmdDir>
    
    <!--<DeployParametersWeb>..\WebDataAgro\*.DeployParameters.xml</DeployParametersWeb>-->
    
    <!--<BatDir>..\Molinos.DataAgro.Build\DeployBat\*.bat</BatDir>-->
    
  </PropertyGroup>

</Project>