-- TRIGGER INSERT para ContactoComercial
CREATE TRIGGER [dbo].[trg_ContactoComercial_Insert]
ON [dbo].[ContactoComercial]
AFTER INSERT
AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO [dbo].[ContactoComercialAuditoria]
    (
        [ContactoComercialId],
        [ProveedorId],
        [Apellido],
        [Nombres],
        [CuitApoderado],
        [FechaDesde],
        [FechaHasta],
        [EsApoderado],
        [PuestoApoderadoId],
        [Puesto],
        [Telefono1],
        [TipoTelefono1Id],
        [Telefono2],
        [TipoTelefono2Id],
        [Telefono3],
        [TipoTelefono3Id],
        [Email1],
        [Email2],
        [Email3],
        [FechaNacimiento],
        [OtrosIntereses],
        [EsPrincipal],
        [Cargo],
        [CompraNet],
        [Cupo],
        [Boleto],
        [TipoOperacion],
        [UsuarioModificacion],
        [FechaModificacion],
        [ValoresNuevos]
    )
    SELECT
        i.[ContactoComercialId],
        i.[ProveedorId],
        i.[Apellido],
        i.[Nombres],
        i.[CuitApoderado],
        i.[FechaDesde],
        i.[FechaHasta],
        i.[EsApoderado],
        i.[PuestoApoderadoId],
        i.[Puesto],
        i.[Telefono1],
        i.[TipoTelefono1Id],
        i.[Telefono2],
        i.[TipoTelefono2Id],
        i.[Telefono3],
        i.[TipoTelefono3Id],
        i.[Email1],
        i.[Email2],
        i.[Email3],
        i.[FechaNacimiento],
        i.[OtrosIntereses],
        i.[EsPrincipal],
        i.[Cargo],
        i.[CompraNet],
        i.[Cupo],
        i.[Boleto],
        'INSERT',
        SYSTEM_USER,
        GETUTCDATE(),
        CONCAT(
            CASE WHEN i2.[ContactoComercialId] IS NOT NULL THEN 'ContactoComercialId: ' + CAST(i2.[ContactoComercialId] AS NVARCHAR(MAX)) + ', ' ELSE '' END,
            CASE WHEN i2.[ProveedorId] IS NOT NULL THEN 'ProveedorId: ' + CAST(i2.[ProveedorId] AS NVARCHAR(MAX)) + ', ' ELSE '' END,
            CASE WHEN i2.[Apellido] IS NOT NULL THEN 'Apellido: ' + i2.[Apellido] + ', ' ELSE '' END,
            CASE WHEN i2.[Nombres] IS NOT NULL THEN 'Nombres: ' + i2.[Nombres] + ', ' ELSE '' END,
            CASE WHEN i2.[CuitApoderado] IS NOT NULL THEN 'CuitApoderado: ' + i2.[CuitApoderado] + ', ' ELSE '' END,
            CASE WHEN i2.[FechaDesde] IS NOT NULL THEN 'FechaDesde: ' + CAST(i2.[FechaDesde] AS NVARCHAR(MAX)) + ', ' ELSE '' END,
            CASE WHEN i2.[FechaHasta] IS NOT NULL THEN 'FechaHasta: ' + CAST(i2.[FechaHasta] AS NVARCHAR(MAX)) + ', ' ELSE '' END,
            CASE WHEN i2.[EsApoderado] IS NOT NULL THEN 'EsApoderado: ' + CAST(i2.[EsApoderado] AS NVARCHAR(MAX)) + ', ' ELSE '' END,
            CASE WHEN i2.[PuestoApoderadoId] IS NOT NULL THEN 'PuestoApoderadoId: ' + CAST(i2.[PuestoApoderadoId] AS NVARCHAR(MAX)) + ', ' ELSE '' END,
            CASE WHEN i2.[Puesto] IS NOT NULL THEN 'Puesto: ' + i2.[Puesto] + ', ' ELSE '' END,
            CASE WHEN i2.[Telefono1] IS NOT NULL THEN 'Telefono1: ' + i2.[Telefono1] + ', ' ELSE '' END,
            CASE WHEN i2.[TipoTelefono1Id] IS NOT NULL THEN 'TipoTelefono1Id: ' + CAST(i2.[TipoTelefono1Id] AS NVARCHAR(MAX)) + ', ' ELSE '' END,
            CASE WHEN i2.[Telefono2] IS NOT NULL THEN 'Telefono2: ' + i2.[Telefono2] + ', ' ELSE '' END,
            CASE WHEN i2.[TipoTelefono2Id] IS NOT NULL THEN 'TipoTelefono2Id: ' + CAST(i2.[TipoTelefono2Id] AS NVARCHAR(MAX)) + ', ' ELSE '' END,
            CASE WHEN i2.[Telefono3] IS NOT NULL THEN 'Telefono3: ' + i2.[Telefono3] + ', ' ELSE '' END,
            CASE WHEN i2.[TipoTelefono3Id] IS NOT NULL THEN 'TipoTelefono3Id: ' + CAST(i2.[TipoTelefono3Id] AS NVARCHAR(MAX)) + ', ' ELSE '' END,
            CASE WHEN i2.[Email1] IS NOT NULL THEN 'Email1: ' + i2.[Email1] + ', ' ELSE '' END,
            CASE WHEN i2.[Email2] IS NOT NULL THEN 'Email2: ' + i2.[Email2] + ', ' ELSE '' END,
            CASE WHEN i2.[Email3] IS NOT NULL THEN 'Email3: ' + i2.[Email3] + ', ' ELSE '' END,
            CASE WHEN i2.[FechaNacimiento] IS NOT NULL THEN 'FechaNacimiento: ' + CAST(i2.[FechaNacimiento] AS NVARCHAR(MAX)) + ', ' ELSE '' END,
            CASE WHEN i2.[OtrosIntereses] IS NOT NULL THEN 'OtrosIntereses: ' + i2.[OtrosIntereses] + ', ' ELSE '' END,
            CASE WHEN i2.[EsPrincipal] IS NOT NULL THEN 'EsPrincipal: ' + CAST(i2.[EsPrincipal] AS NVARCHAR(MAX)) + ', ' ELSE '' END,
            CASE WHEN i2.[Cargo] IS NOT NULL THEN 'Cargo: ' + i2.[Cargo] + ', ' ELSE '' END,
            CASE WHEN i2.[CompraNet] IS NOT NULL THEN 'CompraNet: ' + CAST(i2.[CompraNet] AS NVARCHAR(MAX)) + ', ' ELSE '' END,
            CASE WHEN i2.[Cupo] IS NOT NULL THEN 'Cupo: ' + CAST(i2.[Cupo] AS NVARCHAR(MAX)) + ', ' ELSE '' END,
            CASE WHEN i2.[Boleto] IS NOT NULL THEN 'Boleto: ' + CAST(i2.[Boleto] AS NVARCHAR(MAX)) ELSE '' END
        )
    FROM inserted i
    CROSS APPLY (SELECT * FROM inserted i2 WHERE i2.ContactoComercialId = i.ContactoComercialId) i2;
END;
GO

-- TRIGGER UPDATE para ContactoComercial
CREATE TRIGGER [dbo].[trg_ContactoComercial_Update]
ON [dbo].[ContactoComercial]
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO [dbo].[ContactoComercialAuditoria]
    (
        [ContactoComercialId],
        [ProveedorId],
        [Apellido],
        [Nombres],
        [CuitApoderado],
        [FechaDesde],
        [FechaHasta],
        [EsApoderado],
        [PuestoApoderadoId],
        [Puesto],
        [Telefono1],
        [TipoTelefono1Id],
        [Telefono2],
        [TipoTelefono2Id],
        [Telefono3],
        [TipoTelefono3Id],
        [Email1],
        [Email2],
        [Email3],
        [FechaNacimiento],
        [OtrosIntereses],
        [EsPrincipal],
        [Cargo],
        [CompraNet],
        [Cupo],
        [Boleto],
        [TipoOperacion],
        [UsuarioModificacion],
        [FechaModificacion],
        [ValoresAnteriores],
        [ValoresNuevos]
    )
    SELECT
        i.[ContactoComercialId],
        i.[ProveedorId],
        i.[Apellido],
        i.[Nombres],
        i.[CuitApoderado],
        i.[FechaDesde],
        i.[FechaHasta],
        i.[EsApoderado],
        i.[PuestoApoderadoId],
        i.[Puesto],
        i.[Telefono1],
        i.[TipoTelefono1Id],
        i.[Telefono2],
        i.[TipoTelefono2Id],
        i.[Telefono3],
        i.[TipoTelefono3Id],
        i.[Email1],
        i.[Email2],
        i.[Email3],
        i.[FechaNacimiento],
        i.[OtrosIntereses],
        i.[EsPrincipal],
        i.[Cargo],
        i.[CompraNet],
        i.[Cupo],
        i.[Boleto],
        'UPDATE',
        SYSTEM_USER,
        GETUTCDATE(),
        CONCAT(
            CASE WHEN d2.[ContactoComercialId] IS NOT NULL THEN 'ContactoComercialId: ' + CAST(d2.[ContactoComercialId] AS NVARCHAR(MAX)) + ', ' ELSE '' END,
            CASE WHEN d2.[ProveedorId] IS NOT NULL THEN 'ProveedorId: ' + CAST(d2.[ProveedorId] AS NVARCHAR(MAX)) + ', ' ELSE '' END,
            CASE WHEN d2.[Apellido] IS NOT NULL THEN 'Apellido: ' + d2.[Apellido] + ', ' ELSE '' END,
            CASE WHEN d2.[Nombres] IS NOT NULL THEN 'Nombres: ' + d2.[Nombres] + ', ' ELSE '' END,
            CASE WHEN d2.[CuitApoderado] IS NOT NULL THEN 'CuitApoderado: ' + d2.[CuitApoderado] + ', ' ELSE '' END,
            CASE WHEN d2.[FechaDesde] IS NOT NULL THEN 'FechaDesde: ' + CAST(d2.[FechaDesde] AS NVARCHAR(MAX)) + ', ' ELSE '' END,
            CASE WHEN d2.[FechaHasta] IS NOT NULL THEN 'FechaHasta: ' + CAST(d2.[FechaHasta] AS NVARCHAR(MAX)) + ', ' ELSE '' END,
            CASE WHEN d2.[EsApoderado] IS NOT NULL THEN 'EsApoderado: ' + CAST(d2.[EsApoderado] AS NVARCHAR(MAX)) + ', ' ELSE '' END,
            CASE WHEN d2.[PuestoApoderadoId] IS NOT NULL THEN 'PuestoApoderadoId: ' + CAST(d2.[PuestoApoderadoId] AS NVARCHAR(MAX)) + ', ' ELSE '' END,
            CASE WHEN d2.[Puesto] IS NOT NULL THEN 'Puesto: ' + d2.[Puesto] + ', ' ELSE '' END,
            CASE WHEN d2.[Telefono1] IS NOT NULL THEN 'Telefono1: ' + d2.[Telefono1] + ', ' ELSE '' END,
            CASE WHEN d2.[TipoTelefono1Id] IS NOT NULL THEN 'TipoTelefono1Id: ' + CAST(d2.[TipoTelefono1Id] AS NVARCHAR(MAX)) + ', ' ELSE '' END,
            CASE WHEN d2.[Telefono2] IS NOT NULL THEN 'Telefono2: ' + d2.[Telefono2] + ', ' ELSE '' END,
            CASE WHEN d2.[TipoTelefono2Id] IS NOT NULL THEN 'TipoTelefono2Id: ' + CAST(d2.[TipoTelefono2Id] AS NVARCHAR(MAX)) + ', ' ELSE '' END,
            CASE WHEN d2.[Telefono3] IS NOT NULL THEN 'Telefono3: ' + d2.[Telefono3] + ', ' ELSE '' END,
            CASE WHEN d2.[TipoTelefono3Id] IS NOT NULL THEN 'TipoTelefono3Id: ' + CAST(d2.[TipoTelefono3Id] AS NVARCHAR(MAX)) + ', ' ELSE '' END,
            CASE WHEN d2.[Email1] IS NOT NULL THEN 'Email1: ' + d2.[Email1] + ', ' ELSE '' END,
            CASE WHEN d2.[Email2] IS NOT NULL THEN 'Email2: ' + d2.[Email2] + ', ' ELSE '' END,
            CASE WHEN d2.[Email3] IS NOT NULL THEN 'Email3: ' + d2.[Email3] + ', ' ELSE '' END,
            CASE WHEN d2.[FechaNacimiento] IS NOT NULL THEN 'FechaNacimiento: ' + CAST(d2.[FechaNacimiento] AS NVARCHAR(MAX)) + ', ' ELSE '' END,
            CASE WHEN d2.[OtrosIntereses] IS NOT NULL THEN 'OtrosIntereses: ' + d2.[OtrosIntereses] + ', ' ELSE '' END,
            CASE WHEN d2.[EsPrincipal] IS NOT NULL THEN 'EsPrincipal: ' + CAST(d2.[EsPrincipal] AS NVARCHAR(MAX)) + ', ' ELSE '' END,
            CASE WHEN d2.[Cargo] IS NOT NULL THEN 'Cargo: ' + d2.[Cargo] + ', ' ELSE '' END,
            CASE WHEN d2.[CompraNet] IS NOT NULL THEN 'CompraNet: ' + CAST(d2.[CompraNet] AS NVARCHAR(MAX)) + ', ' ELSE '' END,
            CASE WHEN d2.[Cupo] IS NOT NULL THEN 'Cupo: ' + CAST(d2.[Cupo] AS NVARCHAR(MAX)) + ', ' ELSE '' END,
            CASE WHEN d2.[Boleto] IS NOT NULL THEN 'Boleto: ' + CAST(d2.[Boleto] AS NVARCHAR(MAX)) ELSE '' END
        ),
        CONCAT(
            CASE WHEN i2.[ContactoComercialId] IS NOT NULL THEN 'ContactoComercialId: ' + CAST(i2.[ContactoComercialId] AS NVARCHAR(MAX)) + ', ' ELSE '' END,
            CASE WHEN i2.[ProveedorId] IS NOT NULL THEN 'ProveedorId: ' + CAST(i2.[ProveedorId] AS NVARCHAR(MAX)) + ', ' ELSE '' END,
            CASE WHEN i2.[Apellido] IS NOT NULL THEN 'Apellido: ' + i2.[Apellido] + ', ' ELSE '' END,
            CASE WHEN i2.[Nombres] IS NOT NULL THEN 'Nombres: ' + i2.[Nombres] + ', ' ELSE '' END,
            CASE WHEN i2.[CuitApoderado] IS NOT NULL THEN 'CuitApoderado: ' + i2.[CuitApoderado] + ', ' ELSE '' END,
            CASE WHEN i2.[FechaDesde] IS NOT NULL THEN 'FechaDesde: ' + CAST(i2.[FechaDesde] AS NVARCHAR(MAX)) + ', ' ELSE '' END,
            CASE WHEN i2.[FechaHasta] IS NOT NULL THEN 'FechaHasta: ' + CAST(i2.[FechaHasta] AS NVARCHAR(MAX)) + ', ' ELSE '' END,
            CASE WHEN i2.[EsApoderado] IS NOT NULL THEN 'EsApoderado: ' + CAST(i2.[EsApoderado] AS NVARCHAR(MAX)) + ', ' ELSE '' END,
            CASE WHEN i2.[PuestoApoderadoId] IS NOT NULL THEN 'PuestoApoderadoId: ' + CAST(i2.[PuestoApoderadoId] AS NVARCHAR(MAX)) + ', ' ELSE '' END,
            CASE WHEN i2.[Puesto] IS NOT NULL THEN 'Puesto: ' + i2.[Puesto] + ', ' ELSE '' END,
            CASE WHEN i2.[Telefono1] IS NOT NULL THEN 'Telefono1: ' + i2.[Telefono1] + ', ' ELSE '' END,
            CASE WHEN i2.[TipoTelefono1Id] IS NOT NULL THEN 'TipoTelefono1Id: ' + CAST(i2.[TipoTelefono1Id] AS NVARCHAR(MAX)) + ', ' ELSE '' END,
            CASE WHEN i2.[Telefono2] IS NOT NULL THEN 'Telefono2: ' + i2.[Telefono2] + ', ' ELSE '' END,
            CASE WHEN i2.[TipoTelefono2Id] IS NOT NULL THEN 'TipoTelefono2Id: ' + CAST(i2.[TipoTelefono2Id] AS NVARCHAR(MAX)) + ', ' ELSE '' END,
            CASE WHEN i2.[Telefono3] IS NOT NULL THEN 'Telefono3: ' + i2.[Telefono3] + ', ' ELSE '' END,
            CASE WHEN i2.[TipoTelefono3Id] IS NOT NULL THEN 'TipoTelefono3Id: ' + CAST(i2.[TipoTelefono3Id] AS NVARCHAR(MAX)) + ', ' ELSE '' END,
            CASE WHEN i2.[Email1] IS NOT NULL THEN 'Email1: ' + i2.[Email1] + ', ' ELSE '' END,
            CASE WHEN i2.[Email2] IS NOT NULL THEN 'Email2: ' + i2.[Email2] + ', ' ELSE '' END,
            CASE WHEN i2.[Email3] IS NOT NULL THEN 'Email3: ' + i2.[Email3] + ', ' ELSE '' END,
            CASE WHEN i2.[FechaNacimiento] IS NOT NULL THEN 'FechaNacimiento: ' + CAST(i2.[FechaNacimiento] AS NVARCHAR(MAX)) + ', ' ELSE '' END,
            CASE WHEN i2.[OtrosIntereses] IS NOT NULL THEN 'OtrosIntereses: ' + i2.[OtrosIntereses] + ', ' ELSE '' END,
            CASE WHEN i2.[EsPrincipal] IS NOT NULL THEN 'EsPrincipal: ' + CAST(i2.[EsPrincipal] AS NVARCHAR(MAX)) + ', ' ELSE '' END,
            CASE WHEN i2.[Cargo] IS NOT NULL THEN 'Cargo: ' + i2.[Cargo] + ', ' ELSE '' END,
            CASE WHEN i2.[CompraNet] IS NOT NULL THEN 'CompraNet: ' + CAST(i2.[CompraNet] AS NVARCHAR(MAX)) + ', ' ELSE '' END,
            CASE WHEN i2.[Cupo] IS NOT NULL THEN 'Cupo: ' + CAST(i2.[Cupo] AS NVARCHAR(MAX)) + ', ' ELSE '' END,
            CASE WHEN i2.[Boleto] IS NOT NULL THEN 'Boleto: ' + CAST(i2.[Boleto] AS NVARCHAR(MAX)) ELSE '' END
        )
    FROM inserted i
    CROSS APPLY (SELECT * FROM inserted i2 WHERE i2.ContactoComercialId = i.ContactoComercialId) i2
    CROSS APPLY (SELECT * FROM deleted d2 WHERE d2.ContactoComercialId = i.ContactoComercialId) d2;
END;
GO

-- TRIGGER DELETE para ContactoComercial
CREATE TRIGGER [dbo].[trg_ContactoComercial_Delete]
ON [dbo].[ContactoComercial]
AFTER DELETE
AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO [dbo].[ContactoComercialAuditoria]
    (
        [ContactoComercialId],
        [ProveedorId],
        [Apellido],
        [Nombres],
        [CuitApoderado],
        [FechaDesde],
        [FechaHasta],
        [EsApoderado],
        [PuestoApoderadoId],
        [Puesto],
        [Telefono1],
        [TipoTelefono1Id],
        [Telefono2],
        [TipoTelefono2Id],
        [Telefono3],
        [TipoTelefono3Id],
        [Email1],
        [Email2],
        [Email3],
        [FechaNacimiento],
        [OtrosIntereses],
        [EsPrincipal],
        [Cargo],
        [CompraNet],
        [Cupo],
        [Boleto],
        [TipoOperacion],
        [UsuarioModificacion],
        [FechaModificacion],
        [ValoresAnteriores]
    )
    SELECT
        d.[ContactoComercialId],
        d.[ProveedorId],
        d.[Apellido],
        d.[Nombres],
        d.[CuitApoderado],
        d.[FechaDesde],
        d.[FechaHasta],
        d.[EsApoderado],
        d.[PuestoApoderadoId],
        d.[Puesto],
        d.[Telefono1],
        d.[TipoTelefono1Id],
        d.[Telefono2],
        d.[TipoTelefono2Id],
        d.[Telefono3],
        d.[TipoTelefono3Id],
        d.[Email1],
        d.[Email2],
        d.[Email3],
        d.[FechaNacimiento],
        d.[OtrosIntereses],
        d.[EsPrincipal],
        d.[Cargo],
        d.[CompraNet],
        d.[Cupo],
        d.[Boleto],
        'DELETE',
        SYSTEM_USER,
        GETUTCDATE(),
        CONCAT(
            CASE WHEN d2.[ContactoComercialId] IS NOT NULL THEN 'ContactoComercialId: ' + CAST(d2.[ContactoComercialId] AS NVARCHAR(MAX)) + ', ' ELSE '' END,
            CASE WHEN d2.[ProveedorId] IS NOT NULL THEN 'ProveedorId: ' + CAST(d2.[ProveedorId] AS NVARCHAR(MAX)) + ', ' ELSE '' END,
            CASE WHEN d2.[Apellido] IS NOT NULL THEN 'Apellido: ' + d2.[Apellido] + ', ' ELSE '' END,
            CASE WHEN d2.[Nombres] IS NOT NULL THEN 'Nombres: ' + d2.[Nombres] + ', ' ELSE '' END,
            CASE WHEN d2.[CuitApoderado] IS NOT NULL THEN 'CuitApoderado: ' + d2.[CuitApoderado] + ', ' ELSE '' END,
            CASE WHEN d2.[FechaDesde] IS NOT NULL THEN 'FechaDesde: ' + CAST(d2.[FechaDesde] AS NVARCHAR(MAX)) + ', ' ELSE '' END,
            CASE WHEN d2.[FechaHasta] IS NOT NULL THEN 'FechaHasta: ' + CAST(d2.[FechaHasta] AS NVARCHAR(MAX)) + ', ' ELSE '' END,
            CASE WHEN d2.[EsApoderado] IS NOT NULL THEN 'EsApoderado: ' + CAST(d2.[EsApoderado] AS NVARCHAR(MAX)) + ', ' ELSE '' END,
            CASE WHEN d2.[PuestoApoderadoId] IS NOT NULL THEN 'PuestoApoderadoId: ' + CAST(d2.[PuestoApoderadoId] AS NVARCHAR(MAX)) + ', ' ELSE '' END,
            CASE WHEN d2.[Puesto] IS NOT NULL THEN 'Puesto: ' + d2.[Puesto] + ', ' ELSE '' END,
            CASE WHEN d2.[Telefono1] IS NOT NULL THEN 'Telefono1: ' + d2.[Telefono1] + ', ' ELSE '' END,
            CASE WHEN d2.[TipoTelefono1Id] IS NOT NULL THEN 'TipoTelefono1Id: ' + CAST(d2.[TipoTelefono1Id] AS NVARCHAR(MAX)) + ', ' ELSE '' END,
            CASE WHEN d2.[Telefono2] IS NOT NULL THEN 'Telefono2: ' + d2.[Telefono2] + ', ' ELSE '' END,
            CASE WHEN d2.[TipoTelefono2Id] IS NOT NULL THEN 'TipoTelefono2Id: ' + CAST(d2.[TipoTelefono2Id] AS NVARCHAR(MAX)) + ', ' ELSE '' END,
            CASE WHEN d2.[Telefono3] IS NOT NULL THEN 'Telefono3: ' + d2.[Telefono3] + ', ' ELSE '' END,
            CASE WHEN d2.[TipoTelefono3Id] IS NOT NULL THEN 'TipoTelefono3Id: ' + CAST(d2.[TipoTelefono3Id] AS NVARCHAR(MAX)) + ', ' ELSE '' END,
            CASE WHEN d2.[Email1] IS NOT NULL THEN 'Email1: ' + d2.[Email1] + ', ' ELSE '' END,
            CASE WHEN d2.[Email2] IS NOT NULL THEN 'Email2: ' + d2.[Email2] + ', ' ELSE '' END,
            CASE WHEN d2.[Email3] IS NOT NULL THEN 'Email3: ' + d2.[Email3] + ', ' ELSE '' END,
            CASE WHEN d2.[FechaNacimiento] IS NOT NULL THEN 'FechaNacimiento: ' + CAST(d2.[FechaNacimiento] AS NVARCHAR(MAX)) + ', ' ELSE '' END,
            CASE WHEN d2.[OtrosIntereses] IS NOT NULL THEN 'OtrosIntereses: ' + d2.[OtrosIntereses] + ', ' ELSE '' END,
            CASE WHEN d2.[EsPrincipal] IS NOT NULL THEN 'EsPrincipal: ' + CAST(d2.[EsPrincipal] AS NVARCHAR(MAX)) + ', ' ELSE '' END,
            CASE WHEN d2.[Cargo] IS NOT NULL THEN 'Cargo: ' + d2.[Cargo] + ', ' ELSE '' END,
            CASE WHEN d2.[CompraNet] IS NOT NULL THEN 'CompraNet: ' + CAST(d2.[CompraNet] AS NVARCHAR(MAX)) + ', ' ELSE '' END,
            CASE WHEN d2.[Cupo] IS NOT NULL THEN 'Cupo: ' + CAST(d2.[Cupo] AS NVARCHAR(MAX)) + ', ' ELSE '' END,
            CASE WHEN d2.[Boleto] IS NOT NULL THEN 'Boleto: ' + CAST(d2.[Boleto] AS NVARCHAR(MAX)) ELSE '' END
        )
    FROM deleted d
    CROSS APPLY (SELECT * FROM deleted d2 WHERE d2.ContactoComercialId = d.ContactoComercialId) d2;
END;
GO
