CREATE TABLE [dbo].[AdministracionCupo] (
    [Id]              INT           IDENTITY (1, 1) NOT NULL,    
    [ProveedorId]              INT           NULL,
    [ComercialId]              INT           NULL,
    [CantidadCupo]            INT           NULL,
    [Fecha]                    DATETIME      NULL,
	[CantidadFleteProcedencia]            INT           NULL,
	[EstadoId]   INT NULL,
	[CentroId]              INT           NULL,
    [ZonaId]              INT           NULL,
    [MaterialId]              INT           NULL,
	[Excedente]   BIT NULL,
    CONSTRAINT [PK_AdministracionCupo] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_AdministracionCupo_Comercial] FOREIGN KEY ([ComercialId]) REFERENCES [dbo].[Comercial] ([ComercialId]),
    CONSTRAINT [FK_AdministracionCupo_Proveedor] FOREIGN KEY ([ProveedorId]) REFERENCES [dbo].[Proveedor] ([ProveedorId]),
    CONSTRAINT [FK_AdministracionCupo_Centro] FOREIGN KEY ([CentroId]) REFERENCES [dbo].[Centro] ([Id]),
    CONSTRAINT [FK_AdministracionCupo_Zona] FOREIGN KEY ([ZonaId]) REFERENCES [dbo].[ZonaCupo] ([Id]),
    CONSTRAINT [FK_AdministracionCupo_Material] FOREIGN KEY ([MaterialId]) REFERENCES [dbo].[Material] ([MaterialId]),
);
