CREATE TABLE [dbo].[AdministracionCupo] (
    [Id]              INT           IDENTITY (1, 1) NOT NULL,    
    [ProveedorId]              INT           NULL,
    [ComercialId]              INT           NULL,
    [CantidadCupo]            INT           NULL,
    [Fecha]                    DATETIME      NULL,
	[CantidadFleteProcedencia]            INT           NULL,
	[EstadoId]   INT NULL,
	[CentroId]              INT           NULL,
    [ZonaId]              INT           NULL,
    [MaterialId]              INT           NULL,
	[Excedente]   BIT NULL,
    [TipoAdministracionCupoId] INT NOT NULL DEFAULT 1, 
    [Fason] BIT NULL, 
    [Destinatario] VARCHAR(50) NULL, 
    [ComercialCreadorId] INT NULL, 
    [FechaCreacion] DATETIME NULL, 
    [Observacion] VARCHAR(500) NULL, 
    [SugerenciaCupoId] INT NULL, 
    [Calidad] VARCHAR(50) NULL, 
    [FechaDecision] DATETIME NULL, 
    [ConDescarga] BIT NULL, 
    [Motivo] VARCHAR(2000) NULL, 
    [Sustentable] BIT NULL,
    [EPA] BIT NULL,
    [NegocioId] INT NULL,
    CONSTRAINT [PK_AdministracionCupo] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_AdministracionCupo_Comercial] FOREIGN KEY ([ComercialId]) REFERENCES [dbo].[Comercial] ([ComercialId]),
    CONSTRAINT [FK_AdministracionCupo_Proveedor] FOREIGN KEY ([ProveedorId]) REFERENCES [dbo].[Proveedor] ([ProveedorId]),
    CONSTRAINT [FK_AdministracionCupo_Centro] FOREIGN KEY ([CentroId]) REFERENCES [dbo].[Centro] ([Id]),
    CONSTRAINT [FK_AdministracionCupo_Zona] FOREIGN KEY ([ZonaId]) REFERENCES [dbo].[ZonaCupo] ([Id]),
    CONSTRAINT [FK_AdministracionCupo_Material] FOREIGN KEY ([MaterialId]) REFERENCES [dbo].[Material] ([MaterialId]),
    CONSTRAINT [FK_AdministracionCupo_TipoAdministracionCupo] FOREIGN KEY ([TipoAdministracionCupoId]) REFERENCES [dbo].[TipoAdministracionCupo] ([Id]),
    CONSTRAINT [FK_AdministracionCupo_Sugerencia] FOREIGN KEY ([SugerenciaCupoId]) REFERENCES [dbo].[SugerenciaCupo] ([Id]),
	CONSTRAINT [FK_AdministracionCupo_Negocio] FOREIGN KEY (NegocioId) REFERENCES [Negocio]([Id]),
);
