CREATE TABLE [dbo].[CampanaMaterialDetallePorMes] (
    [Id] INT        IDENTITY (1, 1) NOT NULL,
	[Contrato]       VARCHAR(MAX)        NULL, 
	[CorredorCuit]   VARCHAR(MAX) NULL,
    [Fecha]                     DATETIME        NULL,
    [PendienteAplicar]               FLOAT      NULL,
	[PendienteAFijar]               FLOAT      NULL,
	[ToneladaAmpliada]               FLOAT      NULL,
	[ToneladaAnulada]               FLOAT      NULL,
	[ToneladaAplicada]               FLOAT      NULL,
	[ToneladaContrato]               FLOAT      NULL,
	[ToneladaFijada]               FLOAT      NULL,
	[ClaseDoc]       VARCHAR(MAX)        NULL, 
	[Clasificacion]       VARCHAR(MAX)        NULL, 
    [CampanaMaterialDetalleId]       INT        NULL,    
    [ComercialId]             INT        NULL,
    [CorredorId] INT NULL, 
	[CampanaId]          INT        NOT NULL,
	[CampanaSAPId]          INT        NOT NULL DEFAULT 7,
    [ProveedorId]        INT        NULL,
    [MaterialId]         INT        NOT NULL,
    [FechaDesde] DATETIME NULL, 
    [FechaHasta] DATETIME NULL, 
    [CampanaDesc] VARCHAR(9) NULL, 
    CONSTRAINT [PK_CampanaMaterialDetallePorMes] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_CampanaMaterialDetallePorMes_Contacto] FOREIGN KEY ([CorredorId]) REFERENCES [dbo].[Proveedor] ([ProveedorId]),
	CONSTRAINT [FK_CampanaMaterialDetallePorMes_Comercial] FOREIGN KEY ([ComercialId]) REFERENCES [Comercial]([ComercialId]),
	CONSTRAINT [FK_CampanaMaterialDetallePorMes_Campana] FOREIGN KEY ([CampanaId]) REFERENCES [dbo].[Campaña] ([CampañaId]),
	CONSTRAINT [FK_CampanaMaterialDetallePorMes_CampanaSAP] FOREIGN KEY ([CampanaSAPId]) REFERENCES [dbo].[Campaña] ([CampañaId]),
    CONSTRAINT [FK_CampanaMaterialDetallePorMes_Proveedor] FOREIGN KEY ([ProveedorId]) REFERENCES [dbo].[Proveedor] ([ProveedorId]),
    CONSTRAINT [FK_CampanaMaterialDetallePorMes_Material] FOREIGN KEY ([MaterialId]) REFERENCES [dbo].[Material] ([MaterialId])
);

