CREATE TABLE [dbo].[Configuracion] (
    [Id] INT IDENTITY (1, 1) NOT NULL,
    [CantidadDias] INT NULL DEFAULT 120,
    [ClaveStop] VARCHAR(MAX) NULL DEFAULT '429DAC12-3BDC-6CC4-1A97-AD759F936E1B',
    [ConexionABMStop] BIT NULL DEFAULT 1,
    [ConexionConsultaStop] BIT NULL DEFAULT 1, 
    [TerminalStopId] INT NULL DEFAULT 12,
    [CuitDestinoStop] VARCHAR(MAX) NULL DEFAULT '20005894582',
    [CodigoLocalidadStop] INT NULL DEFAULT 18794, 
    [ImporteSustentable] DECIMAL(11, 2) NULL DEFAULT 8, 
    [ContratoAperturaPrecioPorcentajeDeComisionMaximo] DECIMAL(11, 2) NULL DEFAULT 3, 
    [DiasDiferimiento] INT NULL DEFAULT 120, 
    [CantidadAcuerdo] INT NULL DEFAULT 30000, 
    [CantidadDiasDolarizadoLimiteMaximo] INT NULL DEFAULT 120, 
    [CantidadMaxima] INT NULL DEFAULT 15000000, 
    [CantidadDiasPesificadoLimite] INT NULL DEFAULT 120, 
    [RedespachoMaximoUSDM] INT NULL DEFAULT 60, 
    [RedespachoMaximoARP] INT NULL DEFAULT 1000, 
    [ToleranciaPaseMin] INT NULL DEFAULT 10, 
    [ToleranciaPaseMax] INT NULL DEFAULT 10, 
    [ImporteSustentableEspecial] DECIMAL(11, 2) NULL DEFAULT 20, 
    [AlgoritmoKilosMinimosParaSugerencia] INT NOT NULL DEFAULT 20000, 
    [AlgoritmoProcMaxSugerenciasProveedorDia] INT NOT NULL DEFAULT 30, 
    [Actualizacion] INT NULL DEFAULT 30000, 
    [ApiKeyBolsaRosario] VARCHAR(500) DEFAULT 'D0DBE53F-0B11-EA11-9428-00155D09A724' NOT NULL,
    [SecretBolsaRosario] VARCHAR(500) DEFAULT '3b22d031fcf1a3d5ee52626c00be2d73eaa331d8b86a35b1ab12ec0895d6d842' NOT NULL,
    [MinutosCronometroConDescarga] INT NULL DEFAULT 2,
    [CantidadMaximaDiasNegocioConDescarga] INT NULL DEFAULT 15,
    [PorcentajeVolumenNegocioConDescarga] INT NULL DEFAULT 30,
    [ActivarLogDebug] BIT NULL DEFAULT 1,
    [ExigirNegocioEnSolExt] BIT NULL DEFAULT 0,
    [ApiKeyScoringCupos] VARCHAR(500) DEFAULT 'iYr0s8Bm9p2iHZAqOrEYt2836ep61wFM3CGki4hp' NOT NULL,
    CONSTRAINT [PK_Configuracion] PRIMARY KEY CLUSTERED ([Id] ASC),
);