CREATE TABLE [dbo].[ContactoComercial] (
    [ContactoComercialId] INT             IDENTITY (1, 1) NOT NULL,
    [ProveedorId]         INT             NOT NULL,
    [Apellido]            VARCHAR (50)    NOT NULL,
    [Nombres]             VARCHAR (50)    NOT NULL,
    [Puesto]              VARCHAR (50)    NULL,
    [Telefono1]           VARCHAR (100)   NULL,
    [TipoTelefono1Id]     INT             NULL,
    [Telefono2]           VARCHAR (100)   NULL,
    [TipoTelefono2Id]     INT             NULL,
    [Telefono3]           VARCHAR (100)   NULL,
    [TipoTelefono3Id]     INT             NULL,
    [Email1]              VARCHAR (100)   NULL,
    [Email2]              VARCHAR (100)   NULL,
    [Email3]              VARCHAR (100)   NULL,
    [FechaNacimiento]     DATETIME        NULL,
    [CategoriaId]         INT             NULL,
    [OtrosIntereses]      NVARCHAR (255)  NULL,
    [EsPrincipal]         BIT             NULL,
    [Cargo]               VARCHAR (100)   NULL,
	[CompraNet]			  BIT			  NULL,
    CONSTRAINT [PK_ContactoComercial] PRIMARY KEY CLUSTERED ([ContactoComercialId] ASC),
    CONSTRAINT [FK_ContactoComercial_Proveedor] FOREIGN KEY ([ProveedorId]) REFERENCES [dbo].[Proveedor] ([ProveedorId])
);

