CREATE TABLE [dbo].[Contrato]
(
	[ContratoId] INT NOT NULL PRIMARY KEY IDENTITY, 
    [MaterialId] INT NOT NULL , 
    [TipoNegocioId] INT NOT NULL, 
    [Cantidad] FLOAT NOT NULL, 
    [Precio] DECIMAL(11, 2) NOT NULL, 
    [FechaEntrega] DATETIME NOT NULL, 
    [CampañaId] INT NOT NULL, 
    [FechaDesde] DATETIME NOT NULL, 
    [FechaHasta] DATETIME NOT NULL, 
    [ProveedorId] INT NOT NULL, 
    [MonedaId] CHAR(5) NOT NULL, 
    [Fecha] DATETIME NOT NULL, 
    [GrupoCompra] INT NOT NULL, 
    [ComercialId] INT NULL, 
	[ProvinciaId] INT NULL,
    [LocalidadId] INT NULL, 
    [Base] BIT NULL, 
    [Importe_Sustentable] DECIMAL(11, 2) NULL, 
	[MonedaId_Sustentable] CHAR(5) NULL, 
	[Fecha_Dolarizado] DATETIME NULL,  
	[Dias_Pesificado] INT NULL,  
    [NoInformaSIO] BIT NULL, 
    [TrigoEspecial] BIT NULL, 
    [Estado] INT NOT NULL, 
    [UsuarioId] VARCHAR(100) NULL
    
    CONSTRAINT [FK_Contrato_TipoNegocio] FOREIGN KEY ([TipoNegocioId]) REFERENCES [TipoNegocio]([TipoNegocioId]) DEFAULT 1, 
    [ContratoSAP] INT NULL, 
    [Ampliaciones] FLOAT NULL, 
    [Observacion] NVARCHAR(MAX) NULL, 
    CONSTRAINT [FK_Contrato_Campaña] FOREIGN KEY ([CampañaId]) REFERENCES [Campaña]([CampañaId]), 
    CONSTRAINT [FK_Contrato_Proveedor] FOREIGN KEY ([ProveedorId]) REFERENCES [Proveedor]([ProveedorId]), 
    CONSTRAINT [FK_Contrato_Moneda] FOREIGN KEY ([MonedaId]) REFERENCES [Monedas]([MonedaId]), 
    CONSTRAINT [FK_Contrato_Comercial] FOREIGN KEY ([ComercialId]) REFERENCES [Comercial]([ComercialId]), 
    CONSTRAINT [FK_Contrato_Localidad] FOREIGN KEY ([LocalidadId]) REFERENCES [Localidad]([LocalidadId]), 
    CONSTRAINT [FK_Contrato_EstadoContrato] FOREIGN KEY (Estado) REFERENCES [EstadoContrato]([EstadoContratoId]),
    CONSTRAINT [FK_Es_Localidad] FOREIGN KEY ([LocalidadId]) REFERENCES [Localidad]([LocalidadId])  
)
