CREATE TABLE [dbo].[Contrato]
(
	[ContratoId] INT NOT NULL PRIMARY KEY IDENTITY (1, 1), 
    [MaterialId] INT NOT NULL , 
    [TipoNegocioId] INT NOT NULL DEFAULT 1, 
    [Cantidad] FLOAT NOT NULL, 
    [Precio] DECIMAL(11, 2) NOT NULL, 
    [FechaEntrega] DATETIME NOT NULL, 
    [CampanaId] INT NOT NULL, 
    [FechaDesde] DATETIME NOT NULL, 
    [FechaHasta] DATETIME NOT NULL, 
    [ProveedorId] INT NOT NULL, 
    [MonedaId] CHAR(5) NOT NULL, 
    [Fecha] DATETIME NOT NULL, 
    [GrupoCompra] INT NOT NULL, 
    [ComercialId] INT NULL, 
	[ProvinciaId] INT NULL,
    [LocalidadId] INT NULL, 
    [Base] BIT NULL, 
    ImporteSustentable DECIMAL(11, 2) NULL, 
	MonedaSustentableId CHAR(5) NULL, 
	FechaDolarizado DATETIME NULL,  
	DiasPesificado INT NULL,  
    [NoInformaSIO] BIT NULL, 
    [TrigoEspecial] BIT NULL, 
    [EstadoId] INT NOT NULL, 
    [UsuarioId] VARCHAR(100) NULL,
    [ContratoSAP] INT NULL, 
    [Ampliaciones] FLOAT NULL, 
	[ClasificacionId] INT DEFAULT 1 NOT NULL,  
    [Observacion] NVARCHAR(MAX) NULL,
	DestinoId INT DEFAULT 1 NOT NULL,
	CantidadCamiones INT NULL,
	Consignatario BIT NULL,
	PlanCanje BIT NULL,
	CondicionFijacionId INT NULL,
	CD BIT NULL,
	Warrant BIT NULL,
	PagoDirectoVendedor BIT NULL,
	StandardDeCalidadId INT NULL,
	CalidadEspecialId INT NULL,
	ValorCalidadEspecial DECIMAL(11, 2) NULL,
	EstablecimientoPropio BIT NULL,
	[BoletoId] INT DEFAULT 3 NOT NULL,  
	[BolsaId] INT NULL,
	[DesdeFijacion] DATETIME NULL,
	[HastaFijacion] DATETIME NULL

    CONSTRAINT [FK_Contrato_TipoNegocio] FOREIGN KEY ([TipoNegocioId]) REFERENCES [TipoNegocio]([TipoNegocioId]), 
    CONSTRAINT [FK_Contrato_Campaña] FOREIGN KEY ([CampanaId]) REFERENCES [Campaña]([CampañaId]), 
    CONSTRAINT [FK_Contrato_Proveedor] FOREIGN KEY ([ProveedorId]) REFERENCES [Proveedor]([ProveedorId]), 
    CONSTRAINT [FK_Contrato_Moneda] FOREIGN KEY ([MonedaId]) REFERENCES [Moneda]([MonedaId]), 
    CONSTRAINT [FK_Contrato_Comercial] FOREIGN KEY ([ComercialId]) REFERENCES [Comercial]([ComercialId]), 
    CONSTRAINT [FK_Contrato_Localidad] FOREIGN KEY ([LocalidadId]) REFERENCES [Localidad]([LocalidadId]), 
    CONSTRAINT [FK_Contrato_EstadoContrato] FOREIGN KEY (EstadoId) REFERENCES [EstadoContrato]([EstadoContratoId]),
    CONSTRAINT [FK_Es_Localidad] FOREIGN KEY ([LocalidadId]) REFERENCES [Localidad]([LocalidadId]), 
	CONSTRAINT [FK_Contrato_ClasificacionCompraNet] FOREIGN KEY ([ClasificacionId]) REFERENCES [ClasificacionCompraNet]([Id]), 
	CONSTRAINT [FK_Contrato_BoletoCompraNet] FOREIGN KEY ([BoletoId]) REFERENCES [BoletoCompraNet]([Id]),	
	CONSTRAINT [FK_Contrato_BolsaCompraNet] FOREIGN KEY ([BolsaId]) REFERENCES [BolsaCompraNet]([Id]),
    CONSTRAINT [FK_Contrato_Destino] FOREIGN KEY ([DestinoId]) REFERENCES [Centro](Id),
    CONSTRAINT [FK_Contrato_CondicionFijacion] FOREIGN KEY ([CondicionFijacionId]) REFERENCES [CondicionFijacion]([Id]), 
    CONSTRAINT [FK_Contrato_StandardDeCalidad] FOREIGN KEY (StandardDeCalidadId) REFERENCES [StandardDeCalidad](Id),
	CONSTRAINT [FK_Contrato_CalidadEspecial] FOREIGN KEY ([CalidadEspecialId]) REFERENCES [CalidadEspecial]([Id]), 
)
