CREATE TABLE [dbo].[Cupo]
(
	[Id]					INT NOT NULL IDENTITY (1, 1), 
    [ProveedorId]			INT NOT NULL, 
    [CentroId]				INT NOT NULL,
    [MaterialId]			INT NOT NULL,
	[FechaIngreso]			DATETIME NOT NULL, 
    [CupoSap]				VARCHAR(20) NOT NULL, 
	[ZonaCupoId]			INT NOT NULL,
    [ComercialId]			INT NULL, 
    [FleteProcedencia]		BIT NULL,
	[Calidad]				VARCHAR(20) NULL,
	[Observaciones]			VARCHAR(255) NULL,
	[Fason]					BIT NULL,
	[Destinatario]			VARCHAR(20) NULL,
    [FechaGeneracion]		DATETIME NOT NULL, 
	[EstadoCupoId]			INT NOT NULL DEFAULT 1,
	[CupoStop]				INT NULL,
	[CreacionStop]			VARCHAR(50) NULL,
	[ErrorStop]				VARCHAR(MAX) NULL,

    [FasonId] INT NULL, 
    [ContratoId] INT NULL, 
    [AgenteCompraId] INT NULL, 
    [FijacionDePrecioContratoId] INT NULL, 
    [TipoNegocioId] INT NULL , 
    [ConfiguracionEspacioDinamicoId] INT NULL, 
    CONSTRAINT [PK_Cupo] PRIMARY KEY CLUSTERED ([Id] ASC),
	CONSTRAINT [FK_Cupo_Proveedor] FOREIGN KEY ([ProveedorId]) REFERENCES [Proveedor]([ProveedorId]), 
    CONSTRAINT [FK_Cupo_Centro] FOREIGN KEY (CentroId) REFERENCES [Centro]([Id]),
    CONSTRAINT [FK_Cupo_Material] FOREIGN KEY (MaterialId) REFERENCES [Material]([MaterialId]),
    CONSTRAINT [FK_Cupo_Comercial] FOREIGN KEY ([ComercialId]) REFERENCES [Comercial]([ComercialId]), 
    CONSTRAINT [FK_Cupo_ZonaCupo] FOREIGN KEY (ZonaCupoId) REFERENCES [ZonaCupo]([Id]),
    CONSTRAINT [FK_Cupo_EstadoCupo] FOREIGN KEY (estadoCupoId) REFERENCES [EstadoCupo]([Id]),
    CONSTRAINT [FK_Cupo_Fason] FOREIGN KEY (FasonId) REFERENCES [Fason]([Id]),
    CONSTRAINT [FK_Cupo_Contrato] FOREIGN KEY (ContratoId) REFERENCES [Contrato]([ContratoId]),
    CONSTRAINT [FK_Cupo_FijacionDePrecioContrato] FOREIGN KEY (FijacionDePrecioContratoId) REFERENCES [FijacionDePrecioContrato]([FijacionDePrecioContratoId]),
    CONSTRAINT [FK_Cupo_AgenteCompra] FOREIGN KEY (AgenteCompraId) REFERENCES [AgenteCompra]([Id]),
    CONSTRAINT [FK_Cupo_TipoNegocio] FOREIGN KEY (TipoNegocioId) REFERENCES [TipoNegocio]([TipoNegocioId]),
    CONSTRAINT [FK_Cupo_ConfiguracionEspacioDinamico] FOREIGN KEY (ConfiguracionEspacioDinamicoId) REFERENCES [ConfiguracionEspacioDinamico]([Id]),
	
)
