CREATE TABLE [dbo].[Cupo]
(
    [Id]					INT NOT NULL IDENTITY (1, 1), 
    [ProveedorId]			INT NOT NULL, 
    [CentroId]				INT NOT NULL,
    [MaterialId]			INT NOT NULL,
    [FechaIngreso]			DATETIME NOT NULL, 
    [CupoSap]				VARCHAR(50) NULL, 
    [ZonaCupoId]			INT NOT NULL,
    [ComercialId]			INT NULL, 
    [FleteProcedencia]		BIT NULL,
    [Calidad]				VARCHAR(20) NULL,
    [Observaciones]			VARCHAR(255) NULL,
    [Fason]					BIT NULL,
    [Destinatario]			VARCHAR(20) NULL,
    [FechaGeneracion]		DATETIME NOT NULL, 
    [EstadoCupoId]			INT NOT NULL DEFAULT 1,
    [CupoStop]				INT NULL,
    [CreacionStop]			VARCHAR(50) NULL,
    [ErrorStop]				VARCHAR(MAX) NULL,

    [TipoNegocioId] INT NULL , 
    [ConfiguracionEspacioDinamicoId] INT NULL, 
    [NegocioId] INT NULL, 
    [UsuarioCreador] varchar(100) NULL, 
    [MotivoRechazo] VARCHAR(MAX) NULL, 
    [EstadoPlanta] NVARCHAR(MAX) NULL, 
    [CartaPorte] NVARCHAR(MAX) NULL, 
    [CTG] NVARCHAR(MAX) NULL, 
    [CTGFechaDesde] DATETIME NULL, 
    [CTGFechaHasta] DATETIME NULL, 
    [CuitOrigen] NVARCHAR(MAX) NULL, 
    [RemitenteComercial] NVARCHAR(MAX) NULL, 
    [CorredorComprador] NVARCHAR(MAX) NULL, 
    [MercadoATermino] NVARCHAR(MAX) NULL, 
    [Cosecha] NVARCHAR(MAX) NULL, 
    [Peso] NVARCHAR(MAX) NULL, 
    [Km] NVARCHAR(MAX) NULL, 
    [IntermediarioFlete] NVARCHAR(MAX) NULL, 
    [Transportista] NVARCHAR(MAX) NULL, 
    [Chofer] NVARCHAR(MAX) NULL, 
    [CorredorVendedor] NVARCHAR(MAX) NULL, 
    [CuitOrigenAfip] NVARCHAR(MAX) NULL, 
    [CodLocalidadOrigen] NVARCHAR(MAX) NULL, 
    [NroEstablecimientoOrigen] NVARCHAR(MAX) NULL, 
    [Cumplimiento] BIT NULL, 
    [ConDescarga] BIT NULL, 
    [AdministracionCupoId] INT NULL, 
    [ComercialCreadorId] INT NULL, 
    [Sustentable] BIT NOT NULL DEFAULT 0,
    [EPA] BIT NOT NULL DEFAULT 0,
    [EUDR] BIT NOT NULL DEFAULT 0,
    CONSTRAINT [PK_Cupo] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_Cupo_Proveedor] FOREIGN KEY ([ProveedorId]) REFERENCES [Proveedor]([ProveedorId]), 
    CONSTRAINT [FK_Cupo_Centro] FOREIGN KEY (CentroId) REFERENCES [Centro]([Id]),
    CONSTRAINT [FK_Cupo_Material] FOREIGN KEY (MaterialId) REFERENCES [Material]([MaterialId]),
    CONSTRAINT [FK_Cupo_Comercial] FOREIGN KEY ([ComercialId]) REFERENCES [Comercial]([ComercialId]), 
    CONSTRAINT [FK_Cupo_ComercialCreador] FOREIGN KEY ([ComercialCreadorId]) REFERENCES [Comercial]([ComercialId]), 
    CONSTRAINT [FK_Cupo_ZonaCupo] FOREIGN KEY (ZonaCupoId) REFERENCES [ZonaCupo]([Id]),
    CONSTRAINT [FK_Cupo_EstadoCupo] FOREIGN KEY (estadoCupoId) REFERENCES [EstadoCupo]([Id]),
    CONSTRAINT [FK_Cupo_Negocio] FOREIGN KEY (NegocioId) REFERENCES [Negocio]([Id]),
    CONSTRAINT [FK_Cupo_TipoNegocio] FOREIGN KEY (TipoNegocioId) REFERENCES [TipoNegocio]([TipoNegocioId]),
    CONSTRAINT [FK_Cupo_ConfiguracionEspacioDinamico] FOREIGN KEY (ConfiguracionEspacioDinamicoId) REFERENCES [ConfiguracionEspacioDinamico]([Id]),
    CONSTRAINT [FK_Cupo_AdministracionCupo] FOREIGN KEY (AdministracionCupoId) REFERENCES [AdministracionCupo]([Id]),
    
)
