CREATE TABLE [dbo].[Negocio]
(
	[Id] INT  IDENTITY (1, 1) NOT NULL,
	[ContratoId] INT  NULL , 
    [MaterialId] INT NOT NULL , 
    [TipoNegocioId] INT NOT NULL DEFAULT 1, 
    [Cantidad] FLOAT NULL, 
    [Precio] DECIMAL(11, 2) NULL, 
    [FechaEntrega] DATETIME NULL, 
    [CampanaId] INT NULL, 
    [FechaDesde] DATETIME NOT NULL DEFAULT '1753-01-01', 
    [FechaHasta] DATETIME NOT NULL DEFAULT '1753-01-01', 
    [ProveedorId] INT NULL, 
    [MonedaId] CHAR(5) NULL, 
    [Fecha] DATETIME NULL, 
    [GrupoCompra] INT NULL, 
    [ComercialId] INT NULL, 
	[ProvinciaId] INT NULL,
    [LocalidadId] INT NULL, 
    [Base] BIT NULL, 
    ImporteSustentable DECIMAL(11, 2) NULL, 
	MonedaSustentableId CHAR(5) NULL, 
	FechaDolarizado DATETIME NULL,  
	DiasPesificado INT NULL,  
    [NoInformaSIO] BIT NULL, 
    [TrigoEspecial] BIT NULL, 
    [EstadoId] INT NOT NULL, 
    [UsuarioId] VARCHAR(100) NULL,
    [ContratoSAP] NVARCHAR(15) NULL, 
    [Ampliaciones] FLOAT NULL, 
	[ClasificacionId] INT  NULL,  
    [Observacion] NVARCHAR(MAX) NULL,
	DestinoId INT  NULL,
	CantidadCamiones INT NULL,
	Consignatario BIT NULL,
	PlanCanje BIT NULL,
	CondicionFijacionId INT NULL,
	CD BIT NULL,
	Warrant BIT NULL,
	PagoDirectoVendedor BIT NULL,
	EstablecimientoPropio BIT NULL,
	[BoletoId] INT  NULL,  
	[BolsaId] INT NULL,
	[DesdeFijacion] DATETIME NULL,
	[HastaFijacion] DATETIME NULL,
	[MercsDeposito] BIT NULL,
    [ComercialCreadorId] INT NULL,
	[CorredorId] INT NULL,
	[PorcentajeComision] DECIMAL(11, 2) NULL,
	[ContratoVendedor] NVARCHAR(15) NULL,
    [ContratoCorredor] NVARCHAR(15) NULL,
	[SelCargoVendedor] BIT NULL,
	[SelCargoMOA] BIT NULL,
	[Madre] BIT NULL,
	[ContratoMadre] NVARCHAR(15) NULL,
	[FinDelDiaId] INT NULL,
	[ContratoAcuerdoId] INT NULL,

    [Pizarra] BIT NULL DEFAULT 0, 
    [PrecioNeto] DECIMAL(11, 2) NULL, 
    [StandardDeCalidadId] INT NULL, 
	[PagoDiferido] BIT NULL,
	[ZonaId] INT NULL,
	[NivelTarifaId] INT NULL,
	[TarifaFlete] DECIMAL(11,2) NULL,
	[Compensacion] BIT NULL,
    [Dolarizado] BIT NULL, 
    [Sustentable] BIT NULL, 

	[OperadorId] INT NULL,
	[TipoAgenteCompraId] INT NULL,
	[Posicion] NVARCHAR(10) NULL,	

	[FijacionSAP] NVARCHAR(15) NULL,
	[PagoDiferidoContrato] BIT NULL,
    [ProveedorCreadorId] INT NULL, 
    [MotivoRechazo] NVARCHAR(1000) NULL, 
	[Discriminator]          VARCHAR(250)           NOT NULL,
	[TipoFasonId] [int] NULL,
	[OcultarEnTablero] BIT NOT NULL DEFAULT 0, 
    [FechaCierta] DATETIME NULL, 
    [EsFason] BIT NULL, 
    [PorcentajeDePago] DECIMAL(11, 2) NULL, 
	[CaratulaExtension] NVARCHAR(10) NULL,
	[CaratulaMAT] NVARCHAR(10) NULL,
	[PrecioAjusteComision] DECIMAL(11, 2) NULL,
	[MonedaAjusteComisionId] CHAR(5) NULL,
    [FechaOperacion] DATETIME NULL , 
    [MotivoOperacionAnterior] VARCHAR(500) NULL, 

    [UsuarioConfirmadorId] INT NULL , 
    [FechaConfirmacion] DATETIME NULL, 
    [ChequeElectronico] BIT NULL, 
    [DolarizadoExpress] BIT NULL, 
    [PagoCBU] NVARCHAR(500) NULL, 
    [DolarizadoTercero] BIT NULL, 
    [PagoDiferidoTercero] BIT NULL, 
    [CalidadTercero] BIT NULL, 
    [ObservacionTercero]  NVARCHAR(MAX) NULL,
    
    [Canje] BIT NULL, 
    CONSTRAINT [PK_dbo.Negocio] PRIMARY KEY CLUSTERED ([Id] ASC),
	CONSTRAINT [FK_Negocio_Contrato] FOREIGN KEY ([ContratoId]) REFERENCES [Negocio]([Id]), 
    CONSTRAINT [FK_Negocio_TipoNegocio] FOREIGN KEY ([TipoNegocioId]) REFERENCES [TipoNegocio]([TipoNegocioId]),  
    CONSTRAINT [FK_Negocio_Campaña] FOREIGN KEY ([CampanaId]) REFERENCES [Campaña]([CampañaId]), 
    CONSTRAINT [FK_Negocio_Proveedor] FOREIGN KEY ([ProveedorId]) REFERENCES [Proveedor]([ProveedorId]), 
    CONSTRAINT [FK_Negocio_Moneda] FOREIGN KEY ([MonedaId]) REFERENCES [Moneda]([MonedaId]), 
    CONSTRAINT [FK_Negocio_UsuarioConfirmadorId] FOREIGN KEY ([UsuarioConfirmadorId]) REFERENCES [Comercial]([ComercialId]), 
	CONSTRAINT [FK_Negocio_Comercial] FOREIGN KEY ([ComercialId]) REFERENCES [Comercial]([ComercialId]),
    CONSTRAINT [FK_Negocio_Localidad] FOREIGN KEY ([LocalidadId]) REFERENCES [Localidad]([LocalidadId]), 
    CONSTRAINT [FK_Negocio_EstadoContrato] FOREIGN KEY (EstadoId) REFERENCES [EstadoContrato]([EstadoContratoId]),
    CONSTRAINT [FK_Negocio_Es_Localidad] FOREIGN KEY ([LocalidadId]) REFERENCES [Localidad]([LocalidadId]), 
	CONSTRAINT [FK_Negocio_ClasificacionCompraNet] FOREIGN KEY ([ClasificacionId]) REFERENCES [ClasificacionCompraNet]([Id]), 
	CONSTRAINT [FK_Negocio_BoletoCompraNet] FOREIGN KEY ([BoletoId]) REFERENCES [BoletoCompraNet]([Id]),	
	CONSTRAINT [FK_Negocio_BolsaCompraNet] FOREIGN KEY ([BolsaId]) REFERENCES [BolsaCompraNet]([Id]),
    CONSTRAINT [FK_Negocio_Destino] FOREIGN KEY ([DestinoId]) REFERENCES [Centro](Id),
    CONSTRAINT [FK_Negocio_CondicionFijacion] FOREIGN KEY ([CondicionFijacionId]) REFERENCES [CondicionFijacion]([Id]), 
    CONSTRAINT [FK_Negocio_ComercialCreador] FOREIGN KEY ([ComercialCreadorId]) REFERENCES [Comercial]([ComercialId]), 
    CONSTRAINT [FK_Negocio_Corredor] FOREIGN KEY ([CorredorId]) REFERENCES [Proveedor]([ProveedorId]),
	CONSTRAINT [FK_Negocio_FinDelDia] FOREIGN KEY (FinDelDiaId) REFERENCES [FinDelDia]([Id]),
	CONSTRAINT [FK_Negocio_ContratoAcuerdo] FOREIGN KEY (ContratoAcuerdoId) REFERENCES [Negocio]([Id]),
	CONSTRAINT [FK_Negocio_StandardDeCalidad] FOREIGN KEY (StandardDeCalidadId) REFERENCES [StandardDeCalidad]([Id]),
	CONSTRAINT [FK_Negocio_Zona] FOREIGN KEY (ZonaId) REFERENCES [Zona]([Id]),
	CONSTRAINT [FK_Negocio_NivelTarifa] FOREIGN KEY (NivelTarifaId) REFERENCES [NivelTarifa]([Id]),
	CONSTRAINT [FK_Negocio_TipoFason] FOREIGN KEY([TipoFasonId]) REFERENCES [dbo].[TipoFason] ([Id]),
	CONSTRAINT [FK_Negocio_MonedaAjusteComision] FOREIGN KEY ([MonedaAjusteComisionId]) REFERENCES [Moneda]([MonedaId])
)

GO
CREATE NONCLUSTERED INDEX IX_Fecha_ComercialId_EstadoId
ON [dbo].[Negocio] ([Fecha],[ComercialId],[EstadoId])
INCLUDE ([ContratoId],[Cantidad],[Precio],[ProveedorId],[MonedaId],[ComercialCreadorId])
GO