CREATE TABLE [dbo].[Proveedor] (
    [ProveedorId]				INT             IDENTITY (1, 1) NOT NULL,
    [CUIT]						VARCHAR (20)    NOT NULL,
    [EstadoId]					INT             NULL,
    [RazonSocial]				VARCHAR (100)   NULL,
    [SegmentacionId]			INT             NULL,
    [NombreReferente]			VARCHAR (100)   NULL,
    [Calificacion]				INT             NULL,
    [Intermediario]				VARCHAR (255)   NULL,
    [Observaciones]				NVARCHAR (255)  NULL,
    [Direccion]					VARCHAR (100)   NULL,
    [LocalidadId]				INT             NULL,
    [CodigoPostal]				VARCHAR (20)    NULL,
    [AreaInfluenciaId]			INT             NULL,
    [AlmacVolAnualTotal]		FLOAT  			NULL,
    [AlmacHabilitadoSojaSust]	BIT             NULL,
    [AlmacTonsMaxSojaSust]		FLOAT   	    NULL,
    [AlmacHectSojaSust]			FLOAT 			NULL,
    [ClienteMOA]				BIT             NULL,
    [GrupoCompras]				VARCHAR (255)   NULL,
    [Email1]					VARCHAR (255)   NULL,
    [Email2]					VARCHAR (255)   NULL,
    [Email3]					VARCHAR (255)   NULL,
    [Email4]					VARCHAR (255)   NULL,
    [Telefono1]					VARCHAR (255)   NULL,
    [TipoTelefono1Id]			INT             NULL,
    [Telefono2]					VARCHAR (255)   NULL,
    [TipoTelefono2Id]			INT             NULL,
    [Telefono3]					VARCHAR (255)   NULL,
    [TipoTelefono3Id]			INT             NULL,
    [Telefono4]					VARCHAR (255)   NULL,
    [TipoTelefono4Id]			INT             NULL,
    [FechaUltimoContacto]		DATETIME        NULL,
    [RiesgoComercialSap]		VARCHAR (50)    NULL,
    [ProvinciaId]				INT             NULL,
    [FechaAlta]					DATETIME        NULL,
	[ProvinciaCompraNetId]		INT				NULL,
	[LocalidadCompraNetId]		INT				NULL,
	[ClasificacionCompraNetId]	INT				NULL,
	[BoletoCompraNetId]			INT				NULL,
	[BolsaCompraNetId]			INT				NULL,
	[Consignatario]				BIT				NULL

    CONSTRAINT [PK_Contacto] PRIMARY KEY CLUSTERED ([ProveedorId] ASC),
    CONSTRAINT [FK_Contacto_AreaInfluencia] FOREIGN KEY ([AreaInfluenciaId]) REFERENCES [dbo].[AreaInfluencia] ([AreaInfluenciaId]),
    CONSTRAINT [FK_Contacto_Estado] FOREIGN KEY ([EstadoId]) REFERENCES [dbo].[Estado] ([EstadoId]),
    CONSTRAINT [FK_Contacto_Localidad] FOREIGN KEY ([LocalidadId]) REFERENCES [dbo].[Localidad] ([LocalidadId]),
    CONSTRAINT [FK_Contacto_Segmentacion] FOREIGN KEY ([SegmentacionId]) REFERENCES [dbo].[Segmentacion] ([SegmentacionId]),
    CONSTRAINT [FK_Contacto_TipoTelefono] FOREIGN KEY ([TipoTelefono1Id]) REFERENCES [dbo].[TipoTelefono] ([TipoTelefonoId]),
    CONSTRAINT [FK_Contacto_TipoTelefono1] FOREIGN KEY ([TipoTelefono2Id]) REFERENCES [dbo].[TipoTelefono] ([TipoTelefonoId]),
    CONSTRAINT [FK_Contacto_TipoTelefono2] FOREIGN KEY ([TipoTelefono3Id]) REFERENCES [dbo].[TipoTelefono] ([TipoTelefonoId]),
    CONSTRAINT [FK_Proveedor_TipoTelefono] FOREIGN KEY ([TipoTelefono4Id]) REFERENCES [dbo].[TipoTelefono] ([TipoTelefonoId])
);

