CREATE TABLE [dbo].[Research]
(
    [Id] INT IDENTITY (1, 1) NOT NULL,
    [MaterialId] INT NOT NULL,
    [MaterialIdAntecesor] INT NULL,
    [EstadioId] INT NULL,
    [CondicionId] INT NULL,
    [HumedadSueloId] INT NULL,
    [Comentarios] VARCHAR (100) NULL,
    [Partido] VARCHAR (50) NULL,
    [Localidad] VARCHAR (50) NULL,
    [Provincia] VARCHAR (40) NULL,
    [Latitud] FLOAT NULL,
    [Longitud] FLOAT NULL,
    [TipoMuestraIdUno] INT NULL,
    [MedidasUno] VARCHAR (70) NULL,
    [PromedioMuestraUno] FLOAT NULL,
    [TipoMuestraIdDos] INT NULL,
    [MedidasDos] VARCHAR (70) NULL,
    [PromedioMuestraDos] FLOAT NULL,
    [TipoMuestraIdTres] INT NULL,
    [MedidasTres] VARCHAR (70) NULL,
    [PromedioMuestraTres] FLOAT NULL,
    [DistanciaHileras] FLOAT NULL,
    [Coeficiente] FLOAT NULL,
    [CampañaId] INT NULL,
    [CapitulosGirasol] FLOAT NULL,
    [FechaAlta] DATETIME NULL,
    [Rendimiento] FLOAT NULL,
    [TipoCargaId] INT NULL,
    [EstadoConectividad] VARCHAR (20) NULL,
    [IdPowerApp] INT NULL,
    [FechaModificacion] DATETIME NULL,
    [Author] VARCHAR (50) NULL,
    [Editor] VARCHAR (50) NULL,
    [Attachments] BIT NOT NULL,
    [Sincronizado] BIT NULL,
    [LocalidadId] INT NULL,
    [ComercialId] INT NULL,
    [Eliminado] BIT NOT NULL DEFAULT(0),
    [ProvinciaId] INT NULL,
    [PartidoId] INT NULL,
    [RendimientoCalculado] FLOAT NULL,
    [PromedioGranosVaina] FLOAT NULL, 
    CONSTRAINT [PK_Research] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_Research_Material] FOREIGN KEY ([MaterialId]) REFERENCES [dbo].[Material] ([MaterialId]),
    CONSTRAINT [FK_Research_MaterialAntecesor] FOREIGN KEY ([MaterialIdAntecesor]) REFERENCES [dbo].[Material] ([MaterialId]),
    CONSTRAINT [FK_Research_Estadio] FOREIGN KEY ([EstadioId]) REFERENCES [dbo].[ResearchEstadio] ([EstadioId]),
    CONSTRAINT [FK_Research_ResearchCondicion] FOREIGN KEY ([CondicionId]) REFERENCES [dbo].[ResearchCondicion] ([CondicionId]),
    CONSTRAINT [FK_Research_ResearchHumedadSuelo] FOREIGN KEY ([HumedadSueloId]) REFERENCES [dbo].[ResearchHumedadSuelo] ([HumedadSueloId]),
    CONSTRAINT [FK_Research_ResearchTipoMuestraUno] FOREIGN KEY ([TipoMuestraIdUno]) REFERENCES [dbo].[ResearchTipoMuestra] ([TipoMuestraId]),
    CONSTRAINT [FK_Research_ResearchTipoMuestraDos] FOREIGN KEY ([TipoMuestraIdDos]) REFERENCES [dbo].[ResearchTipoMuestra] ([TipoMuestraId]),
    CONSTRAINT [FK_Research_ResearchTipoMuestraTres] FOREIGN KEY ([TipoMuestraIdTres]) REFERENCES [dbo].[ResearchTipoMuestra] ([TipoMuestraId]),
    CONSTRAINT [FK_Research_Campaña] FOREIGN KEY ([CampañaId]) REFERENCES [dbo].[Campaña] ([CampañaId]),
    CONSTRAINT [FK_Research_ResearchTipoCarga] FOREIGN KEY ([TipoCargaId]) REFERENCES [dbo].[ResearchTipoCarga] ([TipoCargaId]),
    CONSTRAINT [FK_Research_Localidad] FOREIGN KEY ([LocalidadId]) REFERENCES [dbo].[Localidad] ([LocalidadId]),
    CONSTRAINT [FK_Research_Comercial] FOREIGN KEY ([ComercialId]) REFERENCES [dbo].[Comercial] ([ComercialId]),
)
