//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Molinos.DataAgro.Agent.ConfirmaQAConsultaDocumentos {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://confirma.com.ar/gd/2012/05/consultadocumentos", ConfigurationName="ConfirmaQAConsultaDocumentos.IConsultaDocumentosService")]
    public interface IConsultaDocumentosService {
        
        // CODEGEN: Generating message contract since the operation ConsultaEstadoDocumentos is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="ConsultaEstadoDocumentos", ReplyAction="http://confirma.com.ar/gd/2012/05/consultadocumentos/IConsultaDocumentosService/C" +
            "onsultaEstadoDocumentosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Molinos.DataAgro.Agent.ConfirmaQAConsultaDocumentos.DocumentosResponse ConsultaEstadoDocumentos(Molinos.DataAgro.Agent.ConfirmaQAConsultaDocumentos.Documentos request);
        
        [System.ServiceModel.OperationContractAttribute(Action="ConsultaEstadoDocumentos", ReplyAction="http://confirma.com.ar/gd/2012/05/consultadocumentos/IConsultaDocumentosService/C" +
            "onsultaEstadoDocumentosResponse")]
        System.Threading.Tasks.Task<Molinos.DataAgro.Agent.ConfirmaQAConsultaDocumentos.DocumentosResponse> ConsultaEstadoDocumentosAsync(Molinos.DataAgro.Agent.ConfirmaQAConsultaDocumentos.Documentos request);
        
        // CODEGEN: Generating message contract since the operation ConsultaEstadoDocumentoEnCurso is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="ConsultarIdentificadorDocumentoDefinitivo", ReplyAction="http://confirma.com.ar/gd/2012/05/consultadocumentos/IConsultaDocumentosService/C" +
            "onsultaEstadoDocumentoEnCursoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Molinos.DataAgro.Agent.ConfirmaQAConsultaDocumentos.DocumentosResponse ConsultaEstadoDocumentoEnCurso(Molinos.DataAgro.Agent.ConfirmaQAConsultaDocumentos.ConsultaEstadoDocumentoEnCursoMessage request);
        
        [System.ServiceModel.OperationContractAttribute(Action="ConsultarIdentificadorDocumentoDefinitivo", ReplyAction="http://confirma.com.ar/gd/2012/05/consultadocumentos/IConsultaDocumentosService/C" +
            "onsultaEstadoDocumentoEnCursoResponse")]
        System.Threading.Tasks.Task<Molinos.DataAgro.Agent.ConfirmaQAConsultaDocumentos.DocumentosResponse> ConsultaEstadoDocumentoEnCursoAsync(Molinos.DataAgro.Agent.ConfirmaQAConsultaDocumentos.ConsultaEstadoDocumentoEnCursoMessage request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://confirma.com.ar/gd/2012/05/WSConsultaDocumentoSchema")]
    public partial class consultaDocumentoConsultaDocumentoItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string consultaIdBolsaField;
        
        private string consultaIdDocumentoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string consultaIdBolsa {
            get {
                return this.consultaIdBolsaField;
            }
            set {
                this.consultaIdBolsaField = value;
                this.RaisePropertyChanged("consultaIdBolsa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string consultaIdDocumento {
            get {
                return this.consultaIdDocumentoField;
            }
            set {
                this.consultaIdDocumentoField = value;
                this.RaisePropertyChanged("consultaIdDocumento");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://confirma.com.ar/gd/2012/05/WSConsultaDocumentoSchema")]
    public partial class ConsultaEstadoDocumentoEnCursoRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idBolsaField;
        
        private string cUITEmpresaPresentanteField;
        
        private string cUITCompradorField;
        
        private string numeroInternoCompradorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string IdBolsa {
            get {
                return this.idBolsaField;
            }
            set {
                this.idBolsaField = value;
                this.RaisePropertyChanged("IdBolsa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CUITEmpresaPresentante {
            get {
                return this.cUITEmpresaPresentanteField;
            }
            set {
                this.cUITEmpresaPresentanteField = value;
                this.RaisePropertyChanged("CUITEmpresaPresentante");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CUITComprador {
            get {
                return this.cUITCompradorField;
            }
            set {
                this.cUITCompradorField = value;
                this.RaisePropertyChanged("CUITComprador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string NumeroInternoComprador {
            get {
                return this.numeroInternoCompradorField;
            }
            set {
                this.numeroInternoCompradorField = value;
                this.RaisePropertyChanged("NumeroInternoComprador");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://confirma.com.ar/gd/2012/05/WSCommonSchema")]
    public partial class TCodCaption : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string captionField;
        
        private string codListaField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Caption {
            get {
                return this.captionField;
            }
            set {
                this.captionField = value;
                this.RaisePropertyChanged("Caption");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodLista {
            get {
                return this.codListaField;
            }
            set {
                this.codListaField = value;
                this.RaisePropertyChanged("CodLista");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://confirma.com.ar/gd/2012/05/WSConsultaDocumentoResponseSchema")]
    public partial class Empresa : object, System.ComponentModel.INotifyPropertyChanged {
        
        private TCodCaption cUITField;
        
        private string razonSocialField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public TCodCaption CUIT {
            get {
                return this.cUITField;
            }
            set {
                this.cUITField = value;
                this.RaisePropertyChanged("CUIT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string RazonSocial {
            get {
                return this.razonSocialField;
            }
            set {
                this.razonSocialField = value;
                this.RaisePropertyChanged("RazonSocial");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://confirma.com.ar/gd/2012/05/WSConsultaDocumentoResponseSchema")]
    public partial class consultaDocumentosResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private consultaEstadoWS consultaEstadoField;
        
        private string consultaEstadoErrorField;
        
        private consultaDocumentosResponseConsultaDocumentoResponse[] consultaDocumentoResponseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public consultaEstadoWS consultaEstado {
            get {
                return this.consultaEstadoField;
            }
            set {
                this.consultaEstadoField = value;
                this.RaisePropertyChanged("consultaEstado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string consultaEstadoError {
            get {
                return this.consultaEstadoErrorField;
            }
            set {
                this.consultaEstadoErrorField = value;
                this.RaisePropertyChanged("consultaEstadoError");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("consultaDocumentoResponse", Order=2)]
        public consultaDocumentosResponseConsultaDocumentoResponse[] consultaDocumentoResponse {
            get {
                return this.consultaDocumentoResponseField;
            }
            set {
                this.consultaDocumentoResponseField = value;
                this.RaisePropertyChanged("consultaDocumentoResponse");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://confirma.com.ar/gd/2012/05/WSConsultaDocumentoResponseSchema")]
    public enum consultaEstadoWS {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://confirma.com.ar/gd/2012/05/WSConsultaDocumentoResponseSchema")]
    public partial class consultaDocumentosResponseConsultaDocumentoResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idDocumentoField;
        
        private string idBolsaField;
        
        private consultaEstadoDocumento consultaEstadoDocumentoField;
        
        private int estadoDocumentoField;
        
        private Empresa enPoderDeField;
        
        private consultaDocumentosResponseConsultaDocumentoResponseTracking[] accionesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string IdDocumento {
            get {
                return this.idDocumentoField;
            }
            set {
                this.idDocumentoField = value;
                this.RaisePropertyChanged("IdDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string IdBolsa {
            get {
                return this.idBolsaField;
            }
            set {
                this.idBolsaField = value;
                this.RaisePropertyChanged("IdBolsa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public consultaEstadoDocumento consultaEstadoDocumento {
            get {
                return this.consultaEstadoDocumentoField;
            }
            set {
                this.consultaEstadoDocumentoField = value;
                this.RaisePropertyChanged("consultaEstadoDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int EstadoDocumento {
            get {
                return this.estadoDocumentoField;
            }
            set {
                this.estadoDocumentoField = value;
                this.RaisePropertyChanged("EstadoDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public Empresa EnPoderDe {
            get {
                return this.enPoderDeField;
            }
            set {
                this.enPoderDeField = value;
                this.RaisePropertyChanged("EnPoderDe");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Tracking", IsNullable=false)]
        public consultaDocumentosResponseConsultaDocumentoResponseTracking[] Acciones {
            get {
                return this.accionesField;
            }
            set {
                this.accionesField = value;
                this.RaisePropertyChanged("Acciones");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://confirma.com.ar/gd/2012/05/WSConsultaDocumentoResponseSchema")]
    public enum consultaEstadoDocumento {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://confirma.com.ar/gd/2012/05/WSConsultaDocumentoResponseSchema")]
    public partial class consultaDocumentosResponseConsultaDocumentoResponseTracking : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fechaHoraField;
        
        private consultaDocumentosResponseConsultaDocumentoResponseTrackingAccion accionField;
        
        private consultaDocumentosResponseConsultaDocumentoResponseTrackingResultado resultadoField;
        
        private Empresa empresaField;
        
        private consultaDocumentosResponseConsultaDocumentoResponseTrackingUsuario usuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FechaHora {
            get {
                return this.fechaHoraField;
            }
            set {
                this.fechaHoraField = value;
                this.RaisePropertyChanged("FechaHora");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public consultaDocumentosResponseConsultaDocumentoResponseTrackingAccion Accion {
            get {
                return this.accionField;
            }
            set {
                this.accionField = value;
                this.RaisePropertyChanged("Accion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public consultaDocumentosResponseConsultaDocumentoResponseTrackingResultado Resultado {
            get {
                return this.resultadoField;
            }
            set {
                this.resultadoField = value;
                this.RaisePropertyChanged("Resultado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public Empresa Empresa {
            get {
                return this.empresaField;
            }
            set {
                this.empresaField = value;
                this.RaisePropertyChanged("Empresa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public consultaDocumentosResponseConsultaDocumentoResponseTrackingUsuario Usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("Usuario");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://confirma.com.ar/gd/2012/05/WSConsultaDocumentoResponseSchema")]
    public partial class consultaDocumentosResponseConsultaDocumentoResponseTrackingAccion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private codigoAccion codigoField;
        
        private bool codigoFieldSpecified;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public codigoAccion codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoSpecified {
            get {
                return this.codigoFieldSpecified;
            }
            set {
                this.codigoFieldSpecified = value;
                this.RaisePropertyChanged("codigoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://confirma.com.ar/gd/2012/05/WSConsultaDocumentoResponseSchema")]
    public enum codigoAccion {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("9")]
        Item9,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("11")]
        Item11,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://confirma.com.ar/gd/2012/05/WSConsultaDocumentoResponseSchema")]
    public partial class consultaDocumentosResponseConsultaDocumentoResponseTrackingResultado : object, System.ComponentModel.INotifyPropertyChanged {
        
        private codigoResultado codigoField;
        
        private bool codigoFieldSpecified;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public codigoResultado codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoSpecified {
            get {
                return this.codigoFieldSpecified;
            }
            set {
                this.codigoFieldSpecified = value;
                this.RaisePropertyChanged("codigoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://confirma.com.ar/gd/2012/05/WSConsultaDocumentoResponseSchema")]
    public enum codigoResultado {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("18")]
        Item18,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("8")]
        Item8,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("11")]
        Item11,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("27")]
        Item27,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("23")]
        Item23,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("33")]
        Item33,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://confirma.com.ar/gd/2012/05/WSConsultaDocumentoResponseSchema")]
    public partial class consultaDocumentosResponseConsultaDocumentoResponseTrackingUsuario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tipoDocumentoField;
        
        private string nroDocumentoField;
        
        private string apellidoField;
        
        private string nombreField;
        
        private string cargoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TipoDocumento {
            get {
                return this.tipoDocumentoField;
            }
            set {
                this.tipoDocumentoField = value;
                this.RaisePropertyChanged("TipoDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string NroDocumento {
            get {
                return this.nroDocumentoField;
            }
            set {
                this.nroDocumentoField = value;
                this.RaisePropertyChanged("NroDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Apellido {
            get {
                return this.apellidoField;
            }
            set {
                this.apellidoField = value;
                this.RaisePropertyChanged("Apellido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Cargo {
            get {
                return this.cargoField;
            }
            set {
                this.cargoField = value;
                this.RaisePropertyChanged("Cargo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Documentos {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://confirma.com.ar/gd/2012/05/consultadocumentos", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("consultaDocumentoItem", Namespace="http://confirma.com.ar/gd/2012/05/WSConsultaDocumentoSchema", IsNullable=false)]
        public Molinos.DataAgro.Agent.ConfirmaQAConsultaDocumentos.consultaDocumentoConsultaDocumentoItem[] ConsultaDocumento;
        
        public Documentos() {
        }
        
        public Documentos(Molinos.DataAgro.Agent.ConfirmaQAConsultaDocumentos.consultaDocumentoConsultaDocumentoItem[] ConsultaDocumento) {
            this.ConsultaDocumento = ConsultaDocumento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DocumentosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://confirma.com.ar/gd/2012/05/consultadocumentos", Order=0)]
        public Molinos.DataAgro.Agent.ConfirmaQAConsultaDocumentos.consultaDocumentosResponse ConsultaDocumentosResponse;
        
        public DocumentosResponse() {
        }
        
        public DocumentosResponse(Molinos.DataAgro.Agent.ConfirmaQAConsultaDocumentos.consultaDocumentosResponse ConsultaDocumentosResponse) {
            this.ConsultaDocumentosResponse = ConsultaDocumentosResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaEstadoDocumentoEnCursoMessage {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://confirma.com.ar/gd/2012/05/consultadocumentos", Order=0)]
        public Molinos.DataAgro.Agent.ConfirmaQAConsultaDocumentos.ConsultaEstadoDocumentoEnCursoRequest ConsultaEstadoDocumentoEnCursoRequest;
        
        public ConsultaEstadoDocumentoEnCursoMessage() {
        }
        
        public ConsultaEstadoDocumentoEnCursoMessage(Molinos.DataAgro.Agent.ConfirmaQAConsultaDocumentos.ConsultaEstadoDocumentoEnCursoRequest ConsultaEstadoDocumentoEnCursoRequest) {
            this.ConsultaEstadoDocumentoEnCursoRequest = ConsultaEstadoDocumentoEnCursoRequest;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConsultaDocumentosServiceChannel : Molinos.DataAgro.Agent.ConfirmaQAConsultaDocumentos.IConsultaDocumentosService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsultaDocumentosServiceClient : System.ServiceModel.ClientBase<Molinos.DataAgro.Agent.ConfirmaQAConsultaDocumentos.IConsultaDocumentosService>, Molinos.DataAgro.Agent.ConfirmaQAConsultaDocumentos.IConsultaDocumentosService {
        
        public ConsultaDocumentosServiceClient() {
        }
        
        public ConsultaDocumentosServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConsultaDocumentosServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultaDocumentosServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultaDocumentosServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Molinos.DataAgro.Agent.ConfirmaQAConsultaDocumentos.DocumentosResponse Molinos.DataAgro.Agent.ConfirmaQAConsultaDocumentos.IConsultaDocumentosService.ConsultaEstadoDocumentos(Molinos.DataAgro.Agent.ConfirmaQAConsultaDocumentos.Documentos request) {
            return base.Channel.ConsultaEstadoDocumentos(request);
        }
        
        public Molinos.DataAgro.Agent.ConfirmaQAConsultaDocumentos.consultaDocumentosResponse ConsultaEstadoDocumentos(Molinos.DataAgro.Agent.ConfirmaQAConsultaDocumentos.consultaDocumentoConsultaDocumentoItem[] ConsultaDocumento) {
            Molinos.DataAgro.Agent.ConfirmaQAConsultaDocumentos.Documentos inValue = new Molinos.DataAgro.Agent.ConfirmaQAConsultaDocumentos.Documentos();
            inValue.ConsultaDocumento = ConsultaDocumento;
            Molinos.DataAgro.Agent.ConfirmaQAConsultaDocumentos.DocumentosResponse retVal = ((Molinos.DataAgro.Agent.ConfirmaQAConsultaDocumentos.IConsultaDocumentosService)(this)).ConsultaEstadoDocumentos(inValue);
            return retVal.ConsultaDocumentosResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Molinos.DataAgro.Agent.ConfirmaQAConsultaDocumentos.DocumentosResponse> Molinos.DataAgro.Agent.ConfirmaQAConsultaDocumentos.IConsultaDocumentosService.ConsultaEstadoDocumentosAsync(Molinos.DataAgro.Agent.ConfirmaQAConsultaDocumentos.Documentos request) {
            return base.Channel.ConsultaEstadoDocumentosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Molinos.DataAgro.Agent.ConfirmaQAConsultaDocumentos.DocumentosResponse> ConsultaEstadoDocumentosAsync(Molinos.DataAgro.Agent.ConfirmaQAConsultaDocumentos.consultaDocumentoConsultaDocumentoItem[] ConsultaDocumento) {
            Molinos.DataAgro.Agent.ConfirmaQAConsultaDocumentos.Documentos inValue = new Molinos.DataAgro.Agent.ConfirmaQAConsultaDocumentos.Documentos();
            inValue.ConsultaDocumento = ConsultaDocumento;
            return ((Molinos.DataAgro.Agent.ConfirmaQAConsultaDocumentos.IConsultaDocumentosService)(this)).ConsultaEstadoDocumentosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Molinos.DataAgro.Agent.ConfirmaQAConsultaDocumentos.DocumentosResponse Molinos.DataAgro.Agent.ConfirmaQAConsultaDocumentos.IConsultaDocumentosService.ConsultaEstadoDocumentoEnCurso(Molinos.DataAgro.Agent.ConfirmaQAConsultaDocumentos.ConsultaEstadoDocumentoEnCursoMessage request) {
            return base.Channel.ConsultaEstadoDocumentoEnCurso(request);
        }
        
        public Molinos.DataAgro.Agent.ConfirmaQAConsultaDocumentos.consultaDocumentosResponse ConsultaEstadoDocumentoEnCurso(Molinos.DataAgro.Agent.ConfirmaQAConsultaDocumentos.ConsultaEstadoDocumentoEnCursoRequest ConsultaEstadoDocumentoEnCursoRequest) {
            Molinos.DataAgro.Agent.ConfirmaQAConsultaDocumentos.ConsultaEstadoDocumentoEnCursoMessage inValue = new Molinos.DataAgro.Agent.ConfirmaQAConsultaDocumentos.ConsultaEstadoDocumentoEnCursoMessage();
            inValue.ConsultaEstadoDocumentoEnCursoRequest = ConsultaEstadoDocumentoEnCursoRequest;
            Molinos.DataAgro.Agent.ConfirmaQAConsultaDocumentos.DocumentosResponse retVal = ((Molinos.DataAgro.Agent.ConfirmaQAConsultaDocumentos.IConsultaDocumentosService)(this)).ConsultaEstadoDocumentoEnCurso(inValue);
            return retVal.ConsultaDocumentosResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Molinos.DataAgro.Agent.ConfirmaQAConsultaDocumentos.DocumentosResponse> Molinos.DataAgro.Agent.ConfirmaQAConsultaDocumentos.IConsultaDocumentosService.ConsultaEstadoDocumentoEnCursoAsync(Molinos.DataAgro.Agent.ConfirmaQAConsultaDocumentos.ConsultaEstadoDocumentoEnCursoMessage request) {
            return base.Channel.ConsultaEstadoDocumentoEnCursoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Molinos.DataAgro.Agent.ConfirmaQAConsultaDocumentos.DocumentosResponse> ConsultaEstadoDocumentoEnCursoAsync(Molinos.DataAgro.Agent.ConfirmaQAConsultaDocumentos.ConsultaEstadoDocumentoEnCursoRequest ConsultaEstadoDocumentoEnCursoRequest) {
            Molinos.DataAgro.Agent.ConfirmaQAConsultaDocumentos.ConsultaEstadoDocumentoEnCursoMessage inValue = new Molinos.DataAgro.Agent.ConfirmaQAConsultaDocumentos.ConsultaEstadoDocumentoEnCursoMessage();
            inValue.ConsultaEstadoDocumentoEnCursoRequest = ConsultaEstadoDocumentoEnCursoRequest;
            return ((Molinos.DataAgro.Agent.ConfirmaQAConsultaDocumentos.IConsultaDocumentosService)(this)).ConsultaEstadoDocumentoEnCursoAsync(inValue);
        }
    }
}
