//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Molinos.DataAgro.Entities.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Molinos.DataAgro.Entities.Resources.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ampliaciones.
        /// </summary>
        public static string Ampliaciones {
            get {
                return ResourceManager.GetString("Ampliaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base.
        /// </summary>
        public static string Base {
            get {
                return ResourceManager.GetString("Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boleto.
        /// </summary>
        public static string Boleto {
            get {
                return ResourceManager.GetString("Boleto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bolsa.
        /// </summary>
        public static string Bolsa {
            get {
                return ResourceManager.GetString("Bolsa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calidad Especial.
        /// </summary>
        public static string CalidadEspecial {
            get {
                return ResourceManager.GetString("CalidadEspecial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaña.
        /// </summary>
        public static string Campana {
            get {
                return ResourceManager.GetString("Campana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad.
        /// </summary>
        public static string Cantidad {
            get {
                return ResourceManager.GetString("Cantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad Camiones.
        /// </summary>
        public static string CantidadCamiones {
            get {
                return ResourceManager.GetString("CantidadCamiones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comercial.
        /// </summary>
        public static string Comercial {
            get {
                return ResourceManager.GetString("Comercial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condición Fijacion.
        /// </summary>
        public static string CondicionFijacion {
            get {
                return ResourceManager.GetString("CondicionFijacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consignatario.
        /// </summary>
        public static string Consignatario {
            get {
                return ResourceManager.GetString("Consignatario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nro Contrato.
        /// </summary>
        public static string Contrato {
            get {
                return ResourceManager.GetString("Contrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUIT.
        /// </summary>
        public static string Cuit {
            get {
                return ResourceManager.GetString("Cuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desde Fijacion.
        /// </summary>
        public static string DesdeFijacion {
            get {
                return ResourceManager.GetString("DesdeFijacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destino.
        /// </summary>
        public static string Destino {
            get {
                return ResourceManager.GetString("Destino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Días Pesificado.
        /// </summary>
        public static string DiasPesificado {
            get {
                return ResourceManager.GetString("DiasPesificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Establecimiento.
        /// </summary>
        public static string EstablecimientoPropio {
            get {
                return ResourceManager.GetString("EstablecimientoPropio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Operación.
        /// </summary>
        public static string Fecha {
            get {
                return ResourceManager.GetString("Fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Desde.
        /// </summary>
        public static string FechaDesde {
            get {
                return ResourceManager.GetString("FechaDesde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Dolarizado.
        /// </summary>
        public static string FechaDolarizado {
            get {
                return ResourceManager.GetString("FechaDolarizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Hasta.
        /// </summary>
        public static string FechaHasta {
            get {
                return ResourceManager.GetString("FechaHasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasta Fijacion.
        /// </summary>
        public static string HastaFijacion {
            get {
                return ResourceManager.GetString("HastaFijacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importe Sustentable.
        /// </summary>
        public static string ImporteSustentable {
            get {
                return ResourceManager.GetString("ImporteSustentable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localidad.
        /// </summary>
        public static string Localidad {
            get {
                return ResourceManager.GetString("Localidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material.
        /// </summary>
        public static string Material {
            get {
                return ResourceManager.GetString("Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moneda.
        /// </summary>
        public static string Moneda {
            get {
                return ResourceManager.GetString("Moneda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Informa Sio.
        /// </summary>
        public static string NoInformaSio {
            get {
                return ResourceManager.GetString("NoInformaSio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observación.
        /// </summary>
        public static string Observacion {
            get {
                return ResourceManager.GetString("Observacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pago.
        /// </summary>
        public static string Pago {
            get {
                return ResourceManager.GetString("Pago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan Canje.
        /// </summary>
        public static string PlanCanje {
            get {
                return ResourceManager.GetString("PlanCanje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio.
        /// </summary>
        public static string Precio {
            get {
                return ResourceManager.GetString("Precio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provincia.
        /// </summary>
        public static string Provincia {
            get {
                return ResourceManager.GetString("Provincia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razon Social.
        /// </summary>
        public static string RazonSocial {
            get {
                return ResourceManager.GetString("RazonSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Negocio.
        /// </summary>
        public static string TipoNegocio {
            get {
                return ResourceManager.GetString("TipoNegocio", resourceCulture);
            }
        }
    }
}
