 using KendoGridBinder;
using KendoGridBinder.ModelBinder.Mvc;
using Molinos.DataAgro.Entities.Common.Enums;
using Molinos.DataAgro.Entities.Dto;
using Molinos.DataAgro.Entities.Entities;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.SqlServer;
using System.Linq;
using System.Transactions;

namespace Molinos.DataAgro.Repository.ConsultasEF
{
    public class TraerTodosContratos : IConsultaEscalar<KendoGrid<BasicoContrato>>
    {
        private readonly KendoGridMvcRequest request;
        private readonly List<int> equipo;
        private readonly int perfilId;
        private readonly List<int> corredoresComercial;

        public TraerTodosContratos(KendoGridMvcRequest request, int perfilId, List<int> equipo, List<int> corredoresComercial)
        {
            this.request = request;
            this.equipo = equipo;
            this.perfilId = perfilId;
            this.corredoresComercial = corredoresComercial;
        }

        private static KendoGrid<BasicoContrato> Query(DbContext contexto, KendoGridMvcRequest request, int perfilId, List<int> equipo, List<int> corredoresComercial)
        {
            ((System.Data.Entity.Infrastructure.IObjectContextAdapter)contexto).ObjectContext.CommandTimeout = 180;

            var queryContratos =
                from contrato in contexto.Set<Contrato>()
                where perfilId != 8 ? equipo.Contains(contrato.ComercialId != null ? contrato.ComercialId.Value : 0) ||
                equipo.Contains(contrato.ComercialCreadorId != null ? contrato.ComercialCreadorId.Value : 0) :
                    (perfilId == (int)EnumPerfil.CorredoresComercial &&
                    (corredoresComercial.Contains(contrato.ComercialId != null ? contrato.ComercialId.Value : 0) ||
                    corredoresComercial.Contains(contrato.ComercialCreadorId != null ? contrato.ComercialCreadorId.Value : 0)))
                select new BasicoContrato()
                {
                    Id = contrato.ContratoId,
                    ContratoId = contrato.ContratoId,
                    ProveedorId = contrato.ProveedorId,
                    CorredorId = contrato.CorredorId != null ? contrato.CorredorId.Value : 0,
                    ComercialId = contrato.ComercialId,
                    MaterialId = contrato.MaterialId,
                    TipoNegocioId = contrato.TipoNegocioId,
                    Cantidad = contrato.Cantidad,
                    Precio = contrato.Precio,
                    PrecioPlazo = contrato.TipoNegocioId == 1 ? SqlFunctions.DateName("day", contrato.HastaFijacion) + "/" + SqlFunctions.DatePart("month", contrato.HastaFijacion) + "/" + SqlFunctions.DateName("year", contrato.HastaFijacion) : contrato.Precio.ToString(),
                    FechaEntrega = contrato.FechaEntrega,
                    CampanaId = contrato.CampanaId,
                    FechaDesde = DbFunctions.TruncateTime(contrato.FechaDesde),
                    FechaHasta = DbFunctions.TruncateTime(contrato.FechaHasta),
                    MonedaId = contrato.MonedaId,
                    Moneda = contrato.Moneda == null ? "" : contrato.Moneda.Descripcion,
                    Fecha = DbFunctions.TruncateTime(contrato.Fecha),
                    Hora = SqlFunctions.DateName("hh", contrato.Fecha) + ":" + SqlFunctions.DateName("mi", contrato.Fecha),
                    Fecha_Order = contrato.Fecha,
                    GrupoCompra = contrato.GrupoCompra,
                    GrupoCompraDescripcion = contrato.GrupoDeCompras.Descripcion,
                    ProvinciaId = contrato.ProvinciaId,
                    LocalidadId = contrato.LocalidadId,
                    Base = contrato.Base,
                    Importe_Sustentable = ((decimal)contrato.ImporteSustentable),
                    MonedaId_Sustentable = contrato.MonedaSustentableId,
                    Moneda_Sustentable = contrato.MonedaSustentable == null ? "" : contrato.MonedaSustentable.Descripcion,
                    Fecha_Dolarizado = DbFunctions.TruncateTime(contrato.FechaDolarizado),
                    Dias_Pesificado = contrato.DiasPesificado,
                    NoInformaSIO = contrato.NoInformaSio,
                    Estado = contrato.EstadoId,
                    Estado_Contrato = contrato.Estado.Descripcion,
                    Estado_Order = contrato.Estado.Orden,
                    UsuarioId = contrato.UsuarioId,
                    ContratoSAP = contrato.ContratoSAP,
                    Ampliaciones = contrato.Ampliaciones,
                    Cuit = contrato.Proveedor == null ? "" : contrato.Proveedor.CUIT,
                    Proveedor = contrato.Proveedor == null ? "" : contrato.Proveedor.RazonSocial,
                    Corredor = contrato.Corredor == null ? "" : contrato.Corredor.RazonSocial,
                    Comercial = contrato.Comercial == null ? "" : contrato.Comercial.Nombres + " " + contrato.Comercial.Apellido,
                    Material = contrato.Material == null ? "" : contrato.Material.Descripcion,
                    Campania = contrato.Campana == null ? "" : contrato.Campana.Descripcion,
                    Provincia = contrato.Provincia == null ? "" : contrato.Provincia.Nombre,
                    TipoNegocio = contrato.TipoNegocio == null ? "" : contrato.Madre == true ? "CONVENIO" : contrato.Madre == false ? "FIJ. CONVENIO" : contrato.TipoNegocio.Descripcion,
                    Localidad = contrato.Localidad == null ? "" : contrato.Localidad.Nombre,
                    Observacion = contrato.Observacion != null ? contrato.Observacion : "",
                    FijacionDePrecioContratoId = null,
                    Sustentable = ((decimal)contrato.ImporteSustentable) != null && ((decimal)contrato.ImporteSustentable) > 0,
                    Dolarizado = contrato.FechaDolarizado != null,
                    Pesificado = contrato.DiasPesificado != null,
                    Negocio = contrato.ContratoSAP != "0" ? contrato.ContratoSAP : "",
                    DestinoId = contrato.DestinoId,
                    DestinoDescripcion = contrato.Destino.Descripcion,
                    CantidadCamiones = contrato.CantidadCamiones,
                    Consignatario = contrato.Consignatario,
                    PlanCanje = contrato.PlanCanje,
                    CD = contrato.CD,
                    Warrant = contrato.Warrant,
                    PagoDirectoVendedor = contrato.PagoDirectoVendedor,
                    EstablecimientoPropio = contrato.EstablecimientoPropio,
                    BoletoId = contrato.BoletoId,
                    BolsaId = contrato.BolsaId,
                    BoletoDescripcion = contrato.Boleto.Descripcion,
                    BolsaDescripcion = contrato.Bolsa.Descripcion,
                    DesdeFijacion = DbFunctions.TruncateTime(contrato.DesdeFijacion),
                    HastaFijacion = DbFunctions.TruncateTime(contrato.HastaFijacion),
                    CondicionFijacion = contrato.CondicionFijacionId,
                    CondicionFijacionDescripcion = contrato.CondicionFijacion.Descripcion,
                    ClasificacionId = contrato.ClasificacionId,
                    ClasificacionDescripcion = contrato.Clasificacion.Descripcion,
                    CalidadDescripcion = contrato.TrigoEspecial == true ? "Especial" : "Cámara",
                    MercsDeposito = contrato.MercsDeposito == true ? contrato.MercsDeposito : false,
                    ComercialCreadorId = contrato.ComercialCreadorId,
                    ComercialCreador = contrato.ComercialCreador == null ? contrato.Comercial.Nombres + " " + contrato.Comercial.Apellido : contrato.ComercialCreador.Nombres + " " + contrato.ComercialCreador.Apellido,
                    ContratoCorredor = contrato.ContratoCorredor,
                    ContratoVendedor = contrato.ContratoVendedor,
                    SelCargoMOA = contrato.SelCargoMOA,
                    SelCargoVendedor = contrato.SelCargoVendedor,
                    Posicion = "",
                    TipoFason = "",
                    FasonId = 0,
                    Operador = "",
                    OperadorId = 0,
                    AgenteId = 0,
                    PrecioNeto = contrato.PrecioNeto,
                    StandardCalidadId = contrato.StandardDeCalidadId,
                    StandardDeCalidadDescripcion = contrato.StandardDeCalidad.Descripcion,
                    Pizarra = contrato.Pizarra ?? null,
                    PagoDiferido = contrato.PagoDiferido ?? null,
                    ZonaId = contrato.Zona != null ? contrato.ZonaId : null,
                    ZonaDescripcion = contrato.Zona != null ? contrato.Zona.Descripcion : "",
                    AcuerdoId = null,
                    ImporteFinanciero = contrato.AperturaPrecio.FirstOrDefault(t => t.ConceptoAperturaPrecioId == 1).Importe,
                    ImporteRedespacho = contrato.AperturaPrecio.FirstOrDefault(t => t.ConceptoAperturaPrecioId == 2).Importe,
                    PorcentajeComision = contrato.AperturaPrecio.FirstOrDefault(t => t.ConceptoAperturaPrecioId == 3).Porcentaje,
                    ImporteComision = contrato.AperturaPrecio.FirstOrDefault(t => t.ConceptoAperturaPrecioId == 3).Importe,
                    ImporteBonificacion = contrato.AperturaPrecio.FirstOrDefault(t => t.ConceptoAperturaPrecioId == 4).Importe,
                    PorcentajeBonificacion = contrato.AperturaPrecio.FirstOrDefault(t => t.ConceptoAperturaPrecioId == 4).Porcentaje,
                    NivelTarifa = contrato.NivelTarifa.Descripcion,
                    TarifaFlete = contrato.TarifaFlete,
                    Compensacion = contrato.Compensacion.Value
                };

            var queryFijacion =
                from fijac in contexto.Set<FijacionDePrecioContrato>()
                where perfilId != 8 ? equipo.Contains(fijac.ComercialId) || equipo.Contains(fijac.ComercialCreadorId) :
                        (perfilId == (int)EnumPerfil.CorredoresComercial && (corredoresComercial.Contains(fijac.ComercialId) ||
                        corredoresComercial.Contains(fijac.ComercialCreadorId)))
                select new BasicoContrato()
                {
                    Id = fijac.FijacionDePrecioContratoId,
                    ContratoId = fijac.ContratoId.HasValue ? fijac.ContratoId.Value : 0,
                    ProveedorId = fijac.ProveedorId,
                    CorredorId = fijac.CorredorId != null ? fijac.CorredorId.Value : 0,
                    ComercialId = fijac.ComercialId,
                    MaterialId = fijac.MaterialId != null ? fijac.MaterialId.Value : 0,
                    TipoNegocioId = 3,
                    Cantidad = fijac.Cantidad,
                    Precio = fijac.Precio,
                    PrecioPlazo = fijac.Precio.ToString(),
                    FechaEntrega = null,
                    CampanaId = 0,
                    FechaDesde = null,
                    FechaHasta = null,
                    MonedaId = fijac.MonedaId,
                    Moneda = fijac.Moneda == null ? "" : fijac.Moneda.Descripcion,
                    Fecha = DbFunctions.TruncateTime(fijac.Fecha),
                    Hora = SqlFunctions.DateName("hour", fijac.Fecha) + ":" + SqlFunctions.DateName("minute", fijac.Fecha),
                    Fecha_Order = fijac.Fecha,
                    GrupoCompra = 0,
                    GrupoCompraDescripcion = null,
                    ProvinciaId = null,
                    LocalidadId = null,
                    Base = null,
                    Importe_Sustentable = null,
                    MonedaId_Sustentable = "",
                    Moneda_Sustentable = "",
                    Fecha_Dolarizado = null,
                    Dias_Pesificado = fijac.DiasPesificado,
                    NoInformaSIO = null,
                    Estado = fijac.EstadoId,
                    Estado_Contrato = fijac.Estado.Descripcion,
                    Estado_Order = fijac.Estado.Orden,
                    UsuarioId = "",
                    ContratoSAP = fijac.ContratoSAP,
                    Ampliaciones = fijac.Ampliaciones,
                    Cuit = fijac.Proveedor == null ? "" : fijac.Proveedor.CUIT,
                    Proveedor = fijac.Proveedor == null ? "" : fijac.Proveedor.RazonSocial,
                    Corredor = fijac.Corredor == null ? "" : fijac.Corredor.RazonSocial,
                    Comercial = fijac.Comercial == null ? "" : fijac.Comercial.Nombres + " " + fijac.Comercial.Apellido,
                    Material = fijac.Material == null ? "" : fijac.Material.Descripcion,
                    Campania = "",
                    Provincia = "",
                    TipoNegocio = "FIJACION",
                    Localidad = "",
                    Observacion = fijac.Observacion ?? "",
                    FijacionDePrecioContratoId = fijac.FijacionDePrecioContratoId,
                    Sustentable = false,
                    Dolarizado = false,
                    Pesificado = false,
                    Negocio = fijac.EstadoId == (int)EnumEstadoContrato.Finalizado ? fijac.FijacionSAP : fijac.ContratoSAP,
                    DestinoId = fijac.DestinoId,
                    DestinoDescripcion = fijac.Destino != null ? fijac.Destino.Descripcion : "",
                    CantidadCamiones = null,
                    Consignatario = false,
                    PlanCanje = false,
                    CD = null,
                    Warrant = null,
                    PagoDirectoVendedor = null,
                    EstablecimientoPropio = null,
                    BoletoId = null,
                    BolsaId = null,
                    BoletoDescripcion = "",
                    BolsaDescripcion = "",
                    DesdeFijacion = null,
                    HastaFijacion = null,
                    CondicionFijacion = null,
                    CondicionFijacionDescripcion = "",
                    ClasificacionId = null,
                    ClasificacionDescripcion = "",
                    CalidadDescripcion = "",
                    MercsDeposito = null,
                    ComercialCreadorId = fijac.ComercialCreadorId,
                    ComercialCreador = fijac.ComercialCreador == null ? fijac.Comercial.Nombres + " " + fijac.Comercial.Apellido : fijac.ComercialCreador.Nombres + " " + fijac.ComercialCreador.Apellido,
                    ContratoCorredor = "",
                    ContratoVendedor = "",
                    SelCargoMOA = null,
                    SelCargoVendedor = null,
                    Posicion = "",
                    TipoFason = "",
                    FasonId = 0,
                    Operador = "",
                    OperadorId = 0,
                    AgenteId = 0,
                    PrecioNeto = fijac.PrecioNeto,
                    StandardCalidadId = null,
                    StandardDeCalidadDescripcion = "",
                    Pizarra = fijac.Pizarra ?? null,
                    PagoDiferido = fijac.PagoDiferido ?? null,
                    ZonaId = null,
                    ZonaDescripcion = "",
                    AcuerdoId = null,
                    ImporteFinanciero = fijac.AperturaPrecio.FirstOrDefault(t => t.ConceptoAperturaPrecioId == 1).Importe,
                    ImporteRedespacho = fijac.AperturaPrecio.FirstOrDefault(t => t.ConceptoAperturaPrecioId == 2).Importe,
                    PorcentajeComision = fijac.AperturaPrecio.FirstOrDefault(t => t.ConceptoAperturaPrecioId == 3).Porcentaje,
                    ImporteComision = fijac.AperturaPrecio.FirstOrDefault(t => t.ConceptoAperturaPrecioId == 3).Importe,
                    ImporteBonificacion = fijac.AperturaPrecio.FirstOrDefault(t => t.ConceptoAperturaPrecioId == 4).Importe,
                    PorcentajeBonificacion = fijac.AperturaPrecio.FirstOrDefault(t => t.ConceptoAperturaPrecioId == 4).Porcentaje,
                    NivelTarifa = "",
                    TarifaFlete = null,
                    Compensacion = null
                };

            queryContratos = queryContratos.Union(queryFijacion);
            if (perfilId == 7)
            {
                var queryFason =
                    from fas in contexto.Set<Fason>()
                    where equipo.Contains(fas.ComercialId)
                    select new BasicoContrato()
                    {
                        Id = fas.Id,
                        ContratoId = 0,
                        ProveedorId = fas.FasoneroId,
                        CorredorId = 0,
                        ComercialId = fas.ComercialId,
                        MaterialId = fas.MaterialId,
                        TipoNegocioId = 4,
                        Cantidad = fas.Cantidad,
                        Precio = fas.Precio,
                        PrecioPlazo = fas.Precio.ToString(),
                        FechaEntrega = null,
                        CampanaId = 0,
                        FechaDesde = null,
                        FechaHasta = null,
                        MonedaId = fas.MonedaId,
                        Moneda = fas.Moneda == null ? "" : fas.Moneda.Descripcion,
                        Fecha = DbFunctions.TruncateTime(fas.Fecha),
                        Hora = SqlFunctions.DateName("hour", fas.Fecha) + ":" + SqlFunctions.DateName("minute", fas.Fecha),
                        Fecha_Order = fas.Fecha,
                        GrupoCompra = 0,
                        GrupoCompraDescripcion = null,
                        ProvinciaId = null,
                        LocalidadId = null,
                        Base = null,
                        Importe_Sustentable = null,
                        MonedaId_Sustentable = "",
                        Moneda_Sustentable = "",
                        Fecha_Dolarizado = null,
                        Dias_Pesificado = null,
                        NoInformaSIO = null,
                        Estado = fas.EstadoId,
                        Estado_Contrato = fas.Estado.Descripcion,
                        Estado_Order = fas.Estado.Orden,
                        UsuarioId = "",
                        ContratoSAP = null,
                        Ampliaciones = fas.Ampliaciones,
                        Cuit = "",
                        Proveedor = fas.Fasonero == null ? "" : fas.Fasonero.RazonSocial,
                        Corredor = "",
                        Comercial = fas.Comercial == null ? "" : fas.Comercial.Nombres + " " + fas.Comercial.Apellido,
                        Material = fas.Material == null ? "" : fas.Material.Descripcion,
                        Campania = fas.Campana == null ? "" : fas.Campana.Descripcion,
                        Provincia = "",
                        TipoNegocio = "FASON",
                        Localidad = "",
                        Observacion = "",
                        FijacionDePrecioContratoId = null,
                        Sustentable = false,
                        Dolarizado = false,
                        Pesificado = false,
                        Negocio = null,
                        DestinoId = null,
                        DestinoDescripcion = "",
                        CantidadCamiones = null,
                        Consignatario = false,
                        PlanCanje = false,
                        CD = null,
                        Warrant = null,
                        PagoDirectoVendedor = null,
                        EstablecimientoPropio = null,
                        BoletoId = null,
                        BolsaId = null,
                        BoletoDescripcion = "",
                        BolsaDescripcion = "",
                        DesdeFijacion = null,
                        HastaFijacion = null,
                        CondicionFijacion = null,
                        CondicionFijacionDescripcion = "",
                        ClasificacionId = null,
                        ClasificacionDescripcion = "",
                        CalidadDescripcion = "",
                        MercsDeposito = null,
                        ComercialCreadorId = fas.ComercialCreadorId,
                        ComercialCreador = fas.ComercialCreador == null ? fas.Comercial.Nombres + " " + fas.Comercial.Apellido : fas.ComercialCreador.Nombres + " " + fas.ComercialCreador.Apellido,
                        ContratoCorredor = "",
                        ContratoVendedor = "",
                        SelCargoMOA = null,
                        SelCargoVendedor = null,
                        Posicion = fas.Posicion,
                        TipoFason = fas.TipoFason.Descripcion,
                        FasonId = fas.Id,
                        Operador = "",
                        OperadorId = 0,
                        AgenteId = 0,
                        PrecioNeto = null,
                        StandardCalidadId = null,
                        StandardDeCalidadDescripcion = "",
                        Pizarra = null,
                        PagoDiferido = null,
                        ZonaId = null,
                        ZonaDescripcion = "",
                        AcuerdoId = null,
                        ImporteFinanciero = null,
                        ImporteRedespacho = null,
                        PorcentajeComision = null,
                        ImporteComision = null,
                        ImporteBonificacion = null,
                        PorcentajeBonificacion = null,
                        NivelTarifa = "",
                        TarifaFlete = null,
                        Compensacion = null
                    };

                queryContratos = queryContratos.Union(queryFason);

                var queryAgente =
                    from age in contexto.Set<AgenteCompra>()
                    where equipo.Contains(age.ComercialId)
                    select new BasicoContrato()
                    {
                        Id = age.Id,
                        ContratoId = 0,
                        ProveedorId = 0,
                        CorredorId = 0,
                        ComercialId = age.ComercialId,
                        MaterialId = age.MaterialId,
                        TipoNegocioId = 5,
                        Cantidad = age.Cantidad,
                        Precio = age.Precio,
                        PrecioPlazo = age.Precio.ToString(),
                        FechaEntrega = null,
                        CampanaId = 0,
                        FechaDesde = null,
                        FechaHasta = null,
                        MonedaId = age.MonedaId,
                        Moneda = age.Moneda == null ? "" : age.Moneda.Descripcion,
                        Fecha = DbFunctions.TruncateTime(age.Fecha),
                        Hora = SqlFunctions.DateName("hour", age.Fecha) + ":" + SqlFunctions.DateName("minute", age.Fecha),
                        Fecha_Order = age.Fecha,
                        GrupoCompra = 0,
                        GrupoCompraDescripcion = null,
                        ProvinciaId = null,
                        LocalidadId = null,
                        Base = null,
                        Importe_Sustentable = null,
                        MonedaId_Sustentable = "",
                        Moneda_Sustentable = "",
                        Fecha_Dolarizado = null,
                        Dias_Pesificado = null,
                        NoInformaSIO = null,
                        Estado = age.EstadoId,
                        Estado_Contrato = age.Estado.Descripcion,
                        Estado_Order = age.Estado.Orden,
                        UsuarioId = "",
                        ContratoSAP = null,
                        Ampliaciones = age.Ampliaciones,
                        Cuit = "",
                        Proveedor = age.Operador.Descripcion,
                        Corredor = "",
                        Comercial = age.Comercial == null ? "" : age.Comercial.Nombres + " " + age.Comercial.Apellido,
                        Material = age.Material == null ? "" : age.Material.Descripcion,
                        Campania = "",
                        Provincia = "",
                        TipoNegocio = "AGENTE COMPRAS",
                        Localidad = "",
                        Observacion = "",
                        FijacionDePrecioContratoId = null,
                        Sustentable = false,
                        Dolarizado = false,
                        Pesificado = false,
                        Negocio = null,
                        DestinoId = null,
                        DestinoDescripcion = "",
                        CantidadCamiones = null,
                        Consignatario = false,
                        PlanCanje = false,
                        CD = null,
                        Warrant = null,
                        PagoDirectoVendedor = null,
                        EstablecimientoPropio = null,
                        BoletoId = null,
                        BolsaId = null,
                        BoletoDescripcion = "",
                        BolsaDescripcion = "",
                        DesdeFijacion = null,
                        HastaFijacion = null,
                        CondicionFijacion = null,
                        CondicionFijacionDescripcion = "",
                        ClasificacionId = null,
                        ClasificacionDescripcion = "",
                        CalidadDescripcion = "",
                        MercsDeposito = null,
                        ComercialCreadorId = age.ComercialCreadorId,
                        ComercialCreador = age.ComercialCreador == null ? age.Comercial.Nombres + " " + age.Comercial.Apellido : age.ComercialCreador.Nombres + " " + age.ComercialCreador.Apellido,
                        ContratoCorredor = "",
                        ContratoVendedor = "",
                        SelCargoMOA = null,
                        SelCargoVendedor = null,
                        Posicion = age.Posicion,
                        TipoFason = "",
                        FasonId = 0,
                        Operador = age.Operador.Descripcion,
                        OperadorId = age.OperadorId,
                        AgenteId = age.Id,
                        PrecioNeto = null,
                        StandardCalidadId = null,
                        StandardDeCalidadDescripcion = "",
                        Pizarra = null,
                        PagoDiferido = null,
                        ZonaId = null,
                        ZonaDescripcion = "",
                        AcuerdoId = null,
                        ImporteFinanciero = null,
                        ImporteRedespacho = null,
                        PorcentajeComision = null,
                        ImporteComision = null,
                        ImporteBonificacion = null,
                        PorcentajeBonificacion = null,
                        NivelTarifa = "",
                        TarifaFlete = null,
                        Compensacion = null
                    };

                queryContratos = queryContratos.Union(queryAgente);
                var queryAcuerdo =
                    from acu in contexto.Set<ContratoAcuerdo>()
                    where equipo.Contains(acu.ComercialCreadorId)
                    select new BasicoContrato()
                    {
                        Id = acu.Id,
                        ContratoId = 0,
                        ProveedorId = 0,
                        CorredorId = acu.CorredorId ?? 0,
                        ComercialId = acu.ComercialCreadorId,
                        MaterialId = acu.MaterialId,
                        TipoNegocioId = 6,
                        Cantidad = acu.Cantidad,
                        Precio = acu.Precio,
                        PrecioPlazo = acu.Precio.ToString(),
                        FechaEntrega = null,
                        CampanaId = 0,
                        FechaDesde = DbFunctions.TruncateTime(acu.FechaDesde),
                        FechaHasta = DbFunctions.TruncateTime(acu.FechaHasta),
                        MonedaId = acu.MonedaId,
                        Moneda = acu.Moneda == null ? "" : acu.Moneda.Descripcion,
                        Fecha = DbFunctions.TruncateTime(acu.Fecha),
                        Hora = SqlFunctions.DateName("hour", acu.Fecha) + ":" + SqlFunctions.DateName("minute", acu.Fecha),
                        Fecha_Order = acu.Fecha,
                        GrupoCompra = 0,
                        GrupoCompraDescripcion = null,
                        ProvinciaId = null,
                        LocalidadId = null,
                        Base = null,
                        Importe_Sustentable = null,
                        MonedaId_Sustentable = "",
                        Moneda_Sustentable = "",
                        Fecha_Dolarizado = null,
                        Dias_Pesificado = null,
                        NoInformaSIO = null,
                        Estado = acu.EstadoId,
                        Estado_Contrato = acu.Estado.Descripcion,
                        Estado_Order = acu.Estado.Orden,
                        UsuarioId = "",
                        ContratoSAP = "",
                        Ampliaciones = 0,
                        Cuit = acu.Proveedor != null ? acu.Proveedor.CUIT : "",
                        Proveedor = acu.Proveedor!= null ? acu.Proveedor.RazonSocial:"",
                        Corredor = acu.Corredor!=null?acu.Corredor.RazonSocial:"",
                        Comercial = acu.Comercial == null ? "" : acu.Comercial.Nombres + " " + acu.Comercial.Apellido,
                        Material = acu.Material == null ? "" : acu.Material.Descripcion,
                        Campania = "",
                        Provincia = "",
                        TipoNegocio = "CONTRATO ACUERDO",
                        Localidad = "",
                        Observacion = "",
                        FijacionDePrecioContratoId = null,
                        Sustentable = false,
                        Dolarizado = false,
                        Pesificado = false,
                        Negocio = acu.Id.ToString(),
                        DestinoId = acu.DestinoId,
                        DestinoDescripcion = acu.Destino != null ? acu.Destino.Descripcion : "",
                        CantidadCamiones = null,
                        Consignatario = false,
                        PlanCanje = false,
                        CD = null,
                        Warrant = null,
                        PagoDirectoVendedor = null,
                        EstablecimientoPropio = null,
                        BoletoId = null,
                        BolsaId = null,
                        BoletoDescripcion = "",
                        BolsaDescripcion = "",
                        DesdeFijacion = null,
                        HastaFijacion = null,
                        CondicionFijacion = null,
                        CondicionFijacionDescripcion = "",
                        ClasificacionId = null,
                        ClasificacionDescripcion = "",
                        CalidadDescripcion = "",
                        MercsDeposito = null,
                        ComercialCreadorId = acu.ComercialCreadorId,
                        ComercialCreador = acu.Comercial == null ? acu.Comercial.Nombres + " " + acu.Comercial.Apellido : acu.Comercial.Nombres + " " + acu.Comercial.Apellido,
                        ContratoCorredor = "",
                        ContratoVendedor = "",
                        SelCargoMOA = null,
                        SelCargoVendedor = null,
                        Posicion = "",
                        TipoFason = "",
                        FasonId = 0,
                        Operador = "",
                        OperadorId = 0,
                        AgenteId = 0,
                        PrecioNeto = null,
                        StandardCalidadId = null,
                        StandardDeCalidadDescripcion = "",
                        Pizarra = null,
                        PagoDiferido = null,
                        ZonaId = null,
                        ZonaDescripcion = "",
                        AcuerdoId = acu.Id,
                        ImporteFinanciero = null,
                        ImporteRedespacho = null,
                        PorcentajeComision = null,
                        ImporteComision = null,
                        ImporteBonificacion = null,
                        PorcentajeBonificacion = null,
                        NivelTarifa = "",
                        TarifaFlete = null,
                        Compensacion = null
                    };

                queryContratos = queryContratos.Union(queryAcuerdo);
            }
            return new KendoGrid<BasicoContrato>(request, queryContratos);
        }

        public virtual KendoGrid<BasicoContrato> Ejecutar(DbContext contexto)
        {
            using (new TransactionScope(TransactionScopeOption.Required, new TransactionOptions { IsolationLevel = IsolationLevel.ReadUncommitted }))
            {
                return Query(contexto, request, perfilId, equipo, corredoresComercial);
            }
        }
    }
}
