//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Molinos.DataAgro.Agent.DatosDelComercial {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="namespace:dataagro", ConfigurationName="DatosDelComercial.SI_ZMPWS_DATAAGRO_DATOS_COMERCIALES")]
    public interface SI_ZMPWS_DATAAGRO_DATOS_COMERCIALES {
        
        // CODEGEN: Generating message contract since the operation SI_ZMPWS_DATAAGRO_DATOS_COMERCIALES is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Molinos.DataAgro.Agent.DatosDelComercial.SI_ZMPWS_DATAAGRO_DATOS_COMERCIALESResponse SI_ZMPWS_DATAAGRO_DATOS_COMERCIALES(Molinos.DataAgro.Agent.DatosDelComercial.SI_ZMPWS_DATAAGRO_DATOS_COMERCIALESRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<Molinos.DataAgro.Agent.DatosDelComercial.SI_ZMPWS_DATAAGRO_DATOS_COMERCIALESResponse> SI_ZMPWS_DATAAGRO_DATOS_COMERCIALESAsync(Molinos.DataAgro.Agent.DatosDelComercial.SI_ZMPWS_DATAAGRO_DATOS_COMERCIALESRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_MPRFC_DATOS_COMERCIAL : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iM_USUARIOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string IM_USUARIO {
            get {
                return this.iM_USUARIOField;
            }
            set {
                this.iM_USUARIOField = value;
                this.RaisePropertyChanged("IM_USUARIO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_MPRFC_DATOS_COMERCIALResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string eX_GRUPO_COMPRASField;
        
        private string eX_ZONAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string EX_GRUPO_COMPRAS {
            get {
                return this.eX_GRUPO_COMPRASField;
            }
            set {
                this.eX_GRUPO_COMPRASField = value;
                this.RaisePropertyChanged("EX_GRUPO_COMPRAS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string EX_ZONA {
            get {
                return this.eX_ZONAField;
            }
            set {
                this.eX_ZONAField = value;
                this.RaisePropertyChanged("EX_ZONA");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_ZMPWS_DATAAGRO_DATOS_COMERCIALESRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public Molinos.DataAgro.Agent.DatosDelComercial.Z_MPRFC_DATOS_COMERCIAL Z_MPRFC_DATOS_COMERCIAL;
        
        public SI_ZMPWS_DATAAGRO_DATOS_COMERCIALESRequest() {
        }
        
        public SI_ZMPWS_DATAAGRO_DATOS_COMERCIALESRequest(Molinos.DataAgro.Agent.DatosDelComercial.Z_MPRFC_DATOS_COMERCIAL Z_MPRFC_DATOS_COMERCIAL) {
            this.Z_MPRFC_DATOS_COMERCIAL = Z_MPRFC_DATOS_COMERCIAL;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_ZMPWS_DATAAGRO_DATOS_COMERCIALESResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public Molinos.DataAgro.Agent.DatosDelComercial.Z_MPRFC_DATOS_COMERCIALResponse Z_MPRFC_DATOS_COMERCIALResponse;
        
        public SI_ZMPWS_DATAAGRO_DATOS_COMERCIALESResponse() {
        }
        
        public SI_ZMPWS_DATAAGRO_DATOS_COMERCIALESResponse(Molinos.DataAgro.Agent.DatosDelComercial.Z_MPRFC_DATOS_COMERCIALResponse Z_MPRFC_DATOS_COMERCIALResponse) {
            this.Z_MPRFC_DATOS_COMERCIALResponse = Z_MPRFC_DATOS_COMERCIALResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_ZMPWS_DATAAGRO_DATOS_COMERCIALESChannel : Molinos.DataAgro.Agent.DatosDelComercial.SI_ZMPWS_DATAAGRO_DATOS_COMERCIALES, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_ZMPWS_DATAAGRO_DATOS_COMERCIALESClient : System.ServiceModel.ClientBase<Molinos.DataAgro.Agent.DatosDelComercial.SI_ZMPWS_DATAAGRO_DATOS_COMERCIALES>, Molinos.DataAgro.Agent.DatosDelComercial.SI_ZMPWS_DATAAGRO_DATOS_COMERCIALES {
        
        public SI_ZMPWS_DATAAGRO_DATOS_COMERCIALESClient() {
        }
        
        public SI_ZMPWS_DATAAGRO_DATOS_COMERCIALESClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SI_ZMPWS_DATAAGRO_DATOS_COMERCIALESClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_ZMPWS_DATAAGRO_DATOS_COMERCIALESClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_ZMPWS_DATAAGRO_DATOS_COMERCIALESClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Molinos.DataAgro.Agent.DatosDelComercial.SI_ZMPWS_DATAAGRO_DATOS_COMERCIALESResponse Molinos.DataAgro.Agent.DatosDelComercial.SI_ZMPWS_DATAAGRO_DATOS_COMERCIALES.SI_ZMPWS_DATAAGRO_DATOS_COMERCIALES(Molinos.DataAgro.Agent.DatosDelComercial.SI_ZMPWS_DATAAGRO_DATOS_COMERCIALESRequest request) {
            return base.Channel.SI_ZMPWS_DATAAGRO_DATOS_COMERCIALES(request);
        }
        
        public Molinos.DataAgro.Agent.DatosDelComercial.Z_MPRFC_DATOS_COMERCIALResponse SI_ZMPWS_DATAAGRO_DATOS_COMERCIALES(Molinos.DataAgro.Agent.DatosDelComercial.Z_MPRFC_DATOS_COMERCIAL Z_MPRFC_DATOS_COMERCIAL) {
            Molinos.DataAgro.Agent.DatosDelComercial.SI_ZMPWS_DATAAGRO_DATOS_COMERCIALESRequest inValue = new Molinos.DataAgro.Agent.DatosDelComercial.SI_ZMPWS_DATAAGRO_DATOS_COMERCIALESRequest();
            inValue.Z_MPRFC_DATOS_COMERCIAL = Z_MPRFC_DATOS_COMERCIAL;
            Molinos.DataAgro.Agent.DatosDelComercial.SI_ZMPWS_DATAAGRO_DATOS_COMERCIALESResponse retVal = ((Molinos.DataAgro.Agent.DatosDelComercial.SI_ZMPWS_DATAAGRO_DATOS_COMERCIALES)(this)).SI_ZMPWS_DATAAGRO_DATOS_COMERCIALES(inValue);
            return retVal.Z_MPRFC_DATOS_COMERCIALResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Molinos.DataAgro.Agent.DatosDelComercial.SI_ZMPWS_DATAAGRO_DATOS_COMERCIALESResponse> Molinos.DataAgro.Agent.DatosDelComercial.SI_ZMPWS_DATAAGRO_DATOS_COMERCIALES.SI_ZMPWS_DATAAGRO_DATOS_COMERCIALESAsync(Molinos.DataAgro.Agent.DatosDelComercial.SI_ZMPWS_DATAAGRO_DATOS_COMERCIALESRequest request) {
            return base.Channel.SI_ZMPWS_DATAAGRO_DATOS_COMERCIALESAsync(request);
        }
        
        public System.Threading.Tasks.Task<Molinos.DataAgro.Agent.DatosDelComercial.SI_ZMPWS_DATAAGRO_DATOS_COMERCIALESResponse> SI_ZMPWS_DATAAGRO_DATOS_COMERCIALESAsync(Molinos.DataAgro.Agent.DatosDelComercial.Z_MPRFC_DATOS_COMERCIAL Z_MPRFC_DATOS_COMERCIAL) {
            Molinos.DataAgro.Agent.DatosDelComercial.SI_ZMPWS_DATAAGRO_DATOS_COMERCIALESRequest inValue = new Molinos.DataAgro.Agent.DatosDelComercial.SI_ZMPWS_DATAAGRO_DATOS_COMERCIALESRequest();
            inValue.Z_MPRFC_DATOS_COMERCIAL = Z_MPRFC_DATOS_COMERCIAL;
            return ((Molinos.DataAgro.Agent.DatosDelComercial.SI_ZMPWS_DATAAGRO_DATOS_COMERCIALES)(this)).SI_ZMPWS_DATAAGRO_DATOS_COMERCIALESAsync(inValue);
        }
    }
}
