//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Molinos.DataAgro.Agent.EnviarBoleto {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="namespace:dataagro", ConfigurationName="EnviarBoleto.SI_ZMPWS_DATAAGRO_ENVIAR_BOLETOS_GENE")]
    public interface SI_ZMPWS_DATAAGRO_ENVIAR_BOLETOS_GENE {
        
        // CODEGEN: Generating message contract since the operation SI_ZMPWS_DATAAGRO_ENVIAR_BOLETOS_GENE is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Molinos.DataAgro.Agent.EnviarBoleto.SI_ZMPWS_DATAAGRO_ENVIAR_BOLETOS_GENEResponse SI_ZMPWS_DATAAGRO_ENVIAR_BOLETOS_GENE(Molinos.DataAgro.Agent.EnviarBoleto.SI_ZMPWS_DATAAGRO_ENVIAR_BOLETOS_GENERequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<Molinos.DataAgro.Agent.EnviarBoleto.SI_ZMPWS_DATAAGRO_ENVIAR_BOLETOS_GENEResponse> SI_ZMPWS_DATAAGRO_ENVIAR_BOLETOS_GENEAsync(Molinos.DataAgro.Agent.EnviarBoleto.SI_ZMPWS_DATAAGRO_ENVIAR_BOLETOS_GENERequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_MPRFC_ENVIAR_BOLETOS_GENE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iM_CONTRATOField;
        
        private string iM_ESTADOField;
        
        private string iM_ESTADO_DOCUMENTOField;
        
        private string iM_ESTADO_LOTEField;
        
        private string iM_FECHA_GENEField;
        
        private string iM_FIJACIONField;
        
        private string iM_GENERADOField;
        
        private string iM_HORA_GENEField;
        
        private string iM_ID_DOC_CONFIRMAField;
        
        private string iM_ID_LOTE_CONFIRMAField;
        
        private string iM_TIPO_BOLETOField;
        
        private string iM_VERSIONField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string IM_CONTRATO {
            get {
                return this.iM_CONTRATOField;
            }
            set {
                this.iM_CONTRATOField = value;
                this.RaisePropertyChanged("IM_CONTRATO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string IM_ESTADO {
            get {
                return this.iM_ESTADOField;
            }
            set {
                this.iM_ESTADOField = value;
                this.RaisePropertyChanged("IM_ESTADO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string IM_ESTADO_DOCUMENTO {
            get {
                return this.iM_ESTADO_DOCUMENTOField;
            }
            set {
                this.iM_ESTADO_DOCUMENTOField = value;
                this.RaisePropertyChanged("IM_ESTADO_DOCUMENTO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string IM_ESTADO_LOTE {
            get {
                return this.iM_ESTADO_LOTEField;
            }
            set {
                this.iM_ESTADO_LOTEField = value;
                this.RaisePropertyChanged("IM_ESTADO_LOTE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string IM_FECHA_GENE {
            get {
                return this.iM_FECHA_GENEField;
            }
            set {
                this.iM_FECHA_GENEField = value;
                this.RaisePropertyChanged("IM_FECHA_GENE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string IM_FIJACION {
            get {
                return this.iM_FIJACIONField;
            }
            set {
                this.iM_FIJACIONField = value;
                this.RaisePropertyChanged("IM_FIJACION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string IM_GENERADO {
            get {
                return this.iM_GENERADOField;
            }
            set {
                this.iM_GENERADOField = value;
                this.RaisePropertyChanged("IM_GENERADO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string IM_HORA_GENE {
            get {
                return this.iM_HORA_GENEField;
            }
            set {
                this.iM_HORA_GENEField = value;
                this.RaisePropertyChanged("IM_HORA_GENE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string IM_ID_DOC_CONFIRMA {
            get {
                return this.iM_ID_DOC_CONFIRMAField;
            }
            set {
                this.iM_ID_DOC_CONFIRMAField = value;
                this.RaisePropertyChanged("IM_ID_DOC_CONFIRMA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string IM_ID_LOTE_CONFIRMA {
            get {
                return this.iM_ID_LOTE_CONFIRMAField;
            }
            set {
                this.iM_ID_LOTE_CONFIRMAField = value;
                this.RaisePropertyChanged("IM_ID_LOTE_CONFIRMA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string IM_TIPO_BOLETO {
            get {
                return this.iM_TIPO_BOLETOField;
            }
            set {
                this.iM_TIPO_BOLETOField = value;
                this.RaisePropertyChanged("IM_TIPO_BOLETO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string IM_VERSION {
            get {
                return this.iM_VERSIONField;
            }
            set {
                this.iM_VERSIONField = value;
                this.RaisePropertyChanged("IM_VERSION");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_MPRFC_ENVIAR_BOLETOS_GENEResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string eX_MENSAJEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string EX_MENSAJE {
            get {
                return this.eX_MENSAJEField;
            }
            set {
                this.eX_MENSAJEField = value;
                this.RaisePropertyChanged("EX_MENSAJE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_ZMPWS_DATAAGRO_ENVIAR_BOLETOS_GENERequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public Molinos.DataAgro.Agent.EnviarBoleto.Z_MPRFC_ENVIAR_BOLETOS_GENE Z_MPRFC_ENVIAR_BOLETOS_GENE;
        
        public SI_ZMPWS_DATAAGRO_ENVIAR_BOLETOS_GENERequest() {
        }
        
        public SI_ZMPWS_DATAAGRO_ENVIAR_BOLETOS_GENERequest(Molinos.DataAgro.Agent.EnviarBoleto.Z_MPRFC_ENVIAR_BOLETOS_GENE Z_MPRFC_ENVIAR_BOLETOS_GENE) {
            this.Z_MPRFC_ENVIAR_BOLETOS_GENE = Z_MPRFC_ENVIAR_BOLETOS_GENE;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_ZMPWS_DATAAGRO_ENVIAR_BOLETOS_GENEResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public Molinos.DataAgro.Agent.EnviarBoleto.Z_MPRFC_ENVIAR_BOLETOS_GENEResponse Z_MPRFC_ENVIAR_BOLETOS_GENEResponse;
        
        public SI_ZMPWS_DATAAGRO_ENVIAR_BOLETOS_GENEResponse() {
        }
        
        public SI_ZMPWS_DATAAGRO_ENVIAR_BOLETOS_GENEResponse(Molinos.DataAgro.Agent.EnviarBoleto.Z_MPRFC_ENVIAR_BOLETOS_GENEResponse Z_MPRFC_ENVIAR_BOLETOS_GENEResponse) {
            this.Z_MPRFC_ENVIAR_BOLETOS_GENEResponse = Z_MPRFC_ENVIAR_BOLETOS_GENEResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_ZMPWS_DATAAGRO_ENVIAR_BOLETOS_GENEChannel : Molinos.DataAgro.Agent.EnviarBoleto.SI_ZMPWS_DATAAGRO_ENVIAR_BOLETOS_GENE, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_ZMPWS_DATAAGRO_ENVIAR_BOLETOS_GENEClient : System.ServiceModel.ClientBase<Molinos.DataAgro.Agent.EnviarBoleto.SI_ZMPWS_DATAAGRO_ENVIAR_BOLETOS_GENE>, Molinos.DataAgro.Agent.EnviarBoleto.SI_ZMPWS_DATAAGRO_ENVIAR_BOLETOS_GENE {
        
        public SI_ZMPWS_DATAAGRO_ENVIAR_BOLETOS_GENEClient() {
        }
        
        public SI_ZMPWS_DATAAGRO_ENVIAR_BOLETOS_GENEClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SI_ZMPWS_DATAAGRO_ENVIAR_BOLETOS_GENEClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_ZMPWS_DATAAGRO_ENVIAR_BOLETOS_GENEClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_ZMPWS_DATAAGRO_ENVIAR_BOLETOS_GENEClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Molinos.DataAgro.Agent.EnviarBoleto.SI_ZMPWS_DATAAGRO_ENVIAR_BOLETOS_GENEResponse Molinos.DataAgro.Agent.EnviarBoleto.SI_ZMPWS_DATAAGRO_ENVIAR_BOLETOS_GENE.SI_ZMPWS_DATAAGRO_ENVIAR_BOLETOS_GENE(Molinos.DataAgro.Agent.EnviarBoleto.SI_ZMPWS_DATAAGRO_ENVIAR_BOLETOS_GENERequest request) {
            return base.Channel.SI_ZMPWS_DATAAGRO_ENVIAR_BOLETOS_GENE(request);
        }
        
        public Molinos.DataAgro.Agent.EnviarBoleto.Z_MPRFC_ENVIAR_BOLETOS_GENEResponse SI_ZMPWS_DATAAGRO_ENVIAR_BOLETOS_GENE(Molinos.DataAgro.Agent.EnviarBoleto.Z_MPRFC_ENVIAR_BOLETOS_GENE Z_MPRFC_ENVIAR_BOLETOS_GENE) {
            Molinos.DataAgro.Agent.EnviarBoleto.SI_ZMPWS_DATAAGRO_ENVIAR_BOLETOS_GENERequest inValue = new Molinos.DataAgro.Agent.EnviarBoleto.SI_ZMPWS_DATAAGRO_ENVIAR_BOLETOS_GENERequest();
            inValue.Z_MPRFC_ENVIAR_BOLETOS_GENE = Z_MPRFC_ENVIAR_BOLETOS_GENE;
            Molinos.DataAgro.Agent.EnviarBoleto.SI_ZMPWS_DATAAGRO_ENVIAR_BOLETOS_GENEResponse retVal = ((Molinos.DataAgro.Agent.EnviarBoleto.SI_ZMPWS_DATAAGRO_ENVIAR_BOLETOS_GENE)(this)).SI_ZMPWS_DATAAGRO_ENVIAR_BOLETOS_GENE(inValue);
            return retVal.Z_MPRFC_ENVIAR_BOLETOS_GENEResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Molinos.DataAgro.Agent.EnviarBoleto.SI_ZMPWS_DATAAGRO_ENVIAR_BOLETOS_GENEResponse> Molinos.DataAgro.Agent.EnviarBoleto.SI_ZMPWS_DATAAGRO_ENVIAR_BOLETOS_GENE.SI_ZMPWS_DATAAGRO_ENVIAR_BOLETOS_GENEAsync(Molinos.DataAgro.Agent.EnviarBoleto.SI_ZMPWS_DATAAGRO_ENVIAR_BOLETOS_GENERequest request) {
            return base.Channel.SI_ZMPWS_DATAAGRO_ENVIAR_BOLETOS_GENEAsync(request);
        }
        
        public System.Threading.Tasks.Task<Molinos.DataAgro.Agent.EnviarBoleto.SI_ZMPWS_DATAAGRO_ENVIAR_BOLETOS_GENEResponse> SI_ZMPWS_DATAAGRO_ENVIAR_BOLETOS_GENEAsync(Molinos.DataAgro.Agent.EnviarBoleto.Z_MPRFC_ENVIAR_BOLETOS_GENE Z_MPRFC_ENVIAR_BOLETOS_GENE) {
            Molinos.DataAgro.Agent.EnviarBoleto.SI_ZMPWS_DATAAGRO_ENVIAR_BOLETOS_GENERequest inValue = new Molinos.DataAgro.Agent.EnviarBoleto.SI_ZMPWS_DATAAGRO_ENVIAR_BOLETOS_GENERequest();
            inValue.Z_MPRFC_ENVIAR_BOLETOS_GENE = Z_MPRFC_ENVIAR_BOLETOS_GENE;
            return ((Molinos.DataAgro.Agent.EnviarBoleto.SI_ZMPWS_DATAAGRO_ENVIAR_BOLETOS_GENE)(this)).SI_ZMPWS_DATAAGRO_ENVIAR_BOLETOS_GENEAsync(inValue);
        }
    }
}
