//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Molinos.DataAgro.Agent.ValidarPesificaciones {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="namespace:dataagro", ConfigurationName="ValidarPesificaciones.SI_ZMPWS_DATAAGRO_VALIDAR_PESIFICACIONES")]
    public interface SI_ZMPWS_DATAAGRO_VALIDAR_PESIFICACIONES {
        
        // CODEGEN: Generating message contract since the operation SI_ZMPWS_DATAAGRO_VALIDAR_PESIFICACIONES is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Molinos.DataAgro.Agent.ValidarPesificaciones.SI_ZMPWS_DATAAGRO_VALIDAR_PESIFICACIONESResponse SI_ZMPWS_DATAAGRO_VALIDAR_PESIFICACIONES(Molinos.DataAgro.Agent.ValidarPesificaciones.SI_ZMPWS_DATAAGRO_VALIDAR_PESIFICACIONESRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<Molinos.DataAgro.Agent.ValidarPesificaciones.SI_ZMPWS_DATAAGRO_VALIDAR_PESIFICACIONESResponse> SI_ZMPWS_DATAAGRO_VALIDAR_PESIFICACIONESAsync(Molinos.DataAgro.Agent.ValidarPesificaciones.SI_ZMPWS_DATAAGRO_VALIDAR_PESIFICACIONESRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_MPRFC_VALIDAR_PESIFICACIONES : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iM_CONTRATOField;
        
        private string iM_PEDIDOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string IM_CONTRATO {
            get {
                return this.iM_CONTRATOField;
            }
            set {
                this.iM_CONTRATOField = value;
                this.RaisePropertyChanged("IM_CONTRATO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string IM_PEDIDO {
            get {
                return this.iM_PEDIDOField;
            }
            set {
                this.iM_PEDIDOField = value;
                this.RaisePropertyChanged("IM_PEDIDO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_MPRFC_VALIDAR_PESIFICACIONESResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string eX_MENSAJEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string EX_MENSAJE {
            get {
                return this.eX_MENSAJEField;
            }
            set {
                this.eX_MENSAJEField = value;
                this.RaisePropertyChanged("EX_MENSAJE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_ZMPWS_DATAAGRO_VALIDAR_PESIFICACIONESRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public Molinos.DataAgro.Agent.ValidarPesificaciones.Z_MPRFC_VALIDAR_PESIFICACIONES Z_MPRFC_VALIDAR_PESIFICACIONES;
        
        public SI_ZMPWS_DATAAGRO_VALIDAR_PESIFICACIONESRequest() {
        }
        
        public SI_ZMPWS_DATAAGRO_VALIDAR_PESIFICACIONESRequest(Molinos.DataAgro.Agent.ValidarPesificaciones.Z_MPRFC_VALIDAR_PESIFICACIONES Z_MPRFC_VALIDAR_PESIFICACIONES) {
            this.Z_MPRFC_VALIDAR_PESIFICACIONES = Z_MPRFC_VALIDAR_PESIFICACIONES;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_ZMPWS_DATAAGRO_VALIDAR_PESIFICACIONESResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public Molinos.DataAgro.Agent.ValidarPesificaciones.Z_MPRFC_VALIDAR_PESIFICACIONESResponse Z_MPRFC_VALIDAR_PESIFICACIONESResponse;
        
        public SI_ZMPWS_DATAAGRO_VALIDAR_PESIFICACIONESResponse() {
        }
        
        public SI_ZMPWS_DATAAGRO_VALIDAR_PESIFICACIONESResponse(Molinos.DataAgro.Agent.ValidarPesificaciones.Z_MPRFC_VALIDAR_PESIFICACIONESResponse Z_MPRFC_VALIDAR_PESIFICACIONESResponse) {
            this.Z_MPRFC_VALIDAR_PESIFICACIONESResponse = Z_MPRFC_VALIDAR_PESIFICACIONESResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_ZMPWS_DATAAGRO_VALIDAR_PESIFICACIONESChannel : Molinos.DataAgro.Agent.ValidarPesificaciones.SI_ZMPWS_DATAAGRO_VALIDAR_PESIFICACIONES, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_ZMPWS_DATAAGRO_VALIDAR_PESIFICACIONESClient : System.ServiceModel.ClientBase<Molinos.DataAgro.Agent.ValidarPesificaciones.SI_ZMPWS_DATAAGRO_VALIDAR_PESIFICACIONES>, Molinos.DataAgro.Agent.ValidarPesificaciones.SI_ZMPWS_DATAAGRO_VALIDAR_PESIFICACIONES {
        
        public SI_ZMPWS_DATAAGRO_VALIDAR_PESIFICACIONESClient() {
        }
        
        public SI_ZMPWS_DATAAGRO_VALIDAR_PESIFICACIONESClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SI_ZMPWS_DATAAGRO_VALIDAR_PESIFICACIONESClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_ZMPWS_DATAAGRO_VALIDAR_PESIFICACIONESClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_ZMPWS_DATAAGRO_VALIDAR_PESIFICACIONESClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Molinos.DataAgro.Agent.ValidarPesificaciones.SI_ZMPWS_DATAAGRO_VALIDAR_PESIFICACIONESResponse Molinos.DataAgro.Agent.ValidarPesificaciones.SI_ZMPWS_DATAAGRO_VALIDAR_PESIFICACIONES.SI_ZMPWS_DATAAGRO_VALIDAR_PESIFICACIONES(Molinos.DataAgro.Agent.ValidarPesificaciones.SI_ZMPWS_DATAAGRO_VALIDAR_PESIFICACIONESRequest request) {
            return base.Channel.SI_ZMPWS_DATAAGRO_VALIDAR_PESIFICACIONES(request);
        }
        
        public Molinos.DataAgro.Agent.ValidarPesificaciones.Z_MPRFC_VALIDAR_PESIFICACIONESResponse SI_ZMPWS_DATAAGRO_VALIDAR_PESIFICACIONES(Molinos.DataAgro.Agent.ValidarPesificaciones.Z_MPRFC_VALIDAR_PESIFICACIONES Z_MPRFC_VALIDAR_PESIFICACIONES) {
            Molinos.DataAgro.Agent.ValidarPesificaciones.SI_ZMPWS_DATAAGRO_VALIDAR_PESIFICACIONESRequest inValue = new Molinos.DataAgro.Agent.ValidarPesificaciones.SI_ZMPWS_DATAAGRO_VALIDAR_PESIFICACIONESRequest();
            inValue.Z_MPRFC_VALIDAR_PESIFICACIONES = Z_MPRFC_VALIDAR_PESIFICACIONES;
            Molinos.DataAgro.Agent.ValidarPesificaciones.SI_ZMPWS_DATAAGRO_VALIDAR_PESIFICACIONESResponse retVal = ((Molinos.DataAgro.Agent.ValidarPesificaciones.SI_ZMPWS_DATAAGRO_VALIDAR_PESIFICACIONES)(this)).SI_ZMPWS_DATAAGRO_VALIDAR_PESIFICACIONES(inValue);
            return retVal.Z_MPRFC_VALIDAR_PESIFICACIONESResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Molinos.DataAgro.Agent.ValidarPesificaciones.SI_ZMPWS_DATAAGRO_VALIDAR_PESIFICACIONESResponse> Molinos.DataAgro.Agent.ValidarPesificaciones.SI_ZMPWS_DATAAGRO_VALIDAR_PESIFICACIONES.SI_ZMPWS_DATAAGRO_VALIDAR_PESIFICACIONESAsync(Molinos.DataAgro.Agent.ValidarPesificaciones.SI_ZMPWS_DATAAGRO_VALIDAR_PESIFICACIONESRequest request) {
            return base.Channel.SI_ZMPWS_DATAAGRO_VALIDAR_PESIFICACIONESAsync(request);
        }
        
        public System.Threading.Tasks.Task<Molinos.DataAgro.Agent.ValidarPesificaciones.SI_ZMPWS_DATAAGRO_VALIDAR_PESIFICACIONESResponse> SI_ZMPWS_DATAAGRO_VALIDAR_PESIFICACIONESAsync(Molinos.DataAgro.Agent.ValidarPesificaciones.Z_MPRFC_VALIDAR_PESIFICACIONES Z_MPRFC_VALIDAR_PESIFICACIONES) {
            Molinos.DataAgro.Agent.ValidarPesificaciones.SI_ZMPWS_DATAAGRO_VALIDAR_PESIFICACIONESRequest inValue = new Molinos.DataAgro.Agent.ValidarPesificaciones.SI_ZMPWS_DATAAGRO_VALIDAR_PESIFICACIONESRequest();
            inValue.Z_MPRFC_VALIDAR_PESIFICACIONES = Z_MPRFC_VALIDAR_PESIFICACIONES;
            return ((Molinos.DataAgro.Agent.ValidarPesificaciones.SI_ZMPWS_DATAAGRO_VALIDAR_PESIFICACIONES)(this)).SI_ZMPWS_DATAAGRO_VALIDAR_PESIFICACIONESAsync(inValue);
        }
    }
}
