//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Molinos.DataAgro.Agent.ContratosAPesificar {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="namespace:dataagro", ConfigurationName="ContratosAPesificar.SI_ZMPWS_DATAAGRO_LISTA_PROVEEDORES")]
    public interface SI_ZMPWS_DATAAGRO_LISTA_PROVEEDORES {
        
        // CODEGEN: Generating message contract since the operation SI_ZMPWS_DATAAGRO_LISTA_PROVEEDORES is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Molinos.DataAgro.Agent.ContratosAPesificar.SI_ZMPWS_DATAAGRO_LISTA_PROVEEDORESResponse SI_ZMPWS_DATAAGRO_LISTA_PROVEEDORES(Molinos.DataAgro.Agent.ContratosAPesificar.SI_ZMPWS_DATAAGRO_LISTA_PROVEEDORESRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<Molinos.DataAgro.Agent.ContratosAPesificar.SI_ZMPWS_DATAAGRO_LISTA_PROVEEDORESResponse> SI_ZMPWS_DATAAGRO_LISTA_PROVEEDORESAsync(Molinos.DataAgro.Agent.ContratosAPesificar.SI_ZMPWS_DATAAGRO_LISTA_PROVEEDORESRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_MPRFC_LISTA_PROVEEDORES : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] iM_PROVEEDORESField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] IM_PROVEEDORES {
            get {
                return this.iM_PROVEEDORESField;
            }
            set {
                this.iM_PROVEEDORESField = value;
                this.RaisePropertyChanged("IM_PROVEEDORES");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMPES6360 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cONTRATOField;
        
        private string fIJACIONField;
        
        private string fECHA_FIJACIONField;
        
        private string fECHA_ULT_APLIField;
        
        private string dOLARIZADOField;
        
        private string dOLARIZADO_NO_PRODField;
        
        private string fECHA_HASTA_DOLField;
        
        private string dOLARIZADO_EXPRESSField;
        
        private decimal pRECIOField;
        
        private decimal pES_VENCIDAField;
        
        private decimal pES_NO_VENField;
        
        private decimal cANT_PENDIENTEField;
        
        private string cUIT_VENDEDORField;
        
        private string nOM_VENDField;
        
        private string cUIT_CORREDORField;
        
        private string nOM_CORREDORField;
        
        private string mATERIALField;
        
        private string cOMERCIALField;
        
        private string uNIDADField;
        
        private string mONEDAField;
        
        private string cLASIFICACIONField;
        
        private string aNTICIPOField;
        
        private string cESIONField;
        
        private string sTATUSField;
        
        private decimal cANTIDADField;
        
        private string cON_PRECIOField;
        
        private decimal cANT_RECIBIDAField;
        
        private decimal iMP_RECIBIDOField;
        
        private decimal cANT_LIQUIDADAField;
        
        private decimal mONTO_PENDIENTEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CONTRATO {
            get {
                return this.cONTRATOField;
            }
            set {
                this.cONTRATOField = value;
                this.RaisePropertyChanged("CONTRATO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string FIJACION {
            get {
                return this.fIJACIONField;
            }
            set {
                this.fIJACIONField = value;
                this.RaisePropertyChanged("FIJACION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string FECHA_FIJACION {
            get {
                return this.fECHA_FIJACIONField;
            }
            set {
                this.fECHA_FIJACIONField = value;
                this.RaisePropertyChanged("FECHA_FIJACION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string FECHA_ULT_APLI {
            get {
                return this.fECHA_ULT_APLIField;
            }
            set {
                this.fECHA_ULT_APLIField = value;
                this.RaisePropertyChanged("FECHA_ULT_APLI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string DOLARIZADO {
            get {
                return this.dOLARIZADOField;
            }
            set {
                this.dOLARIZADOField = value;
                this.RaisePropertyChanged("DOLARIZADO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string DOLARIZADO_NO_PROD {
            get {
                return this.dOLARIZADO_NO_PRODField;
            }
            set {
                this.dOLARIZADO_NO_PRODField = value;
                this.RaisePropertyChanged("DOLARIZADO_NO_PROD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string FECHA_HASTA_DOL {
            get {
                return this.fECHA_HASTA_DOLField;
            }
            set {
                this.fECHA_HASTA_DOLField = value;
                this.RaisePropertyChanged("FECHA_HASTA_DOL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string DOLARIZADO_EXPRESS {
            get {
                return this.dOLARIZADO_EXPRESSField;
            }
            set {
                this.dOLARIZADO_EXPRESSField = value;
                this.RaisePropertyChanged("DOLARIZADO_EXPRESS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public decimal PRECIO {
            get {
                return this.pRECIOField;
            }
            set {
                this.pRECIOField = value;
                this.RaisePropertyChanged("PRECIO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public decimal PES_VENCIDA {
            get {
                return this.pES_VENCIDAField;
            }
            set {
                this.pES_VENCIDAField = value;
                this.RaisePropertyChanged("PES_VENCIDA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public decimal PES_NO_VEN {
            get {
                return this.pES_NO_VENField;
            }
            set {
                this.pES_NO_VENField = value;
                this.RaisePropertyChanged("PES_NO_VEN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public decimal CANT_PENDIENTE {
            get {
                return this.cANT_PENDIENTEField;
            }
            set {
                this.cANT_PENDIENTEField = value;
                this.RaisePropertyChanged("CANT_PENDIENTE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string CUIT_VENDEDOR {
            get {
                return this.cUIT_VENDEDORField;
            }
            set {
                this.cUIT_VENDEDORField = value;
                this.RaisePropertyChanged("CUIT_VENDEDOR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string NOM_VEND {
            get {
                return this.nOM_VENDField;
            }
            set {
                this.nOM_VENDField = value;
                this.RaisePropertyChanged("NOM_VEND");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string CUIT_CORREDOR {
            get {
                return this.cUIT_CORREDORField;
            }
            set {
                this.cUIT_CORREDORField = value;
                this.RaisePropertyChanged("CUIT_CORREDOR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string NOM_CORREDOR {
            get {
                return this.nOM_CORREDORField;
            }
            set {
                this.nOM_CORREDORField = value;
                this.RaisePropertyChanged("NOM_CORREDOR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string MATERIAL {
            get {
                return this.mATERIALField;
            }
            set {
                this.mATERIALField = value;
                this.RaisePropertyChanged("MATERIAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string COMERCIAL {
            get {
                return this.cOMERCIALField;
            }
            set {
                this.cOMERCIALField = value;
                this.RaisePropertyChanged("COMERCIAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string UNIDAD {
            get {
                return this.uNIDADField;
            }
            set {
                this.uNIDADField = value;
                this.RaisePropertyChanged("UNIDAD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string MONEDA {
            get {
                return this.mONEDAField;
            }
            set {
                this.mONEDAField = value;
                this.RaisePropertyChanged("MONEDA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string CLASIFICACION {
            get {
                return this.cLASIFICACIONField;
            }
            set {
                this.cLASIFICACIONField = value;
                this.RaisePropertyChanged("CLASIFICACION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string ANTICIPO {
            get {
                return this.aNTICIPOField;
            }
            set {
                this.aNTICIPOField = value;
                this.RaisePropertyChanged("ANTICIPO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string CESION {
            get {
                return this.cESIONField;
            }
            set {
                this.cESIONField = value;
                this.RaisePropertyChanged("CESION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string STATUS {
            get {
                return this.sTATUSField;
            }
            set {
                this.sTATUSField = value;
                this.RaisePropertyChanged("STATUS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public decimal CANTIDAD {
            get {
                return this.cANTIDADField;
            }
            set {
                this.cANTIDADField = value;
                this.RaisePropertyChanged("CANTIDAD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string CON_PRECIO {
            get {
                return this.cON_PRECIOField;
            }
            set {
                this.cON_PRECIOField = value;
                this.RaisePropertyChanged("CON_PRECIO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public decimal CANT_RECIBIDA {
            get {
                return this.cANT_RECIBIDAField;
            }
            set {
                this.cANT_RECIBIDAField = value;
                this.RaisePropertyChanged("CANT_RECIBIDA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public decimal IMP_RECIBIDO {
            get {
                return this.iMP_RECIBIDOField;
            }
            set {
                this.iMP_RECIBIDOField = value;
                this.RaisePropertyChanged("IMP_RECIBIDO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public decimal CANT_LIQUIDADA {
            get {
                return this.cANT_LIQUIDADAField;
            }
            set {
                this.cANT_LIQUIDADAField = value;
                this.RaisePropertyChanged("CANT_LIQUIDADA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public decimal MONTO_PENDIENTE {
            get {
                return this.mONTO_PENDIENTEField;
            }
            set {
                this.mONTO_PENDIENTEField = value;
                this.RaisePropertyChanged("MONTO_PENDIENTE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_MPRFC_LISTA_PROVEEDORESResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZMPES6360[] eX_SALIDAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZMPES6360[] EX_SALIDA {
            get {
                return this.eX_SALIDAField;
            }
            set {
                this.eX_SALIDAField = value;
                this.RaisePropertyChanged("EX_SALIDA");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_ZMPWS_DATAAGRO_LISTA_PROVEEDORESRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public Molinos.DataAgro.Agent.ContratosAPesificar.Z_MPRFC_LISTA_PROVEEDORES Z_MPRFC_LISTA_PROVEEDORES;
        
        public SI_ZMPWS_DATAAGRO_LISTA_PROVEEDORESRequest() {
        }
        
        public SI_ZMPWS_DATAAGRO_LISTA_PROVEEDORESRequest(Molinos.DataAgro.Agent.ContratosAPesificar.Z_MPRFC_LISTA_PROVEEDORES Z_MPRFC_LISTA_PROVEEDORES) {
            this.Z_MPRFC_LISTA_PROVEEDORES = Z_MPRFC_LISTA_PROVEEDORES;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_ZMPWS_DATAAGRO_LISTA_PROVEEDORESResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public Molinos.DataAgro.Agent.ContratosAPesificar.Z_MPRFC_LISTA_PROVEEDORESResponse Z_MPRFC_LISTA_PROVEEDORESResponse;
        
        public SI_ZMPWS_DATAAGRO_LISTA_PROVEEDORESResponse() {
        }
        
        public SI_ZMPWS_DATAAGRO_LISTA_PROVEEDORESResponse(Molinos.DataAgro.Agent.ContratosAPesificar.Z_MPRFC_LISTA_PROVEEDORESResponse Z_MPRFC_LISTA_PROVEEDORESResponse) {
            this.Z_MPRFC_LISTA_PROVEEDORESResponse = Z_MPRFC_LISTA_PROVEEDORESResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_ZMPWS_DATAAGRO_LISTA_PROVEEDORESChannel : Molinos.DataAgro.Agent.ContratosAPesificar.SI_ZMPWS_DATAAGRO_LISTA_PROVEEDORES, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_ZMPWS_DATAAGRO_LISTA_PROVEEDORESClient : System.ServiceModel.ClientBase<Molinos.DataAgro.Agent.ContratosAPesificar.SI_ZMPWS_DATAAGRO_LISTA_PROVEEDORES>, Molinos.DataAgro.Agent.ContratosAPesificar.SI_ZMPWS_DATAAGRO_LISTA_PROVEEDORES {
        
        public SI_ZMPWS_DATAAGRO_LISTA_PROVEEDORESClient() {
        }
        
        public SI_ZMPWS_DATAAGRO_LISTA_PROVEEDORESClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SI_ZMPWS_DATAAGRO_LISTA_PROVEEDORESClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_ZMPWS_DATAAGRO_LISTA_PROVEEDORESClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_ZMPWS_DATAAGRO_LISTA_PROVEEDORESClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Molinos.DataAgro.Agent.ContratosAPesificar.SI_ZMPWS_DATAAGRO_LISTA_PROVEEDORESResponse Molinos.DataAgro.Agent.ContratosAPesificar.SI_ZMPWS_DATAAGRO_LISTA_PROVEEDORES.SI_ZMPWS_DATAAGRO_LISTA_PROVEEDORES(Molinos.DataAgro.Agent.ContratosAPesificar.SI_ZMPWS_DATAAGRO_LISTA_PROVEEDORESRequest request) {
            return base.Channel.SI_ZMPWS_DATAAGRO_LISTA_PROVEEDORES(request);
        }
        
        public Molinos.DataAgro.Agent.ContratosAPesificar.Z_MPRFC_LISTA_PROVEEDORESResponse SI_ZMPWS_DATAAGRO_LISTA_PROVEEDORES(Molinos.DataAgro.Agent.ContratosAPesificar.Z_MPRFC_LISTA_PROVEEDORES Z_MPRFC_LISTA_PROVEEDORES) {
            Molinos.DataAgro.Agent.ContratosAPesificar.SI_ZMPWS_DATAAGRO_LISTA_PROVEEDORESRequest inValue = new Molinos.DataAgro.Agent.ContratosAPesificar.SI_ZMPWS_DATAAGRO_LISTA_PROVEEDORESRequest();
            inValue.Z_MPRFC_LISTA_PROVEEDORES = Z_MPRFC_LISTA_PROVEEDORES;
            Molinos.DataAgro.Agent.ContratosAPesificar.SI_ZMPWS_DATAAGRO_LISTA_PROVEEDORESResponse retVal = ((Molinos.DataAgro.Agent.ContratosAPesificar.SI_ZMPWS_DATAAGRO_LISTA_PROVEEDORES)(this)).SI_ZMPWS_DATAAGRO_LISTA_PROVEEDORES(inValue);
            return retVal.Z_MPRFC_LISTA_PROVEEDORESResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Molinos.DataAgro.Agent.ContratosAPesificar.SI_ZMPWS_DATAAGRO_LISTA_PROVEEDORESResponse> Molinos.DataAgro.Agent.ContratosAPesificar.SI_ZMPWS_DATAAGRO_LISTA_PROVEEDORES.SI_ZMPWS_DATAAGRO_LISTA_PROVEEDORESAsync(Molinos.DataAgro.Agent.ContratosAPesificar.SI_ZMPWS_DATAAGRO_LISTA_PROVEEDORESRequest request) {
            return base.Channel.SI_ZMPWS_DATAAGRO_LISTA_PROVEEDORESAsync(request);
        }
        
        public System.Threading.Tasks.Task<Molinos.DataAgro.Agent.ContratosAPesificar.SI_ZMPWS_DATAAGRO_LISTA_PROVEEDORESResponse> SI_ZMPWS_DATAAGRO_LISTA_PROVEEDORESAsync(Molinos.DataAgro.Agent.ContratosAPesificar.Z_MPRFC_LISTA_PROVEEDORES Z_MPRFC_LISTA_PROVEEDORES) {
            Molinos.DataAgro.Agent.ContratosAPesificar.SI_ZMPWS_DATAAGRO_LISTA_PROVEEDORESRequest inValue = new Molinos.DataAgro.Agent.ContratosAPesificar.SI_ZMPWS_DATAAGRO_LISTA_PROVEEDORESRequest();
            inValue.Z_MPRFC_LISTA_PROVEEDORES = Z_MPRFC_LISTA_PROVEEDORES;
            return ((Molinos.DataAgro.Agent.ContratosAPesificar.SI_ZMPWS_DATAAGRO_LISTA_PROVEEDORES)(this)).SI_ZMPWS_DATAAGRO_LISTA_PROVEEDORESAsync(inValue);
        }
    }
}
