//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Molinos.DataAgro.Agent.AnulacionContratos {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="namespace:dataagro", ConfigurationName="AnulacionContratos.SI_ZMPWS_DATAAGRO_ANULACION_CONTRATO")]
    public interface SI_ZMPWS_DATAAGRO_ANULACION_CONTRATO {
        
        // CODEGEN: Generating message contract since the operation SI_ZMPWS_DATAAGRO_ANULACION_CONTRATO is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Molinos.DataAgro.Agent.AnulacionContratos.SI_ZMPWS_DATAAGRO_ANULACION_CONTRATOResponse SI_ZMPWS_DATAAGRO_ANULACION_CONTRATO(Molinos.DataAgro.Agent.AnulacionContratos.SI_ZMPWS_DATAAGRO_ANULACION_CONTRATORequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<Molinos.DataAgro.Agent.AnulacionContratos.SI_ZMPWS_DATAAGRO_ANULACION_CONTRATOResponse> SI_ZMPWS_DATAAGRO_ANULACION_CONTRATOAsync(Molinos.DataAgro.Agent.AnulacionContratos.SI_ZMPWS_DATAAGRO_ANULACION_CONTRATORequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_MPRFC_ANULACION_CONTRATO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iM_CONTRATOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string IM_CONTRATO {
            get {
                return this.iM_CONTRATOField;
            }
            set {
                this.iM_CONTRATOField = value;
                this.RaisePropertyChanged("IM_CONTRATO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_MPRFC_ANULACION_CONTRATOResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string eX_MENSAJEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string EX_MENSAJE {
            get {
                return this.eX_MENSAJEField;
            }
            set {
                this.eX_MENSAJEField = value;
                this.RaisePropertyChanged("EX_MENSAJE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_ZMPWS_DATAAGRO_ANULACION_CONTRATORequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public Molinos.DataAgro.Agent.AnulacionContratos.Z_MPRFC_ANULACION_CONTRATO Z_MPRFC_ANULACION_CONTRATO;
        
        public SI_ZMPWS_DATAAGRO_ANULACION_CONTRATORequest() {
        }
        
        public SI_ZMPWS_DATAAGRO_ANULACION_CONTRATORequest(Molinos.DataAgro.Agent.AnulacionContratos.Z_MPRFC_ANULACION_CONTRATO Z_MPRFC_ANULACION_CONTRATO) {
            this.Z_MPRFC_ANULACION_CONTRATO = Z_MPRFC_ANULACION_CONTRATO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_ZMPWS_DATAAGRO_ANULACION_CONTRATOResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public Molinos.DataAgro.Agent.AnulacionContratos.Z_MPRFC_ANULACION_CONTRATOResponse Z_MPRFC_ANULACION_CONTRATOResponse;
        
        public SI_ZMPWS_DATAAGRO_ANULACION_CONTRATOResponse() {
        }
        
        public SI_ZMPWS_DATAAGRO_ANULACION_CONTRATOResponse(Molinos.DataAgro.Agent.AnulacionContratos.Z_MPRFC_ANULACION_CONTRATOResponse Z_MPRFC_ANULACION_CONTRATOResponse) {
            this.Z_MPRFC_ANULACION_CONTRATOResponse = Z_MPRFC_ANULACION_CONTRATOResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_ZMPWS_DATAAGRO_ANULACION_CONTRATOChannel : Molinos.DataAgro.Agent.AnulacionContratos.SI_ZMPWS_DATAAGRO_ANULACION_CONTRATO, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_ZMPWS_DATAAGRO_ANULACION_CONTRATOClient : System.ServiceModel.ClientBase<Molinos.DataAgro.Agent.AnulacionContratos.SI_ZMPWS_DATAAGRO_ANULACION_CONTRATO>, Molinos.DataAgro.Agent.AnulacionContratos.SI_ZMPWS_DATAAGRO_ANULACION_CONTRATO {
        
        public SI_ZMPWS_DATAAGRO_ANULACION_CONTRATOClient() {
        }
        
        public SI_ZMPWS_DATAAGRO_ANULACION_CONTRATOClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SI_ZMPWS_DATAAGRO_ANULACION_CONTRATOClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_ZMPWS_DATAAGRO_ANULACION_CONTRATOClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_ZMPWS_DATAAGRO_ANULACION_CONTRATOClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Molinos.DataAgro.Agent.AnulacionContratos.SI_ZMPWS_DATAAGRO_ANULACION_CONTRATOResponse Molinos.DataAgro.Agent.AnulacionContratos.SI_ZMPWS_DATAAGRO_ANULACION_CONTRATO.SI_ZMPWS_DATAAGRO_ANULACION_CONTRATO(Molinos.DataAgro.Agent.AnulacionContratos.SI_ZMPWS_DATAAGRO_ANULACION_CONTRATORequest request) {
            return base.Channel.SI_ZMPWS_DATAAGRO_ANULACION_CONTRATO(request);
        }
        
        public Molinos.DataAgro.Agent.AnulacionContratos.Z_MPRFC_ANULACION_CONTRATOResponse SI_ZMPWS_DATAAGRO_ANULACION_CONTRATO(Molinos.DataAgro.Agent.AnulacionContratos.Z_MPRFC_ANULACION_CONTRATO Z_MPRFC_ANULACION_CONTRATO) {
            Molinos.DataAgro.Agent.AnulacionContratos.SI_ZMPWS_DATAAGRO_ANULACION_CONTRATORequest inValue = new Molinos.DataAgro.Agent.AnulacionContratos.SI_ZMPWS_DATAAGRO_ANULACION_CONTRATORequest();
            inValue.Z_MPRFC_ANULACION_CONTRATO = Z_MPRFC_ANULACION_CONTRATO;
            Molinos.DataAgro.Agent.AnulacionContratos.SI_ZMPWS_DATAAGRO_ANULACION_CONTRATOResponse retVal = ((Molinos.DataAgro.Agent.AnulacionContratos.SI_ZMPWS_DATAAGRO_ANULACION_CONTRATO)(this)).SI_ZMPWS_DATAAGRO_ANULACION_CONTRATO(inValue);
            return retVal.Z_MPRFC_ANULACION_CONTRATOResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Molinos.DataAgro.Agent.AnulacionContratos.SI_ZMPWS_DATAAGRO_ANULACION_CONTRATOResponse> Molinos.DataAgro.Agent.AnulacionContratos.SI_ZMPWS_DATAAGRO_ANULACION_CONTRATO.SI_ZMPWS_DATAAGRO_ANULACION_CONTRATOAsync(Molinos.DataAgro.Agent.AnulacionContratos.SI_ZMPWS_DATAAGRO_ANULACION_CONTRATORequest request) {
            return base.Channel.SI_ZMPWS_DATAAGRO_ANULACION_CONTRATOAsync(request);
        }
        
        public System.Threading.Tasks.Task<Molinos.DataAgro.Agent.AnulacionContratos.SI_ZMPWS_DATAAGRO_ANULACION_CONTRATOResponse> SI_ZMPWS_DATAAGRO_ANULACION_CONTRATOAsync(Molinos.DataAgro.Agent.AnulacionContratos.Z_MPRFC_ANULACION_CONTRATO Z_MPRFC_ANULACION_CONTRATO) {
            Molinos.DataAgro.Agent.AnulacionContratos.SI_ZMPWS_DATAAGRO_ANULACION_CONTRATORequest inValue = new Molinos.DataAgro.Agent.AnulacionContratos.SI_ZMPWS_DATAAGRO_ANULACION_CONTRATORequest();
            inValue.Z_MPRFC_ANULACION_CONTRATO = Z_MPRFC_ANULACION_CONTRATO;
            return ((Molinos.DataAgro.Agent.AnulacionContratos.SI_ZMPWS_DATAAGRO_ANULACION_CONTRATO)(this)).SI_ZMPWS_DATAAGRO_ANULACION_CONTRATOAsync(inValue);
        }
    }
}
