//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Molinos.DataAgro.Agent.StatusContrato {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="namespace:dataagro", ConfigurationName="StatusContrato.SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATO")]
    public interface SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATO {
        
        // CODEGEN: Generating message contract since the operation SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATO is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Molinos.DataAgro.Agent.StatusContrato.SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATOResponse SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATO(Molinos.DataAgro.Agent.StatusContrato.SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATORequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<Molinos.DataAgro.Agent.StatusContrato.SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATOResponse> SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATOAsync(Molinos.DataAgro.Agent.StatusContrato.SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATORequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_MPRFC_STATUS_DE_CONTRATO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] iM_CONTRATOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] IM_CONTRATO {
            get {
                return this.iM_CONTRATOField;
            }
            set {
                this.iM_CONTRATOField = value;
                this.RaisePropertyChanged("IM_CONTRATO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMPES6980 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cONTRATOField;
        
        private string sTATUSField;
        
        private string nUM_SIOField;
        
        private string nO_INFORMAR_SIOField;
        
        private string fECHA_SIOField;
        
        private string fE_VUELTAField;
        
        private string mENSAJEField;
        
        private string fECHA_CONFIRField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CONTRATO {
            get {
                return this.cONTRATOField;
            }
            set {
                this.cONTRATOField = value;
                this.RaisePropertyChanged("CONTRATO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string STATUS {
            get {
                return this.sTATUSField;
            }
            set {
                this.sTATUSField = value;
                this.RaisePropertyChanged("STATUS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string NUM_SIO {
            get {
                return this.nUM_SIOField;
            }
            set {
                this.nUM_SIOField = value;
                this.RaisePropertyChanged("NUM_SIO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string NO_INFORMAR_SIO {
            get {
                return this.nO_INFORMAR_SIOField;
            }
            set {
                this.nO_INFORMAR_SIOField = value;
                this.RaisePropertyChanged("NO_INFORMAR_SIO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string FECHA_SIO {
            get {
                return this.fECHA_SIOField;
            }
            set {
                this.fECHA_SIOField = value;
                this.RaisePropertyChanged("FECHA_SIO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string FE_VUELTA {
            get {
                return this.fE_VUELTAField;
            }
            set {
                this.fE_VUELTAField = value;
                this.RaisePropertyChanged("FE_VUELTA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string MENSAJE {
            get {
                return this.mENSAJEField;
            }
            set {
                this.mENSAJEField = value;
                this.RaisePropertyChanged("MENSAJE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string FECHA_CONFIR {
            get {
                return this.fECHA_CONFIRField;
            }
            set {
                this.fECHA_CONFIRField = value;
                this.RaisePropertyChanged("FECHA_CONFIR");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_MPRFC_STATUS_DE_CONTRATOResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZMPES6980[] eX_SALIDAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZMPES6980[] EX_SALIDA {
            get {
                return this.eX_SALIDAField;
            }
            set {
                this.eX_SALIDAField = value;
                this.RaisePropertyChanged("EX_SALIDA");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATORequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public Molinos.DataAgro.Agent.StatusContrato.Z_MPRFC_STATUS_DE_CONTRATO Z_MPRFC_STATUS_DE_CONTRATO;
        
        public SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATORequest() {
        }
        
        public SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATORequest(Molinos.DataAgro.Agent.StatusContrato.Z_MPRFC_STATUS_DE_CONTRATO Z_MPRFC_STATUS_DE_CONTRATO) {
            this.Z_MPRFC_STATUS_DE_CONTRATO = Z_MPRFC_STATUS_DE_CONTRATO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATOResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public Molinos.DataAgro.Agent.StatusContrato.Z_MPRFC_STATUS_DE_CONTRATOResponse Z_MPRFC_STATUS_DE_CONTRATOResponse;
        
        public SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATOResponse() {
        }
        
        public SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATOResponse(Molinos.DataAgro.Agent.StatusContrato.Z_MPRFC_STATUS_DE_CONTRATOResponse Z_MPRFC_STATUS_DE_CONTRATOResponse) {
            this.Z_MPRFC_STATUS_DE_CONTRATOResponse = Z_MPRFC_STATUS_DE_CONTRATOResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATOChannel : Molinos.DataAgro.Agent.StatusContrato.SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATO, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATOClient : System.ServiceModel.ClientBase<Molinos.DataAgro.Agent.StatusContrato.SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATO>, Molinos.DataAgro.Agent.StatusContrato.SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATO {
        
        public SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATOClient() {
        }
        
        public SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATOClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATOClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATOClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATOClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Molinos.DataAgro.Agent.StatusContrato.SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATOResponse Molinos.DataAgro.Agent.StatusContrato.SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATO.SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATO(Molinos.DataAgro.Agent.StatusContrato.SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATORequest request) {
            return base.Channel.SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATO(request);
        }
        
        public Molinos.DataAgro.Agent.StatusContrato.Z_MPRFC_STATUS_DE_CONTRATOResponse SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATO(Molinos.DataAgro.Agent.StatusContrato.Z_MPRFC_STATUS_DE_CONTRATO Z_MPRFC_STATUS_DE_CONTRATO) {
            Molinos.DataAgro.Agent.StatusContrato.SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATORequest inValue = new Molinos.DataAgro.Agent.StatusContrato.SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATORequest();
            inValue.Z_MPRFC_STATUS_DE_CONTRATO = Z_MPRFC_STATUS_DE_CONTRATO;
            Molinos.DataAgro.Agent.StatusContrato.SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATOResponse retVal = ((Molinos.DataAgro.Agent.StatusContrato.SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATO)(this)).SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATO(inValue);
            return retVal.Z_MPRFC_STATUS_DE_CONTRATOResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Molinos.DataAgro.Agent.StatusContrato.SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATOResponse> Molinos.DataAgro.Agent.StatusContrato.SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATO.SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATOAsync(Molinos.DataAgro.Agent.StatusContrato.SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATORequest request) {
            return base.Channel.SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATOAsync(request);
        }
        
        public System.Threading.Tasks.Task<Molinos.DataAgro.Agent.StatusContrato.SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATOResponse> SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATOAsync(Molinos.DataAgro.Agent.StatusContrato.Z_MPRFC_STATUS_DE_CONTRATO Z_MPRFC_STATUS_DE_CONTRATO) {
            Molinos.DataAgro.Agent.StatusContrato.SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATORequest inValue = new Molinos.DataAgro.Agent.StatusContrato.SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATORequest();
            inValue.Z_MPRFC_STATUS_DE_CONTRATO = Z_MPRFC_STATUS_DE_CONTRATO;
            return ((Molinos.DataAgro.Agent.StatusContrato.SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATO)(this)).SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATOAsync(inValue);
        }
    }
}
