//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Molinos.DataAgro.Agent.StatusContrato {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="namespace:dataagro", ConfigurationName="StatusContrato.SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATO")]
    public interface SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATO {
        
        // CODEGEN: Generating message contract since the operation SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATO is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Molinos.DataAgro.Agent.StatusContrato.SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATOResponse SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATO(Molinos.DataAgro.Agent.StatusContrato.SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATORequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<Molinos.DataAgro.Agent.StatusContrato.SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATOResponse> SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATOAsync(Molinos.DataAgro.Agent.StatusContrato.SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATORequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_MPRFC_STATUS_DE_CONTRATO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iM_CONTRATOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string IM_CONTRATO {
            get {
                return this.iM_CONTRATOField;
            }
            set {
                this.iM_CONTRATOField = value;
                this.RaisePropertyChanged("IM_CONTRATO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_MPRFC_STATUS_DE_CONTRATOResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string eX_CONTRATOField;
        
        private string eX_FECHA_SIOField;
        
        private string eX_MENSAJEField;
        
        private string eX_NO_INFORMAR_SIOField;
        
        private string eX_NUM_SIOField;
        
        private string eX_STATUSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string EX_CONTRATO {
            get {
                return this.eX_CONTRATOField;
            }
            set {
                this.eX_CONTRATOField = value;
                this.RaisePropertyChanged("EX_CONTRATO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string EX_FECHA_SIO {
            get {
                return this.eX_FECHA_SIOField;
            }
            set {
                this.eX_FECHA_SIOField = value;
                this.RaisePropertyChanged("EX_FECHA_SIO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string EX_MENSAJE {
            get {
                return this.eX_MENSAJEField;
            }
            set {
                this.eX_MENSAJEField = value;
                this.RaisePropertyChanged("EX_MENSAJE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string EX_NO_INFORMAR_SIO {
            get {
                return this.eX_NO_INFORMAR_SIOField;
            }
            set {
                this.eX_NO_INFORMAR_SIOField = value;
                this.RaisePropertyChanged("EX_NO_INFORMAR_SIO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string EX_NUM_SIO {
            get {
                return this.eX_NUM_SIOField;
            }
            set {
                this.eX_NUM_SIOField = value;
                this.RaisePropertyChanged("EX_NUM_SIO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string EX_STATUS {
            get {
                return this.eX_STATUSField;
            }
            set {
                this.eX_STATUSField = value;
                this.RaisePropertyChanged("EX_STATUS");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATORequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public Molinos.DataAgro.Agent.StatusContrato.Z_MPRFC_STATUS_DE_CONTRATO Z_MPRFC_STATUS_DE_CONTRATO;
        
        public SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATORequest() {
        }
        
        public SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATORequest(Molinos.DataAgro.Agent.StatusContrato.Z_MPRFC_STATUS_DE_CONTRATO Z_MPRFC_STATUS_DE_CONTRATO) {
            this.Z_MPRFC_STATUS_DE_CONTRATO = Z_MPRFC_STATUS_DE_CONTRATO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATOResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public Molinos.DataAgro.Agent.StatusContrato.Z_MPRFC_STATUS_DE_CONTRATOResponse Z_MPRFC_STATUS_DE_CONTRATOResponse;
        
        public SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATOResponse() {
        }
        
        public SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATOResponse(Molinos.DataAgro.Agent.StatusContrato.Z_MPRFC_STATUS_DE_CONTRATOResponse Z_MPRFC_STATUS_DE_CONTRATOResponse) {
            this.Z_MPRFC_STATUS_DE_CONTRATOResponse = Z_MPRFC_STATUS_DE_CONTRATOResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATOChannel : Molinos.DataAgro.Agent.StatusContrato.SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATO, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATOClient : System.ServiceModel.ClientBase<Molinos.DataAgro.Agent.StatusContrato.SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATO>, Molinos.DataAgro.Agent.StatusContrato.SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATO {
        
        public SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATOClient() {
        }
        
        public SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATOClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATOClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATOClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATOClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Molinos.DataAgro.Agent.StatusContrato.SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATOResponse Molinos.DataAgro.Agent.StatusContrato.SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATO.SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATO(Molinos.DataAgro.Agent.StatusContrato.SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATORequest request) {
            return base.Channel.SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATO(request);
        }
        
        public Molinos.DataAgro.Agent.StatusContrato.Z_MPRFC_STATUS_DE_CONTRATOResponse SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATO(Molinos.DataAgro.Agent.StatusContrato.Z_MPRFC_STATUS_DE_CONTRATO Z_MPRFC_STATUS_DE_CONTRATO) {
            Molinos.DataAgro.Agent.StatusContrato.SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATORequest inValue = new Molinos.DataAgro.Agent.StatusContrato.SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATORequest();
            inValue.Z_MPRFC_STATUS_DE_CONTRATO = Z_MPRFC_STATUS_DE_CONTRATO;
            Molinos.DataAgro.Agent.StatusContrato.SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATOResponse retVal = ((Molinos.DataAgro.Agent.StatusContrato.SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATO)(this)).SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATO(inValue);
            return retVal.Z_MPRFC_STATUS_DE_CONTRATOResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Molinos.DataAgro.Agent.StatusContrato.SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATOResponse> Molinos.DataAgro.Agent.StatusContrato.SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATO.SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATOAsync(Molinos.DataAgro.Agent.StatusContrato.SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATORequest request) {
            return base.Channel.SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATOAsync(request);
        }
        
        public System.Threading.Tasks.Task<Molinos.DataAgro.Agent.StatusContrato.SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATOResponse> SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATOAsync(Molinos.DataAgro.Agent.StatusContrato.Z_MPRFC_STATUS_DE_CONTRATO Z_MPRFC_STATUS_DE_CONTRATO) {
            Molinos.DataAgro.Agent.StatusContrato.SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATORequest inValue = new Molinos.DataAgro.Agent.StatusContrato.SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATORequest();
            inValue.Z_MPRFC_STATUS_DE_CONTRATO = Z_MPRFC_STATUS_DE_CONTRATO;
            return ((Molinos.DataAgro.Agent.StatusContrato.SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATO)(this)).SI_ZMPWS_DATAAGRO_STATUS_DE_CONTRATOAsync(inValue);
        }
    }
}
