//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Molinos.DataAgro.Agent.FinalizarFijacion {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="namespace:dataagro", ConfigurationName="FinalizarFijacion.SI_ZMPWS_DATAAGRO_REGISTRAR_FIJACION")]
    public interface SI_ZMPWS_DATAAGRO_REGISTRAR_FIJACION {
        
        // CODEGEN: Generating message contract since the operation SI_ZMPWS_DATAAGRO_REGISTRAR_FIJACION is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Molinos.DataAgro.Agent.FinalizarFijacion.SI_ZMPWS_DATAAGRO_REGISTRAR_FIJACIONResponse SI_ZMPWS_DATAAGRO_REGISTRAR_FIJACION(Molinos.DataAgro.Agent.FinalizarFijacion.SI_ZMPWS_DATAAGRO_REGISTRAR_FIJACIONRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<Molinos.DataAgro.Agent.FinalizarFijacion.SI_ZMPWS_DATAAGRO_REGISTRAR_FIJACIONResponse> SI_ZMPWS_DATAAGRO_REGISTRAR_FIJACIONAsync(Molinos.DataAgro.Agent.FinalizarFijacion.SI_ZMPWS_DATAAGRO_REGISTRAR_FIJACIONRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_MPRFC_REGISTRAR_FIJACION : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iM_CONTRATOField;
        
        private string iM_CORREDORField;
        
        private decimal iM_KILOSField;
        
        private string iM_MATERIALField;
        
        private string iM_MONEDAField;
        
        private decimal iM_PRECIOField;
        
        private string iM_PROVEEDORField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string IM_CONTRATO {
            get {
                return this.iM_CONTRATOField;
            }
            set {
                this.iM_CONTRATOField = value;
                this.RaisePropertyChanged("IM_CONTRATO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string IM_CORREDOR {
            get {
                return this.iM_CORREDORField;
            }
            set {
                this.iM_CORREDORField = value;
                this.RaisePropertyChanged("IM_CORREDOR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal IM_KILOS {
            get {
                return this.iM_KILOSField;
            }
            set {
                this.iM_KILOSField = value;
                this.RaisePropertyChanged("IM_KILOS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string IM_MATERIAL {
            get {
                return this.iM_MATERIALField;
            }
            set {
                this.iM_MATERIALField = value;
                this.RaisePropertyChanged("IM_MATERIAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string IM_MONEDA {
            get {
                return this.iM_MONEDAField;
            }
            set {
                this.iM_MONEDAField = value;
                this.RaisePropertyChanged("IM_MONEDA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal IM_PRECIO {
            get {
                return this.iM_PRECIOField;
            }
            set {
                this.iM_PRECIOField = value;
                this.RaisePropertyChanged("IM_PRECIO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string IM_PROVEEDOR {
            get {
                return this.iM_PROVEEDORField;
            }
            set {
                this.iM_PROVEEDORField = value;
                this.RaisePropertyChanged("IM_PROVEEDOR");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_MPRFC_REGISTRAR_FIJACIONResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string eX_MENSAJEField;
        
        private string eX_SALIDAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string EX_MENSAJE {
            get {
                return this.eX_MENSAJEField;
            }
            set {
                this.eX_MENSAJEField = value;
                this.RaisePropertyChanged("EX_MENSAJE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string EX_SALIDA {
            get {
                return this.eX_SALIDAField;
            }
            set {
                this.eX_SALIDAField = value;
                this.RaisePropertyChanged("EX_SALIDA");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_ZMPWS_DATAAGRO_REGISTRAR_FIJACIONRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public Molinos.DataAgro.Agent.FinalizarFijacion.Z_MPRFC_REGISTRAR_FIJACION Z_MPRFC_REGISTRAR_FIJACION;
        
        public SI_ZMPWS_DATAAGRO_REGISTRAR_FIJACIONRequest() {
        }
        
        public SI_ZMPWS_DATAAGRO_REGISTRAR_FIJACIONRequest(Molinos.DataAgro.Agent.FinalizarFijacion.Z_MPRFC_REGISTRAR_FIJACION Z_MPRFC_REGISTRAR_FIJACION) {
            this.Z_MPRFC_REGISTRAR_FIJACION = Z_MPRFC_REGISTRAR_FIJACION;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_ZMPWS_DATAAGRO_REGISTRAR_FIJACIONResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public Molinos.DataAgro.Agent.FinalizarFijacion.Z_MPRFC_REGISTRAR_FIJACIONResponse Z_MPRFC_REGISTRAR_FIJACIONResponse;
        
        public SI_ZMPWS_DATAAGRO_REGISTRAR_FIJACIONResponse() {
        }
        
        public SI_ZMPWS_DATAAGRO_REGISTRAR_FIJACIONResponse(Molinos.DataAgro.Agent.FinalizarFijacion.Z_MPRFC_REGISTRAR_FIJACIONResponse Z_MPRFC_REGISTRAR_FIJACIONResponse) {
            this.Z_MPRFC_REGISTRAR_FIJACIONResponse = Z_MPRFC_REGISTRAR_FIJACIONResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_ZMPWS_DATAAGRO_REGISTRAR_FIJACIONChannel : Molinos.DataAgro.Agent.FinalizarFijacion.SI_ZMPWS_DATAAGRO_REGISTRAR_FIJACION, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_ZMPWS_DATAAGRO_REGISTRAR_FIJACIONClient : System.ServiceModel.ClientBase<Molinos.DataAgro.Agent.FinalizarFijacion.SI_ZMPWS_DATAAGRO_REGISTRAR_FIJACION>, Molinos.DataAgro.Agent.FinalizarFijacion.SI_ZMPWS_DATAAGRO_REGISTRAR_FIJACION {
        
        public SI_ZMPWS_DATAAGRO_REGISTRAR_FIJACIONClient() {
        }
        
        public SI_ZMPWS_DATAAGRO_REGISTRAR_FIJACIONClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SI_ZMPWS_DATAAGRO_REGISTRAR_FIJACIONClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_ZMPWS_DATAAGRO_REGISTRAR_FIJACIONClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_ZMPWS_DATAAGRO_REGISTRAR_FIJACIONClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Molinos.DataAgro.Agent.FinalizarFijacion.SI_ZMPWS_DATAAGRO_REGISTRAR_FIJACIONResponse Molinos.DataAgro.Agent.FinalizarFijacion.SI_ZMPWS_DATAAGRO_REGISTRAR_FIJACION.SI_ZMPWS_DATAAGRO_REGISTRAR_FIJACION(Molinos.DataAgro.Agent.FinalizarFijacion.SI_ZMPWS_DATAAGRO_REGISTRAR_FIJACIONRequest request) {
            return base.Channel.SI_ZMPWS_DATAAGRO_REGISTRAR_FIJACION(request);
        }
        
        public Molinos.DataAgro.Agent.FinalizarFijacion.Z_MPRFC_REGISTRAR_FIJACIONResponse SI_ZMPWS_DATAAGRO_REGISTRAR_FIJACION(Molinos.DataAgro.Agent.FinalizarFijacion.Z_MPRFC_REGISTRAR_FIJACION Z_MPRFC_REGISTRAR_FIJACION) {
            Molinos.DataAgro.Agent.FinalizarFijacion.SI_ZMPWS_DATAAGRO_REGISTRAR_FIJACIONRequest inValue = new Molinos.DataAgro.Agent.FinalizarFijacion.SI_ZMPWS_DATAAGRO_REGISTRAR_FIJACIONRequest();
            inValue.Z_MPRFC_REGISTRAR_FIJACION = Z_MPRFC_REGISTRAR_FIJACION;
            Molinos.DataAgro.Agent.FinalizarFijacion.SI_ZMPWS_DATAAGRO_REGISTRAR_FIJACIONResponse retVal = ((Molinos.DataAgro.Agent.FinalizarFijacion.SI_ZMPWS_DATAAGRO_REGISTRAR_FIJACION)(this)).SI_ZMPWS_DATAAGRO_REGISTRAR_FIJACION(inValue);
            return retVal.Z_MPRFC_REGISTRAR_FIJACIONResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Molinos.DataAgro.Agent.FinalizarFijacion.SI_ZMPWS_DATAAGRO_REGISTRAR_FIJACIONResponse> Molinos.DataAgro.Agent.FinalizarFijacion.SI_ZMPWS_DATAAGRO_REGISTRAR_FIJACION.SI_ZMPWS_DATAAGRO_REGISTRAR_FIJACIONAsync(Molinos.DataAgro.Agent.FinalizarFijacion.SI_ZMPWS_DATAAGRO_REGISTRAR_FIJACIONRequest request) {
            return base.Channel.SI_ZMPWS_DATAAGRO_REGISTRAR_FIJACIONAsync(request);
        }
        
        public System.Threading.Tasks.Task<Molinos.DataAgro.Agent.FinalizarFijacion.SI_ZMPWS_DATAAGRO_REGISTRAR_FIJACIONResponse> SI_ZMPWS_DATAAGRO_REGISTRAR_FIJACIONAsync(Molinos.DataAgro.Agent.FinalizarFijacion.Z_MPRFC_REGISTRAR_FIJACION Z_MPRFC_REGISTRAR_FIJACION) {
            Molinos.DataAgro.Agent.FinalizarFijacion.SI_ZMPWS_DATAAGRO_REGISTRAR_FIJACIONRequest inValue = new Molinos.DataAgro.Agent.FinalizarFijacion.SI_ZMPWS_DATAAGRO_REGISTRAR_FIJACIONRequest();
            inValue.Z_MPRFC_REGISTRAR_FIJACION = Z_MPRFC_REGISTRAR_FIJACION;
            return ((Molinos.DataAgro.Agent.FinalizarFijacion.SI_ZMPWS_DATAAGRO_REGISTRAR_FIJACION)(this)).SI_ZMPWS_DATAAGRO_REGISTRAR_FIJACIONAsync(inValue);
        }
    }
}
