//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Molinos.DataAgro.Agent.DisponibilidadCupos {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="namespace:dataagro", ConfigurationName="DisponibilidadCupos.SI_ZMPWS_DATAAGRO_DISPONIBILIDAD_CUPOS")]
    public interface SI_ZMPWS_DATAAGRO_DISPONIBILIDAD_CUPOS {
        
        // CODEGEN: Generating message contract since the operation SI_ZMPWS_DATAAGRO_DISPONIBILIDAD_CUPOS is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Molinos.DataAgro.Agent.DisponibilidadCupos.SI_ZMPWS_DATAAGRO_DISPONIBILIDAD_CUPOSResponse SI_ZMPWS_DATAAGRO_DISPONIBILIDAD_CUPOS(Molinos.DataAgro.Agent.DisponibilidadCupos.SI_ZMPWS_DATAAGRO_DISPONIBILIDAD_CUPOSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<Molinos.DataAgro.Agent.DisponibilidadCupos.SI_ZMPWS_DATAAGRO_DISPONIBILIDAD_CUPOSResponse> SI_ZMPWS_DATAAGRO_DISPONIBILIDAD_CUPOSAsync(Molinos.DataAgro.Agent.DisponibilidadCupos.SI_ZMPWS_DATAAGRO_DISPONIBILIDAD_CUPOSRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_MPRFC_DISPONIBILIDAD_CUPOS : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iM_CENTROField;
        
        private string iM_FECHAField;
        
        private string iM_MATERIALField;
        
        private string iM_ZONAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string IM_CENTRO {
            get {
                return this.iM_CENTROField;
            }
            set {
                this.iM_CENTROField = value;
                this.RaisePropertyChanged("IM_CENTRO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string IM_FECHA {
            get {
                return this.iM_FECHAField;
            }
            set {
                this.iM_FECHAField = value;
                this.RaisePropertyChanged("IM_FECHA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string IM_MATERIAL {
            get {
                return this.iM_MATERIALField;
            }
            set {
                this.iM_MATERIALField = value;
                this.RaisePropertyChanged("IM_MATERIAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string IM_ZONA {
            get {
                return this.iM_ZONAField;
            }
            set {
                this.iM_ZONAField = value;
                this.RaisePropertyChanged("IM_ZONA");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMPES5600 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fECHAField;
        
        private string mATERIALField;
        
        private string zONAField;
        
        private string dISPONIBLESField;
        
        private string cONSUMIDOSField;
        
        private string lIMITE_CUPOSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string FECHA {
            get {
                return this.fECHAField;
            }
            set {
                this.fECHAField = value;
                this.RaisePropertyChanged("FECHA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string MATERIAL {
            get {
                return this.mATERIALField;
            }
            set {
                this.mATERIALField = value;
                this.RaisePropertyChanged("MATERIAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ZONA {
            get {
                return this.zONAField;
            }
            set {
                this.zONAField = value;
                this.RaisePropertyChanged("ZONA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string DISPONIBLES {
            get {
                return this.dISPONIBLESField;
            }
            set {
                this.dISPONIBLESField = value;
                this.RaisePropertyChanged("DISPONIBLES");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string CONSUMIDOS {
            get {
                return this.cONSUMIDOSField;
            }
            set {
                this.cONSUMIDOSField = value;
                this.RaisePropertyChanged("CONSUMIDOS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string LIMITE_CUPOS {
            get {
                return this.lIMITE_CUPOSField;
            }
            set {
                this.lIMITE_CUPOSField = value;
                this.RaisePropertyChanged("LIMITE_CUPOS");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_MPRFC_DISPONIBILIDAD_CUPOSResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZMPES5600[] eX_SALIDAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZMPES5600[] EX_SALIDA {
            get {
                return this.eX_SALIDAField;
            }
            set {
                this.eX_SALIDAField = value;
                this.RaisePropertyChanged("EX_SALIDA");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_ZMPWS_DATAAGRO_DISPONIBILIDAD_CUPOSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public Molinos.DataAgro.Agent.DisponibilidadCupos.Z_MPRFC_DISPONIBILIDAD_CUPOS Z_MPRFC_DISPONIBILIDAD_CUPOS;
        
        public SI_ZMPWS_DATAAGRO_DISPONIBILIDAD_CUPOSRequest() {
        }
        
        public SI_ZMPWS_DATAAGRO_DISPONIBILIDAD_CUPOSRequest(Molinos.DataAgro.Agent.DisponibilidadCupos.Z_MPRFC_DISPONIBILIDAD_CUPOS Z_MPRFC_DISPONIBILIDAD_CUPOS) {
            this.Z_MPRFC_DISPONIBILIDAD_CUPOS = Z_MPRFC_DISPONIBILIDAD_CUPOS;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_ZMPWS_DATAAGRO_DISPONIBILIDAD_CUPOSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public Molinos.DataAgro.Agent.DisponibilidadCupos.Z_MPRFC_DISPONIBILIDAD_CUPOSResponse Z_MPRFC_DISPONIBILIDAD_CUPOSResponse;
        
        public SI_ZMPWS_DATAAGRO_DISPONIBILIDAD_CUPOSResponse() {
        }
        
        public SI_ZMPWS_DATAAGRO_DISPONIBILIDAD_CUPOSResponse(Molinos.DataAgro.Agent.DisponibilidadCupos.Z_MPRFC_DISPONIBILIDAD_CUPOSResponse Z_MPRFC_DISPONIBILIDAD_CUPOSResponse) {
            this.Z_MPRFC_DISPONIBILIDAD_CUPOSResponse = Z_MPRFC_DISPONIBILIDAD_CUPOSResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_ZMPWS_DATAAGRO_DISPONIBILIDAD_CUPOSChannel : Molinos.DataAgro.Agent.DisponibilidadCupos.SI_ZMPWS_DATAAGRO_DISPONIBILIDAD_CUPOS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_ZMPWS_DATAAGRO_DISPONIBILIDAD_CUPOSClient : System.ServiceModel.ClientBase<Molinos.DataAgro.Agent.DisponibilidadCupos.SI_ZMPWS_DATAAGRO_DISPONIBILIDAD_CUPOS>, Molinos.DataAgro.Agent.DisponibilidadCupos.SI_ZMPWS_DATAAGRO_DISPONIBILIDAD_CUPOS {
        
        public SI_ZMPWS_DATAAGRO_DISPONIBILIDAD_CUPOSClient() {
        }
        
        public SI_ZMPWS_DATAAGRO_DISPONIBILIDAD_CUPOSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SI_ZMPWS_DATAAGRO_DISPONIBILIDAD_CUPOSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_ZMPWS_DATAAGRO_DISPONIBILIDAD_CUPOSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_ZMPWS_DATAAGRO_DISPONIBILIDAD_CUPOSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Molinos.DataAgro.Agent.DisponibilidadCupos.SI_ZMPWS_DATAAGRO_DISPONIBILIDAD_CUPOSResponse Molinos.DataAgro.Agent.DisponibilidadCupos.SI_ZMPWS_DATAAGRO_DISPONIBILIDAD_CUPOS.SI_ZMPWS_DATAAGRO_DISPONIBILIDAD_CUPOS(Molinos.DataAgro.Agent.DisponibilidadCupos.SI_ZMPWS_DATAAGRO_DISPONIBILIDAD_CUPOSRequest request) {
            return base.Channel.SI_ZMPWS_DATAAGRO_DISPONIBILIDAD_CUPOS(request);
        }
        
        public Molinos.DataAgro.Agent.DisponibilidadCupos.Z_MPRFC_DISPONIBILIDAD_CUPOSResponse SI_ZMPWS_DATAAGRO_DISPONIBILIDAD_CUPOS(Molinos.DataAgro.Agent.DisponibilidadCupos.Z_MPRFC_DISPONIBILIDAD_CUPOS Z_MPRFC_DISPONIBILIDAD_CUPOS) {
            Molinos.DataAgro.Agent.DisponibilidadCupos.SI_ZMPWS_DATAAGRO_DISPONIBILIDAD_CUPOSRequest inValue = new Molinos.DataAgro.Agent.DisponibilidadCupos.SI_ZMPWS_DATAAGRO_DISPONIBILIDAD_CUPOSRequest();
            inValue.Z_MPRFC_DISPONIBILIDAD_CUPOS = Z_MPRFC_DISPONIBILIDAD_CUPOS;
            Molinos.DataAgro.Agent.DisponibilidadCupos.SI_ZMPWS_DATAAGRO_DISPONIBILIDAD_CUPOSResponse retVal = ((Molinos.DataAgro.Agent.DisponibilidadCupos.SI_ZMPWS_DATAAGRO_DISPONIBILIDAD_CUPOS)(this)).SI_ZMPWS_DATAAGRO_DISPONIBILIDAD_CUPOS(inValue);
            return retVal.Z_MPRFC_DISPONIBILIDAD_CUPOSResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Molinos.DataAgro.Agent.DisponibilidadCupos.SI_ZMPWS_DATAAGRO_DISPONIBILIDAD_CUPOSResponse> Molinos.DataAgro.Agent.DisponibilidadCupos.SI_ZMPWS_DATAAGRO_DISPONIBILIDAD_CUPOS.SI_ZMPWS_DATAAGRO_DISPONIBILIDAD_CUPOSAsync(Molinos.DataAgro.Agent.DisponibilidadCupos.SI_ZMPWS_DATAAGRO_DISPONIBILIDAD_CUPOSRequest request) {
            return base.Channel.SI_ZMPWS_DATAAGRO_DISPONIBILIDAD_CUPOSAsync(request);
        }
        
        public System.Threading.Tasks.Task<Molinos.DataAgro.Agent.DisponibilidadCupos.SI_ZMPWS_DATAAGRO_DISPONIBILIDAD_CUPOSResponse> SI_ZMPWS_DATAAGRO_DISPONIBILIDAD_CUPOSAsync(Molinos.DataAgro.Agent.DisponibilidadCupos.Z_MPRFC_DISPONIBILIDAD_CUPOS Z_MPRFC_DISPONIBILIDAD_CUPOS) {
            Molinos.DataAgro.Agent.DisponibilidadCupos.SI_ZMPWS_DATAAGRO_DISPONIBILIDAD_CUPOSRequest inValue = new Molinos.DataAgro.Agent.DisponibilidadCupos.SI_ZMPWS_DATAAGRO_DISPONIBILIDAD_CUPOSRequest();
            inValue.Z_MPRFC_DISPONIBILIDAD_CUPOS = Z_MPRFC_DISPONIBILIDAD_CUPOS;
            return ((Molinos.DataAgro.Agent.DisponibilidadCupos.SI_ZMPWS_DATAAGRO_DISPONIBILIDAD_CUPOS)(this)).SI_ZMPWS_DATAAGRO_DISPONIBILIDAD_CUPOSAsync(inValue);
        }
    }
}
