//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Molinos.DataAgro.Agent.ConfirmaQAConsultaLote {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://confirma.com.ar/gd/2012/05/consultalote", ConfigurationName="ConfirmaQAConsultaLote.IConsultaLoteDocumentosService")]
    public interface IConsultaLoteDocumentosService {
        
        // CODEGEN: Generating message contract since the operation consultaLote is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://confirma.com.ar/gd/2012/05/IConsultaLoteDocumentosService/consultaLote", ReplyAction="http://confirma.com.ar/gd/2012/05/consultalote/IConsultaLoteDocumentosService/con" +
            "sultaLoteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Molinos.DataAgro.Agent.ConfirmaQAConsultaLote.consultaLoteResponse consultaLote(Molinos.DataAgro.Agent.ConfirmaQAConsultaLote.consultaLoteInvoke request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://confirma.com.ar/gd/2012/05/IConsultaLoteDocumentosService/consultaLote", ReplyAction="http://confirma.com.ar/gd/2012/05/consultalote/IConsultaLoteDocumentosService/con" +
            "sultaLoteResponse")]
        System.Threading.Tasks.Task<Molinos.DataAgro.Agent.ConfirmaQAConsultaLote.consultaLoteResponse> consultaLoteAsync(Molinos.DataAgro.Agent.ConfirmaQAConsultaLote.consultaLoteInvoke request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://confirma.com.ar/gd/2012/05/WSConsultaLoteSchema")]
    public partial class consultaLote : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string consultaIdLoteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string consultaIdLote {
            get {
                return this.consultaIdLoteField;
            }
            set {
                this.consultaIdLoteField = value;
                this.RaisePropertyChanged("consultaIdLote");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://confirma.com.ar/gd/2012/05/WSConsultaLoteResponseSchema")]
    public partial class consultaItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string consultaIdDocumentoField;
        
        private consultaItemConsultaEstadoDocumento consultaEstadoDocumentoField;
        
        private string[] consultaErroresField;
        
        private string codigoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string consultaIdDocumento {
            get {
                return this.consultaIdDocumentoField;
            }
            set {
                this.consultaIdDocumentoField = value;
                this.RaisePropertyChanged("consultaIdDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public consultaItemConsultaEstadoDocumento consultaEstadoDocumento {
            get {
                return this.consultaEstadoDocumentoField;
            }
            set {
                this.consultaEstadoDocumentoField = value;
                this.RaisePropertyChanged("consultaEstadoDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("consultaError", IsNullable=false)]
        public string[] consultaErrores {
            get {
                return this.consultaErroresField;
            }
            set {
                this.consultaErroresField = value;
                this.RaisePropertyChanged("consultaErrores");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://confirma.com.ar/gd/2012/05/WSConsultaLoteResponseSchema")]
    public enum consultaItemConsultaEstadoDocumento {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://confirma.com.ar/gd/2012/05/WSConsultaLoteResponseSchema")]
    public partial class consultaLoteResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string consultaIdLoteField;
        
        private consultaLoteResultConsultaEstado consultaEstadoField;
        
        private bool consultaEstadoFieldSpecified;
        
        private consultaLoteResultConsultaEstadoLote consultaEstadoLoteField;
        
        private bool consultaEstadoLoteFieldSpecified;
        
        private consultaItem[] consultaItemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string consultaIdLote {
            get {
                return this.consultaIdLoteField;
            }
            set {
                this.consultaIdLoteField = value;
                this.RaisePropertyChanged("consultaIdLote");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public consultaLoteResultConsultaEstado consultaEstado {
            get {
                return this.consultaEstadoField;
            }
            set {
                this.consultaEstadoField = value;
                this.RaisePropertyChanged("consultaEstado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool consultaEstadoSpecified {
            get {
                return this.consultaEstadoFieldSpecified;
            }
            set {
                this.consultaEstadoFieldSpecified = value;
                this.RaisePropertyChanged("consultaEstadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public consultaLoteResultConsultaEstadoLote consultaEstadoLote {
            get {
                return this.consultaEstadoLoteField;
            }
            set {
                this.consultaEstadoLoteField = value;
                this.RaisePropertyChanged("consultaEstadoLote");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool consultaEstadoLoteSpecified {
            get {
                return this.consultaEstadoLoteFieldSpecified;
            }
            set {
                this.consultaEstadoLoteFieldSpecified = value;
                this.RaisePropertyChanged("consultaEstadoLoteSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("consultaItem", Order=3)]
        public consultaItem[] consultaItem {
            get {
                return this.consultaItemField;
            }
            set {
                this.consultaItemField = value;
                this.RaisePropertyChanged("consultaItem");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://confirma.com.ar/gd/2012/05/WSConsultaLoteResponseSchema")]
    public enum consultaLoteResultConsultaEstado {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://confirma.com.ar/gd/2012/05/WSConsultaLoteResponseSchema")]
    public enum consultaLoteResultConsultaEstadoLote {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaLoteInvoke {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://confirma.com.ar/gd/2012/05/consultalotedocumentos", Order=0)]
        public Molinos.DataAgro.Agent.ConfirmaQAConsultaLote.consultaLote ConsultaLote;
        
        public consultaLoteInvoke() {
        }
        
        public consultaLoteInvoke(Molinos.DataAgro.Agent.ConfirmaQAConsultaLote.consultaLote ConsultaLote) {
            this.ConsultaLote = ConsultaLote;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaLoteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://confirma.com.ar/gd/2012/05/consultalote", Order=0)]
        public Molinos.DataAgro.Agent.ConfirmaQAConsultaLote.consultaLoteResult ConsultaLoteResult;
        
        public consultaLoteResponse() {
        }
        
        public consultaLoteResponse(Molinos.DataAgro.Agent.ConfirmaQAConsultaLote.consultaLoteResult ConsultaLoteResult) {
            this.ConsultaLoteResult = ConsultaLoteResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConsultaLoteDocumentosServiceChannel : Molinos.DataAgro.Agent.ConfirmaQAConsultaLote.IConsultaLoteDocumentosService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsultaLoteDocumentosServiceClient : System.ServiceModel.ClientBase<Molinos.DataAgro.Agent.ConfirmaQAConsultaLote.IConsultaLoteDocumentosService>, Molinos.DataAgro.Agent.ConfirmaQAConsultaLote.IConsultaLoteDocumentosService {
        
        public ConsultaLoteDocumentosServiceClient() {
        }
        
        public ConsultaLoteDocumentosServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConsultaLoteDocumentosServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultaLoteDocumentosServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultaLoteDocumentosServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Molinos.DataAgro.Agent.ConfirmaQAConsultaLote.consultaLoteResponse Molinos.DataAgro.Agent.ConfirmaQAConsultaLote.IConsultaLoteDocumentosService.consultaLote(Molinos.DataAgro.Agent.ConfirmaQAConsultaLote.consultaLoteInvoke request) {
            return base.Channel.consultaLote(request);
        }
        
        public Molinos.DataAgro.Agent.ConfirmaQAConsultaLote.consultaLoteResult consultaLote(Molinos.DataAgro.Agent.ConfirmaQAConsultaLote.consultaLote ConsultaLote1) {
            Molinos.DataAgro.Agent.ConfirmaQAConsultaLote.consultaLoteInvoke inValue = new Molinos.DataAgro.Agent.ConfirmaQAConsultaLote.consultaLoteInvoke();
            inValue.ConsultaLote = ConsultaLote1;
            Molinos.DataAgro.Agent.ConfirmaQAConsultaLote.consultaLoteResponse retVal = ((Molinos.DataAgro.Agent.ConfirmaQAConsultaLote.IConsultaLoteDocumentosService)(this)).consultaLote(inValue);
            return retVal.ConsultaLoteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Molinos.DataAgro.Agent.ConfirmaQAConsultaLote.consultaLoteResponse> Molinos.DataAgro.Agent.ConfirmaQAConsultaLote.IConsultaLoteDocumentosService.consultaLoteAsync(Molinos.DataAgro.Agent.ConfirmaQAConsultaLote.consultaLoteInvoke request) {
            return base.Channel.consultaLoteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Molinos.DataAgro.Agent.ConfirmaQAConsultaLote.consultaLoteResponse> consultaLoteAsync(Molinos.DataAgro.Agent.ConfirmaQAConsultaLote.consultaLote ConsultaLote) {
            Molinos.DataAgro.Agent.ConfirmaQAConsultaLote.consultaLoteInvoke inValue = new Molinos.DataAgro.Agent.ConfirmaQAConsultaLote.consultaLoteInvoke();
            inValue.ConsultaLote = ConsultaLote;
            return ((Molinos.DataAgro.Agent.ConfirmaQAConsultaLote.IConsultaLoteDocumentosService)(this)).consultaLoteAsync(inValue);
        }
    }
}
