//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Molinos.DataAgro.Agent.RiesgoComercial {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="namespace:dataagro", ConfigurationName="RiesgoComercial.SI_ZMPWS_DATAAGRO_RIESGO_COMERCIAL")]
    public interface SI_ZMPWS_DATAAGRO_RIESGO_COMERCIAL {
        
        // CODEGEN: Generating message contract since the operation SI_ZMPWS_DATAAGRO_RIESGO_COMERCIAL is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Molinos.DataAgro.Agent.RiesgoComercial.SI_ZMPWS_DATAAGRO_RIESGO_COMERCIALResponse SI_ZMPWS_DATAAGRO_RIESGO_COMERCIAL(Molinos.DataAgro.Agent.RiesgoComercial.SI_ZMPWS_DATAAGRO_RIESGO_COMERCIALRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<Molinos.DataAgro.Agent.RiesgoComercial.SI_ZMPWS_DATAAGRO_RIESGO_COMERCIALResponse> SI_ZMPWS_DATAAGRO_RIESGO_COMERCIALAsync(Molinos.DataAgro.Agent.RiesgoComercial.SI_ZMPWS_DATAAGRO_RIESGO_COMERCIALRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_MPRFC_RIESGO_COMERCIAL : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iM_CUITField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string IM_CUIT {
            get {
                return this.iM_CUITField;
            }
            set {
                this.iM_CUITField = value;
                this.RaisePropertyChanged("IM_CUIT");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_MPRFC_RIESGO_COMERCIALResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string eX_RIESGOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string EX_RIESGO {
            get {
                return this.eX_RIESGOField;
            }
            set {
                this.eX_RIESGOField = value;
                this.RaisePropertyChanged("EX_RIESGO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_ZMPWS_DATAAGRO_RIESGO_COMERCIALRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public Molinos.DataAgro.Agent.RiesgoComercial.Z_MPRFC_RIESGO_COMERCIAL Z_MPRFC_RIESGO_COMERCIAL;
        
        public SI_ZMPWS_DATAAGRO_RIESGO_COMERCIALRequest() {
        }
        
        public SI_ZMPWS_DATAAGRO_RIESGO_COMERCIALRequest(Molinos.DataAgro.Agent.RiesgoComercial.Z_MPRFC_RIESGO_COMERCIAL Z_MPRFC_RIESGO_COMERCIAL) {
            this.Z_MPRFC_RIESGO_COMERCIAL = Z_MPRFC_RIESGO_COMERCIAL;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_ZMPWS_DATAAGRO_RIESGO_COMERCIALResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public Molinos.DataAgro.Agent.RiesgoComercial.Z_MPRFC_RIESGO_COMERCIALResponse Z_MPRFC_RIESGO_COMERCIALResponse;
        
        public SI_ZMPWS_DATAAGRO_RIESGO_COMERCIALResponse() {
        }
        
        public SI_ZMPWS_DATAAGRO_RIESGO_COMERCIALResponse(Molinos.DataAgro.Agent.RiesgoComercial.Z_MPRFC_RIESGO_COMERCIALResponse Z_MPRFC_RIESGO_COMERCIALResponse) {
            this.Z_MPRFC_RIESGO_COMERCIALResponse = Z_MPRFC_RIESGO_COMERCIALResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_ZMPWS_DATAAGRO_RIESGO_COMERCIALChannel : Molinos.DataAgro.Agent.RiesgoComercial.SI_ZMPWS_DATAAGRO_RIESGO_COMERCIAL, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_ZMPWS_DATAAGRO_RIESGO_COMERCIALClient : System.ServiceModel.ClientBase<Molinos.DataAgro.Agent.RiesgoComercial.SI_ZMPWS_DATAAGRO_RIESGO_COMERCIAL>, Molinos.DataAgro.Agent.RiesgoComercial.SI_ZMPWS_DATAAGRO_RIESGO_COMERCIAL {
        
        public SI_ZMPWS_DATAAGRO_RIESGO_COMERCIALClient() {
        }
        
        public SI_ZMPWS_DATAAGRO_RIESGO_COMERCIALClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SI_ZMPWS_DATAAGRO_RIESGO_COMERCIALClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_ZMPWS_DATAAGRO_RIESGO_COMERCIALClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_ZMPWS_DATAAGRO_RIESGO_COMERCIALClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Molinos.DataAgro.Agent.RiesgoComercial.SI_ZMPWS_DATAAGRO_RIESGO_COMERCIALResponse Molinos.DataAgro.Agent.RiesgoComercial.SI_ZMPWS_DATAAGRO_RIESGO_COMERCIAL.SI_ZMPWS_DATAAGRO_RIESGO_COMERCIAL(Molinos.DataAgro.Agent.RiesgoComercial.SI_ZMPWS_DATAAGRO_RIESGO_COMERCIALRequest request) {
            return base.Channel.SI_ZMPWS_DATAAGRO_RIESGO_COMERCIAL(request);
        }
        
        public Molinos.DataAgro.Agent.RiesgoComercial.Z_MPRFC_RIESGO_COMERCIALResponse SI_ZMPWS_DATAAGRO_RIESGO_COMERCIAL(Molinos.DataAgro.Agent.RiesgoComercial.Z_MPRFC_RIESGO_COMERCIAL Z_MPRFC_RIESGO_COMERCIAL) {
            Molinos.DataAgro.Agent.RiesgoComercial.SI_ZMPWS_DATAAGRO_RIESGO_COMERCIALRequest inValue = new Molinos.DataAgro.Agent.RiesgoComercial.SI_ZMPWS_DATAAGRO_RIESGO_COMERCIALRequest();
            inValue.Z_MPRFC_RIESGO_COMERCIAL = Z_MPRFC_RIESGO_COMERCIAL;
            Molinos.DataAgro.Agent.RiesgoComercial.SI_ZMPWS_DATAAGRO_RIESGO_COMERCIALResponse retVal = ((Molinos.DataAgro.Agent.RiesgoComercial.SI_ZMPWS_DATAAGRO_RIESGO_COMERCIAL)(this)).SI_ZMPWS_DATAAGRO_RIESGO_COMERCIAL(inValue);
            return retVal.Z_MPRFC_RIESGO_COMERCIALResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Molinos.DataAgro.Agent.RiesgoComercial.SI_ZMPWS_DATAAGRO_RIESGO_COMERCIALResponse> Molinos.DataAgro.Agent.RiesgoComercial.SI_ZMPWS_DATAAGRO_RIESGO_COMERCIAL.SI_ZMPWS_DATAAGRO_RIESGO_COMERCIALAsync(Molinos.DataAgro.Agent.RiesgoComercial.SI_ZMPWS_DATAAGRO_RIESGO_COMERCIALRequest request) {
            return base.Channel.SI_ZMPWS_DATAAGRO_RIESGO_COMERCIALAsync(request);
        }
        
        public System.Threading.Tasks.Task<Molinos.DataAgro.Agent.RiesgoComercial.SI_ZMPWS_DATAAGRO_RIESGO_COMERCIALResponse> SI_ZMPWS_DATAAGRO_RIESGO_COMERCIALAsync(Molinos.DataAgro.Agent.RiesgoComercial.Z_MPRFC_RIESGO_COMERCIAL Z_MPRFC_RIESGO_COMERCIAL) {
            Molinos.DataAgro.Agent.RiesgoComercial.SI_ZMPWS_DATAAGRO_RIESGO_COMERCIALRequest inValue = new Molinos.DataAgro.Agent.RiesgoComercial.SI_ZMPWS_DATAAGRO_RIESGO_COMERCIALRequest();
            inValue.Z_MPRFC_RIESGO_COMERCIAL = Z_MPRFC_RIESGO_COMERCIAL;
            return ((Molinos.DataAgro.Agent.RiesgoComercial.SI_ZMPWS_DATAAGRO_RIESGO_COMERCIAL)(this)).SI_ZMPWS_DATAAGRO_RIESGO_COMERCIALAsync(inValue);
        }
    }
}
